== Capítulo 1. La Muerte del Alma Inmortal

En el principio Dios creó buenas todas las cosas.
Al ser Él mismo inherentemente e inmutablemente bueno,
toda creación Suya debe ser necesariamente así,
según los diferentes géneros en los que Él las creó.
El hombre fue hecho enteramente por Él,
por lo tanto,
tuvo que haber sido hecho enteramente bueno también.
Su naturaleza estaba limpia de toda impureza,
y libre de todo defecto y desorden.
Sus facultades eran perfectas, aunque limitadas a su propia esfera,
y cada parte de su composición fue formada en su debida rectitud.
El cuerpo fue puesto en subordinación a su espíritu racional
o alma (la cual es la parte más noble y excelente,
creada para la inmortalidad), y ésta fue puesta en sujeción a la guía de su Creador.

Las facultades humanas estaban originalmente limpias y sin prejuicios,
y eran aptas para recibir impresiones.
Y puesto que el hombre no pudo traer con él ningún conocimiento real al mundo,
todo conocimiento tuvo que haberle sido comunicado directamente a él por Su Creador,
o después, adquirido por sí mismo a través de la observación y la experiencia.
Esto último le tomó tiempo obtenerlo,
pero no hay duda de que se encontró a sí mismo inmediatamente dotado
con suficiente entendimiento de sí mismo y de su Creador,
relacionado tanto con su deber presente como con su felicidad.

El hombre no sólo fue provisto de una medida de luz y de entendimiento,
sino que también fue facultado, sin ninguna duda, para actuar conforme a dicha medida,
de otro modo su conocimiento le habría sido dado en vano.
Siendo así, él estaba capacitado para obedecer, sin embargo,
lo que sucedió a continuación demostró que él había
sido puesto por Dios en un estado de prueba,
de lo contrario, no habría podido ser considerado culpable por su fracaso,
porque si Su Creador lo hubiera deseado,
lo habría fijado en un estado de virtud y bondad inmutable.

Es indudable que el Creador en Su omnisciencia,
previó que el hombre tendría que encontrarse con un adversario muy sutil, por lo tanto,
le proporcionó medios suficientes para descubrir sus trampas y resistir sus asaltos.
Si se le permitió a Satanás usar su sutileza e influencia para engañarlo,
ciertamente fue porque el hombre no sólo había sido advertido,
sino también dotado con suficiente luz y poder divinos para resistir sus intentos,
en la medida que se mantuviera atento a su Creador
(porque nada menor que la naturaleza divina,
puede capacitar a cualquier criatura inteligente para resistir
la tentación y actuar según la voluntad divina).

Dios creó al hombre para Su propia gloria,
así que debe caminar conforme a la voluntad de Dios
para poder glorificarlo y ser partícipe de Su gloria.
Pero el hombre no puede conocer correctamente Su voluntad,
ni llevarla a cabo constantemente, sólo con la fuerza de sus propias facultades.
Por lo tanto,
el primer hombre debe necesariamente haber sido asistido por el Espíritu de Dios,
y capacitado para cumplir Su voluntad,
de tal manera que glorificara a su Creador y respondiera
al propósito para el que fue creado.
Se concluye, entonces, que Adán primero fue creado hombre natural,
y luego hecho espiritual por medio del poder vivificante
del Espíritu de Cristo--porque "`lo espiritual no es primero,
sino lo natural; luego lo espiritual.`"^
footnote:[1 Corintios 15:45]
Esta vida espiritual es la verdadera vida,
y el elemento apropiado en el cual las almas inmortales deben vivir y moverse.

Así, los padres de la humanidad en su estado original e incorrupto,
eran templos aptos para morada del Espíritu de Dios.
Ellos eran "`participantes de la naturaleza divina,`"^
footnote:[2 Pedro 1:4]
recipientes del aliento del poder de Dios,
la influencia pura que fluye de la gloria del Altísimo.
Indudablemente,
fue a causa de la luz de esta influencia pura que Adán tenía
un discernimiento tan intuitivo de la creación,
y la capacidad de darle nombre a todas las criaturas, según sus respectivas naturalezas.
Porque leemos: "`Jehová Dios formó, pues, de la tierra toda bestia del campo,
y toda ave de los cielos, y las trajo a Adán para que viese cómo las había de llamar;
y todo lo que Adán llamó a los animales vivientes, ese es su nombre.`"^
footnote:[Génesis 2:19]

Bajo esta dotación celestial,
la santa expresión de la imagen divina estaba claramente manifiesta
en el primero de la humanidad--"`a imagen de Dios lo creó.`"^
footnote:[Génesis 1:27]

Ahora bien, si el hombre se hubiera mantenido en fiel obediencia a su Guía celestial,
y hubiese rechazado los esfuerzos del tentador, con toda certeza, y en su debido tiempo,
habría llegado a un grado de establecimiento más allá de toda posibilidad de caer;
pero al no continuar en un estado de vigilancia, y volver su atención hacia la tentación,
(contrario a la advertencia que se le había dado), dejó caer su guardia,
y dejó ir a ese Espíritu del que su vida y su fuerza dependían. En verdad,
cayó de Él y de todas Sus ventajas, y de la libertad de los hijos de Dios,
a la esclavitud de la corrupción--una introducción segura a la miseria.
(Porque tal como la santidad y la felicidad están inseparablemente unidas,
así el pecado y la miseria están indivisiblemente conectados).

Suponer que el Todopoderoso Autor de toda bondad creó al hombre con una
necesidad moral de transgredir ante la aparición de la tentación,
es una imaginación demasiado perjudicial para el carácter divino como para ser admitida.
Nuestros primeros padres fueron incuestionablemente
capacitados por su Creador para permanecer en vigilancia,
la cual les habría permitido experimentar la preservación. Su deserción de esto,
en definitiva, no fue de Dios, sino de ellos.
Si el fracaso de ellos hubiera sido por la voluntad de Dios,
o por el diseño intencional de sus circunstancias,
de modo que el pecado inevitablemente hubiera sucedido,
no habría sido congruente con Su carácter castigarlos por actuar contra Su voluntad.

Un deseo peligroso de volverse sabios en cosas dañinas e innecesarias,
parece haber tenido una entrada temprana en la mente humana.
"`El día que comáis de él, serán abiertos vuestros ojos, y seréis como Dios,
sabiendo el bien y el mal.`"^
footnote:[Génesis 3:5]
Eva fue engañada por la sugerencia de esta mentira halagadora.
Conociendo sólo el bien, podría haber permanecido feliz, pero al experimentar el mal,
se volvió otra.

Este tipo de conocimiento es tan opuesto al de la sabiduría divina,
como opuesta es la oscuridad de la luz.
Es cierto que el Dios Omnisciente conoce el bien y el mal,
pero Él conoce el bien por inmutable posesión y disfrute perfecto,
pero mira el mal con aborrecimiento,
en eterna oposición y a una infinita distancia de la pureza de Su naturaleza.
Sin embargo, con el hombre pecador el caso es lo contrario,
pues el mal tiene posesión directa de él, y el bien queda fuera de su alcance.
Sin la divina misericordia, debe permanecer completamente miserable.
Esta es la necesaria consecuencia de ese conocimiento jactancioso del mundo,
que adquieren los hombres al saborear los mortales y venenosos dulces de la tentación.

Las consecuencias de este fracaso afectaron inmediatamente a los dos transgresores,
e influyeron remotamente sobre toda su posteridad.
Adán y Eva perdieron la brillante impresión de la imagen divina,
y todas las alegrías que le correspondían. Al perder la directa,
interna y pura influencia del Santo Espíritu de Dios,
perdieron esa semejanza divina en la que habían gozado internamente de luz, vida, amor,
bondad, justicia, santidad y felicidad.
Ese Espíritu Omnipresente de poder, verdad y virtud,
que en el estado original había sido la cubierta y el consolador de ellos,
se separó por la transgresión y se convirtió entonces, en acusador y condenador de ellos.

Por haberse apartado de la debida y constante sujeción a la mente y Espíritu de su Creador,
la voluntad del hombre se separó de la voluntad de Dios,
y se convirtió en "`voluntad propia.`"
Y por su infiel auto gratificación, al dejar entrar la sugerencia del tentador,
el amor principal de los hombres se volcó de su Creador hacia sí mismos.
De esta manera,
se originaron en el hombre el "`amor propio`" desenfrenado y la "`voluntad propia,`"
lo cual siempre se encuentra en una voluntad separada de la voluntad de Dios,
y en un espíritu contrario a Su Santo Espíritu.
Además, esta separación le abrió al espíritu maligno un camino de fácil acceso,
por el cual llevar a la mente humana hacia los objetos externos,
a merced de perpetua tentación. Por darle paso a las inclinaciones carnales,
el hombre se volvió de mente carnal, y "`la mente carnal es muerte.`"^
footnote:[Romanos 8:6 (Versión Reina Valera 1602 Purificada)]

Cuando el Soberano Legislador le dio por primera vez un mandato positivo a Adán,
pronunció la muerte inmediata que recibiría en caso de transgresión:
"`El día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:17]
Esto parece implicar un significado mucho más profundo y más importante
que el significado que hace referencia al cuerpo natural.
Un significado que afecta más directamente al alma racional, a saber:
la privación de una vida que antes de la transgresión era disfrutada felizmente,
y que por la desobediencia ciertamente debía perder.

¿Cuál es entonces la verdadera vida del alma?
¿Y qué es la muerte de un alma, viendo que existe para siempre?
Simplemente existir no puede ser la vida pretendida.
La verdadera vida de un alma debe ser,
vivir en aquella vida que sólo existe en la naturaleza divina,
y que no puede ser disfrutada sino participando de la naturaleza divina; es decir,
vivir en el Espíritu de Aquel que es la vida,
la cual el Evangelista declara ser la verdadera luz de los hombres.
Este poder y virtud sobrenaturales,
espirituales y celestiales del gran Iluminador y Vivificador,
son la verdadera vida del espíritu inmortal del hombre;
y la total carencia o privación de ellos, es su muerte.

Cuando nuestros padres se apartaron de dicha vida y abrazaron la tentación,
se desviaron y murieron en espíritu a la vida divina por la que habían sido vivificados.
Porque: "`El Espíritu es el que da vida;`"^
footnote:[Juan 6:63]
y cuando se aparta la vida, la muerte se produce naturalmente.
Así como muere el cuerpo cuando se le priva de su vida natural,
así también queda el alma en un estado de muerte espiritual,
cuando se aparta de ella lo que es su verdadera vida;
excepto por esta diferencia--que el cuerpo fallecido permanece completamente insensible,
pero el alma, en su estado de muerte,
todavía existe bajo el inevitable sentido de su culpa y miseria.
