== Capítulo 3. La Oferta de Redención Perfecta

Además de la corrupción que hayamos recibido de nuestros padres,
nosotros ciertamente hemos amontonado más por cuenta propia.
"`Toda carne había corrompido su camino sobre la tierra.`"^
footnote:[Génesis 6:12]
Toda persona adulta en su estado natural ordinario, después de una seria reflexión,
encontrará en sí misma una tendencia hacia la gratificación del "`yo,`"
una inclinación ansiosa en ciertos momentos hacia el placer prohibido,
una aversión a la piedad y a la vida santa, una conciencia de culpa,
y una temerosa expectativa por el acercamiento de la muerte.
Los hombres generalmente confiesan que se han equivocado y que se han desviado
como ovejas perdidas de los sanos caminos de la virtud y del deber,
y que su fragilidad es tal, que es fácil caer en la tentación,
pero difícil (si no imposible) resistirla eficazmente.
De hecho, incluso las grandes recompensas prometidas a la virtud y a una vida santa,
y los dolorosos castigos conectados con el vicio y la locura,
son absolutamente insuficientes para mantener a los hombres en la práctica de lo primero,
o para permitirles conquistar la fuerza de su inclinación hacia lo último.

Esto demuestra claramente la corrupción de su naturaleza.
Cristo dijo: "`de la abundancia del corazón habla la boca.`"^
footnote:[Lucas 6:45]
Y así,
el hombre encuentra que toda su práctica externa
surge de lo que se aloja y gobierna en el interior.
La corrupción en el corazón afecta todas las acciones, las costumbres y el lenguaje.
De aquí brota toda la inmoralidad en la conducta, todos los discursos profanos y falsos,
y todos los intentos desesperados de las mentes vanas
para satisfacer el orgullo y la locura.
Y tal como el origen del mal en el hombre resultó de tornar su atención y deseo
del Creador a la criatura (separando así su voluntad de la voluntad de Dios,
y su espíritu del Espíritu de Dios),
asimismo la continuación del mal en el hombre sucede por la continuidad de esta separación,
y debe perdurar mientras la separación permanezca.
En esta condición, comúnmente llamada el estado natural,
no somos aptos ni capaces de entrar en el reino de los cielos,
el cual no admite nada que sea pecaminoso o inmundo.

Por lo tanto,
es absolutamente necesario que el hombre sea santificado para poder ser feliz.
La santidad no puede unirse con la inmundicia,
ni puede surgir la capacidad de la absoluta debilidad.
Si la contaminación pudiera purificarse a sí misma, si el mal pudiera producir el bien,
si la muerte pudiera producir la vida, entonces el hombre así corrompido,
debilitado y muerto, sería capaz de reformarse, vivificarse y restaurarse a sí mismo;
pero no está en el poder del hombre liberarse de los lazos del pecado y de la muerte.
Por lo tanto, así como el pecado separa al hombre de su Hacedor,
el hombre debe ser separado del pecado,
o no podrá ser reconciliado y unido a Él. Sin la restauración a un estado de santidad,
nunca podrá disfrutar de la felicidad que le pertenece a dicho estado,
porque "`sin santidad nadie verá al Señor.`"^
footnote:[Hebreos 12:14]

Entonces, ¿cómo puede el hombre corrupto llegar a ser santo?
¿Cómo, en un estado de absoluta incapacidad,
entrará en guerra contra sus muchos y poderosos adversarios
que le acosan por dentro y por fuera?
¿Qué capacidad tiene él para enfrentar a un enemigo que ya lo ha encadenado?
En efecto, un poder demasiado fuerte para el hombre ha tomado posesión, y por lo tanto,
el poder que lo libere, rescate y restaure debe ser superior.
¿Quién es suficiente para estas cosas?
Únicamente el Omnipotente Creador del hombre es capaz de desatarlo y liberarlo,
pero ¡ay!, Adán se apartó de Su voluntad, transgredió Su ley,
desobedeció Su mandamiento y cometió una gran ofensa.

Sin embargo, ¡contemplen la asombrosa compasión y benevolencia de la Bondad infinita!
Un medio completamente suficiente fue provisto para la redención,
tanto de los primeros transgresores como la de todos sus descendientes.
La Palabra eterna, el Hijo, el Cordero del Dios Altísimo,
demostró la grandeza del amor y de la misericordia divina; en primer lugar,
al estar de acuerdo con el Padre en humillarse a Sí mismo tomando sobre Él,
en su debido tiempo, la condición de hombre,
y en entregarla al sufrimiento y a la muerte,
para hacer una propiciación por toda la especie; y en segundo lugar,
al ofrecer directamente y en todo momento, a cada persona,
una "`manifestación del Espíritu para provecho,`"^
footnote:[1 Corintios 12:7]
con el fin de llevar a cabo hoy su liberación del poder del pecado,
y obrar su eterna salvación del inevitable efecto de permanecer en pecado, a saber,
la segunda muerte.

Que el hombre puede por sí mismo,
producir el poder para vivir en la constante práctica
de crucificar sus inclinaciones y tendencias naturales,
es una presunción descabellada; pero que un Espíritu infinitamente bueno,
que es más poderoso que todos los enemigos del hombre, lo puede influenciar,
inclinar y capacitar, es muy razonable de creer, porque es absolutamente necesario.
No es razonable poner en duda la posibilidad de purificación
y santificación del hombre a través del Espíritu Santo,
ya que el Omnipotente es, ciertamente, más capaz de purificar,
que lo que los poderes creados,
corruptos y caídos de las tinieblas son capaces de contaminar.
Si el Soberano Señor no pretendiera que el hombre sea santificado, no lo demandaría;
tampoco lo demandaría sin proveerle la ayuda necesaria para lograrlo,
porque Dios no demanda ninguna imposibilidad.

Ahora bien,
las Sagradas Escrituras testifican suficientemente que Dios
sí demanda la santificación. Un escritor apostólico dice:
"`Dios no nos ha llamado a inmundicia, sino a santificación.`"^
footnote:[1 Tesalonicenses 4:7]
Y "`así como Cristo amó a la iglesia, y se entregó a Sí mismo por ella,
para santificarla,
habiéndola purificado en el lavamiento del agua por la palabra,`" es decir,
en la eficacia purificadora de la Santa Palabra o Espíritu
que limpia el alma como el agua limpia al cuerpo,
"`a fin de presentársela a Sí mismo, una iglesia gloriosa,
que no tuviese mancha ni arruga ni cosa semejante, sino que fuese santa y sin mancha.`"^
footnote:[Efesios 5:25-27]
En otro lugar escribe: "`Así que, amados, puesto que tenemos tales promesas,
limpiémonos de toda contaminación de carne y de espíritu,
perfeccionando la santidad en el temor de Dios.`"^
footnote:[2 Corintios 7:1]
Y en otro lugar da esta exhortación:
"`Absteneos de toda especie de mal,`"--luego prosigue--"`Y
el mismo Dios de paz os santifique por completo;
y todo vuestro ser, espíritu, alma y cuerpo,
sea guardado irreprensible para la venida de nuestro Señor Jesucristo.`"
Y para alentarlos a buscar y a esperar la santificación, inmediatamente les asegura:
"`Fiel es el que os llama, el cual también lo hará.`"^
footnote:[1 Tesalonicenses 5:22-24]

Vana es la imaginaria pretensión, de que Cristo ya ha pagado todo el precio por nosotros,
por causa de lo cual estamos completamente absueltos ante los ojos de Dios,
y tenemos completa redención en Él, sin ninguna santificación en nosotros mismos.
Porque si esto fuera realmente cierto, significa entonces,
que Cristo pagó el precio de la redención, de modo tal,
que el hombre puede continuar en un estado de contaminación practicando el mal con seguridad,
o puede ser justificado a pesar de quebrantar los mandamientos conocidos de Dios,
sirviendo a Satanás durante toda su vida.
Contrario a esto, la doctrina apostólica es,
"`quien llevó él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros,
estando muertos a los pecados, vivamos a la justicia.`"^
footnote:[1 Pedro 2:24]
Y "`por todos murió, para que los que viven, ya no vivan para sí,
sino para aquel que murió y resucitó por ellos.`"^
footnote:[2 Corintios 5:15]
Y "`los que hemos muerto al pecado, ¿cómo viviremos aún en él?`"^
footnote:[Romanos 6:2]
Y "`no reine, pues, el pecado en vuestro cuerpo mortal,
de modo que lo obedezcáis en sus concupiscencias.`"^
footnote:[Romanos 6:12]
Porque,
"`¿qué fruto teníais de aquellas cosas de las cuales
ahora os avergonzáis? Porque el fin de ellas es muerte.
Mas ahora que habéis sido libertados del pecado y hechos siervos de Dios,
tenéis por vuestro fruto la santificación, y como fin, la vida eterna.`"^
footnote:[Romanos 6:22-23]

Es cierto que el apóstol dice:
"`Porque con una sola ofrenda hizo perfectos para siempre a los santificados.`"^
footnote:[Hebreos 10:14]
Pero esto no implica que Su sacrificio perfeccione a los que nunca llegan a ser santificados.
Esto no puede significar más,
que aquellos que han experimentado la operación efectiva de la gracia divina,
como para llegar a ser santificados,
obtienen por esa única ofrenda la remisión de los pecados cometidos antes de su santificación,
perfeccionando así su redención. Porque una vez cometido el pecado, no se puede deshacer.
Por lo tanto, nuestro Salvador, a través de Su sacrificio, manifestó la misericordia,
amor y bondad de Dios,
siendo Él "`a quien Dios puso como propiciación por medio de la fe en su sangre,
para manifestar su justicia, a causa de haber pasado por alto, en su paciencia,
los pecados pasados.`"^
footnote:[Romanos 3:25]
Aquí se muestra que hay una puerta de reconciliación abierta para todos los hombres,
pero aquellos que por su incredulidad y desobediencia a la gracia divina,
nunca experimentan la obra de santificación,
se privan a sí mismos de este inefable beneficio,
porque es por medio de la santificación,
que alguien puede llegar a disfrutar efectivamente del beneficio del sacrificio de Cristo.

La ofrenda externa de Cristo por "`todos los hombres,`"^
footnote:[Romanos 5:18, 6:10; 1 Timoteo 4:10]
manifestó el amor de Dios para todos,
y demuestra que Él está dispuesto a perdonar los pecados pasados,
de todos aquellos que acepten sinceramente Sus términos
de verdadero arrepentimiento y reforma.
No obstante, la salvación de nuestra alma no es completada sólo por ese único acto,
ni la obra de redención terminada por nosotros sin nosotros.
Aunque Cristo murió por nosotros para que seamos llevados a la gloria, aun así,
no estamos realmente purificados, ni preparados para entrar en el reino,
ni hemos sido introducidos en él por la única ofrenda externa.
El camino para la reconciliación fue ciertamente abierto por la muerte de Cristo,
pero no somos salvos por Su vida,
hasta que tengamos una experiencia viva de la obra
de salvación en nuestros propios corazones.
En efecto, debemos "`recibir con mansedumbre la palabra implantada,
la cual puede salvar nuestras almas,`"^
footnote:[Santiago 1:21]
y aprender a "`trabajar en nuestra salvación con temor y temblor,
porque Dios es el que en nosotros produce así el querer como el hacer,
por su buena voluntad.`"^
footnote:[Filipenses 2:12-13 (traducción literal)]
"`Porque si siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo,
mucho más, estando reconciliados, seremos salvos por su vida.`"^
footnote:[Romanos 5:10]

Entonces, la redención perfecta consiste, primero: en pagar el precio del rescate;
y segundo: en sacar al prisionero de la servidumbre y ponerlo en libertad.
Nuestro Salvador pagó lo primero, por medio de Sus sufrimientos y sacrificio;
y realiza lo último,
por la operación eficaz de Su Espíritu en los corazones
de aquellos que lo reciben y se entregan totalmente a Él.^
footnote:[Esta es la doctrina del apóstol que aparece en su carta a los Efesios,
en la que se les dice primero: "`En Él tenemos redención por su sangre,
el perdón de pecados.`"
(Ef. 1:7) Luego, tan sólo unos pocos versos después,
los encomienda al "`Espíritu Santo de la promesa,
que es las arras de nuestra herencia hasta la redención
de la posesión adquirida`" (Ef. 1:14)--Nota de Editor.]

La humanidad no tiene motivos para quejarse o murmurar
contra las dispensaciones de su benevolente Creador,
porque en Cristo Él le ha dado a cada hijo de Adán una compensación completa por la
pérdida sufrida a través de su infeliz caída. "`Porque de tal manera amó Dios al mundo,
que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda,
más tenga vida eterna.`"^
footnote:[Juan 3:16]

Dios amó tanto a toda Su creación racional,
que les dio a todos la oportunidad de ser salvos por medio de creer.
Si alguno no la acepta, su rechazo es la causa de su condenación,
y no la falta del amor de Dios,
ni la oportunidad de aceptar y recibir el beneficio de ella.
Así lo declaran claramente los cuatro versículos siguientes:

Porque no envió Dios a su Hijo al mundo para condenar al mundo,
sino para que el mundo sea salvo por él. El que en él cree, no es condenado;
pero el que no cree, ya ha sido condenado,
porque no ha creído en el nombre del unigénito Hijo de Dios.
Y esta es la condenación: que la luz vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.
Porque todo aquel que hace lo malo, aborrece la luz y no viene a la luz,
para que sus obras no sean reprendidas.^
footnote:[Juan 3:17-20]

No es razonable concluir que el mundo entero represente menos que toda la especie humana.
El Apóstol Pedro dice:

Porque la profecía no vino en los tiempos pasados por voluntad de hombre:
más los santos hombres de Dios hablaron, siendo movidos por el Espíritu Santo.
Pero hubo también falsos profetas entre el pueblo,
así como habrá entre vosotros falsos maestros,
que introducirán encubiertamente herejías de perdición,
y aun negando al Señor que los compró, trayendo sobre sí mismos acelerada perdición.^
footnote:[2 Pedro 1:21-2:1, RV1602P, énfasis mío]

Esta Escritura indica que Cristo no murió solamente por aquellos que llegan a ser salvos,
sino también por aquellos que atraen destrucción sobre sí mismos; de lo contrario,
no se podría decir que, por Su sacrificio,
Él "`compró`" o pagó el precio de la redención, condicionalmente,
tanto por unos como por otros.
Pero que Dios compró incluso a aquellos que lo niegan,
y que así ocasionan su propia destrucción,
también es afirmado claramente en las siguientes Escrituras:
"`Para que por la gracia de Dios gustase la muerte por todos;`"^
footnote:[Hebreos 2:9]
y "`Él es la propiciación por nuestros pecados; y no solamente por los nuestros,
sino también por los de todo el mundo.`"^
footnote:[1 Juan 2:2]

Siempre es necesario que los medios sean suficientes para obtener el fin perseguido.
Por lo tanto, puesto que todos los hombres,
en todas las naciones y en todas las generaciones,
están en las mismas condiciones con respecto a su Creador,
y naturalmente están en absoluta necesidad de Su ayuda,
para poder experimentar purificación y salvación,
los medios proporcionados para este propósito deben
ser universales y capaces de alcanzar a todos.
Debe haber un verdadero y poderoso don de santidad y bondad,
que sea capaz de cambiar la condición del hombre del mal al bien.
Debe ser omnipotente, para que pueda capacitar al hombre para vencer a sus adversarios:
el mundo, la carne y el diablo.
Solamente un Espíritu superior a todo esto puede efectivamente limpiar el alma,
y llevar a cabo la expulsión y exclusión de esos enemigos sutiles y poderosos que buscan
continuamente mantener al hombre en la esclavitud de corrupción. Por lo tanto,
nada sino el Espíritu Santo, Universal y Todopoderoso de Dios,
puede efectuar esta necesaria transformación en el hombre,
rectificar el desorden que el pecado ha introducido en su naturaleza,
y resucitarlo de un estado de muerte espiritual,
al producir en él un nacimiento nuevo y celestial de la vida divina.
Sólo por la obra de este Espíritu,
el hombre puede ser "`creado en Cristo Jesús para buenas obras,`"^
footnote:[Efesios 2:10]
y restaurado a la imagen de Dios en la justicia y santidad de la verdad.^
footnote:[Efesios 4:24]
