== Capítulo 6. La Regeneración: Una Experiencia Palpable

Ahora bien, hombre, ¿cuál es el gran asunto de tu vida en este mundo,
sino volver al paraíso de Dios y asegurar la herencia eterna que es incorruptible,
incontaminada e inmarcesible?
Para lograr esto, debes ser despojado de todo lo que te hace indigno para entrar.
Lo que haya sido la causa de la exclusión, debe ser removida.
Lo que no pueda tener un lugar o habitación allí, debe ser separado de ti,
o no podrás ser admitido.
'`Lo que detiene, detendrá hasta que sea quitado del medio.`'^
footnote:[2 Tesalonicenses 2:7]
Cualquier cosa que tengas en ti o alrededor de ti a la que estés apegado como consecuencia
de la caída--todo el yo independiente y la mente carnal--debe ser entregada,
o nunca podrás experimentar la restauración. El hacha del evangelio,
el poder del Espíritu de Dios, debe ser puesta a la raíz del árbol corrupto en ti,
para que sea desarraigado y la Vid de la vida plantada en su lugar.
Entonces la Palabra implantada, la cual puede regenerar y salvar el alma,
podrá florecer y producir sus frutos celestiales,
donde la naturaleza pecaminosa por tanto tiempo ha esparcido sus productos venenosos
en el corazón. Solamente de aquí surge toda la verdadera felicidad en la criatura,
y las alabanzas vivas para el eterno Autor de salvación.

La necesidad de regeneración no sólo fue predicada a los pueblos en tiempos primitivos,
sino que fue realmente experimentada por los creyentes.
Tenemos un ejemplo claro y significativo en 1 Corintios 6:9-11, que dice:
"`¿No sabéis que los injustos no heredarán el reino de Dios?
No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados,
ni los que se echan con varones, ni los ladrones, ni los avaros, ni los borrachos,
ni los maldicientes, ni los estafadores, heredarán el reino de Dios.
Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`"
Aquí el apóstol testifica claramente que algunos de los hermanos corintios,
que habían sido de corazones contaminados y de vidas viciosas, fueron regenerados,
lavados y santificados;
y muestra que este gran cambio en ellos fue hecho en el nombre (o poder) del Señor Jesús,
y explica que fue por medio del Espíritu de nuestro Dios.
El apóstol Pedro coincide con Pablo al dar el mismo testimonio:
"`Habiendo purificado vuestras almas por la obediencia a la verdad, mediante el Espíritu,
para el amor fraternal no fingido, amaos unos a otros entrañablemente, de corazón puro;
siendo renacidos, no de simiente corruptible, sino de incorruptible,
por la palabra de Dios que vive y permanece para siempre.`"^
footnote:[1 Pedro 1:22-23]
Muchos otros textos podrían ser añadidos para este mismo propósito.

El apóstol muestra particularmente la naturaleza y la manera
de esta obra en los capítulos 7 y 8 de Romanos,
que muchos, por falta de una experiencia verdadera,
han sido llevados a imaginar que fueron escritos con el
fin de describir su propia condición en ese momento.
Sin embargo, es evidente que estos capítulos comprenden diversas, e incluso contrarias,
condiciones que él y otros habían experimentado en su progreso cristiano,
y en las que era imposible que él estuviera al mismo tiempo, a saber:
en un estado de oscuridad y en un estado de luz;
en un estado de impureza y en un estado de pureza;
en un estado de esclavitud y en un estado de libertad;
en un estado de vida y en un estado de muerte.

En el capítulo 7:5 él dice:
"`Porque mientras estábamos en la carne,`"--bajo el dominio de
la naturaleza carnal--"`las pasiones pecaminosas que eran por la
ley obraban en nuestros miembros llevando fruto para muerte.`"
Aquí se refiere al estado de pecado y muerte en el que estaban esclavizados anteriormente,
pero que ya había pasado, como claramente aparece en el siguiente versículo:
"`Pero ahora estamos libres de la ley,
por haber muerto a aquello en que estábamos sujetos,
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra.`"
En el versículo 7, vuelve a hablar del estado anterior y es más específico:
"`yo no conocí el pecado,`" dice él, "`sino por la ley.`"
Antes de ser sensiblemente condenado en su propia consciencia,
en la que le fue revelado un sentido del requerimiento de Dios,
permaneció en su primer estado natural de ceguera, aunque no lo sabía,
a pesar de su amplia educación y rigor legal.
Aunque "`muerto`" en cuanto a cualquier sentido de la vida divina,
estaba "`vivo`" en el espíritu del mundo.
Y añade: "`Yo sin la ley vivía en un tiempo; pero venido el mandamiento,
el pecado revivió y yo morí.`" Ahora bien,
al ser confrontada por la aparición y administración interna de la ley espiritual,
que produjo verdadera convicción,
la naturaleza pecaminosa fue agitada nuevamente por el poder del mal,
y se levantó como con nueva vida y vigor para evitar que él escapara de ella;
"`porque sin la ley el pecado está muerto.`"
Es decir, la naturaleza de pecado permaneció quieta y sin perturbaciones,
disfrutando su indulgencia sin interrupción,
hasta que fue ministrada la ley de la vida contra ella.
Entonces "`hallé que el mismo mandamiento que era
para vida,`" por la resistencia de esa naturaleza,
"`a mí me resultó para muerte; porque el pecado, tomando ocasión por el mandamiento,
me engañó, y por él me mató,`" o me oscureció y trajo una sensación de muerte sobre mí.

Parece que el pecado lo engañó al principio con la creencia de que la ley producía muerte,
porque él experimentó una sensación de muerte como
resultado de las convicciones de esta ley.
Pero en realidad, la muerte es fruto del pecado, el cual es condenado por la ley.
Entonces dice: "`La ley a la verdad es santa, y el mandamiento santo, justo y bueno.
¿Luego lo que es bueno, vino a ser muerte para mí? En ninguna manera.`"^
footnote:[Romanos 7:12-13]
Mas bien,
encontró que aquello que se oponía tan violentamente
a la ley era lo que producía la muerte,
y ocasionaba que la condenación de la ley viniese sobre él,
la cual descubrió esta muerte dentro de él. Esto fue permitido,
con el fin de que "`el pecado,
pudiera mostrarse pecado,`" y para que por la fuerza convencedora del mandamiento,
"`el pecado llegase a ser sobremanera pecaminoso`" a su vista, y fuera aborrecido por él.

Luego expresa, con un vivo sentido de experiencia,
la esclavizante situación de este estado condenado, pero no cambiado,
y dice en el versículo 14: "`La ley es espiritual; mas yo soy carnal, vendido al pecado.
Porque lo que hago, no lo entiendo.`"
Estoy convencido de que es malo y de buena gana me liberaría de él,
pero a pesar de mis convicciones, estoy bajo su poder y no puedo liberarme.
"`Porque no hago el bien que quiero, sino el mal que no quiero, eso hago.`"
Sin embargo, en paciente sumisión y aferrado fervientemente a Dios,
algo de consolación y entendimiento acompañó este estado despierto:
"`Y si hago lo que no quiero, ya no lo hago yo,
sino el pecado que mora en mí. Porque según el hombre interior,
me deleito en la ley de Dios; pero veo otra ley`"--o poder--"`en mis miembros,
que se rebela contra la ley de mi mente,
y que me lleva cautivo a la ley`"--o poder--"`del pecado que está en mis miembros.`"
Por tanto, impedido de lo que amo y llevado cautivo por lo que odio,
¡qué miserable esclavitud en la que estoy! "`¡Miserable
de mí! ¿quién me librará de este cuerpo de muerte?`"

En conclusión, procede a mostrar, que aunque en otro tiempo esa había sido su condición,
ahora experimentaba libertad perfecta de todas las circunstancias confusas e hirientes,
y de los distintos estados de prueba por los que había pasado anteriormente.
Dice: "`Ahora, pues,
ninguna condenación hay para los que están en Cristo Jesús,`" (aunque
antes claramente la había) "`los que no andan conforme a la carne,
sino conforme al Espíritu.
Porque la ley del Espíritu de vida en Cristo Jesús
me ha librado de la ley del pecado y de la muerte.`"^
footnote:[Romanos 8:1-2]
Esto nuevamente testifica de su libertad y corresponde al versículo citado previamente:
"`Ahora estamos libres de la ley,`" la cual condena por causa del pecado,
"`habiendo muerto a aquella en que estábamos sujetos +++[+++a saber, la naturaleza pecaminosa],
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra.`"
Colosenses 1:12-14 está de acuerdo con estas Escrituras:
"`con gozo dando gracias al Padre que nos hizo aptos
para participar de la herencia de los santos en luz;
el cual nos ha librado de la potestad de las tinieblas,
y trasladado al reino de su amado Hijo.`"

En los pasajes de Romanos 7 y 8 citados arriba,
el experimentado apóstol claramente incluye una representación
de tres condiciones muy diferentes,
mostrando el curso de sus progresos y las diferencias entre ellas.
Primera, el estado natural, ciego y no convencido;
el cual es el estado de oscuridad y de muerte que corresponde
al caos original antes de que la luz resplandeciera.
Segunda, el estado de iluminación y descubrimiento, de convicción y guerra interna,
con la expectativa de alcanzar una conversión completa.
Este estado experimenta una mezcla,
en la que la luz y la oscuridad están en proceso de separación,
como en Génesis 1:3-5. Tercera,
el estado de redención del poder del pecado a través de la purificación,
y traslado al reino espiritual de Cristo.
Este es el estado del cristiano perfecto, y completa la nueva creación,
en la que todo toma su debido lugar y se mueve en el orden correcto.

Ahora apelo al lector: ¿No es absurdo imaginar que estos tres estados diferentes,
y en algunos aspectos contrarios,
puedan coexistir juntos en la misma persona al mismo tiempo?
En esta corta sección de su carta (que contiene un breve,
pero completo bosquejo de la obra del nuevo nacimiento),
el apóstol les muestra a los nuevos en la fe,
los diferentes estados por los que tienen que pasar en su viaje preparatorio, y además,
en palabras de su propia experiencia,
les recuerda a los realmente regenerados lo que ya han experimentado.
Describe los diversos pasos y las principales directrices del Espíritu Santo,
hasta que por Su efectiva operación,
el alma se convierte en una nueva criatura y se le
otorga una generosa entrada al Reino de Dios;
al cual, siendo espiritual e interno, se entra por un camino interno y espiritual.

Por lo tanto, queda claro que un hombre puede adquirir todo el conocimiento,
y recibir todos los títulos que las escuelas y universidades otorguen,
con toda la autoridad que los hombres concedan, y además,
ser estricto en la práctica de todas las formas y aspectos externos de la religión,
y aún así seguir siendo un hombre natural.
De hecho, esas cosas no pueden acercarlo más a la verdadera regeneración,
de lo que estaba al momento de su nacimiento natural,
porque el nuevo nacimiento es obra exclusiva del Espíritu Santo.
Solamente el Espíritu de Santidad puede hacer a un hombre santo,
porque nada puede comunicar o impartir lo que no posee.
Nada puede liberar a los hombres del poder del pecado (y de su paga de muerte),
excepto la ley o poder del Espíritu de vida en Cristo Jesús, ministrado individualmente.
Este Espíritu Santo--que convierte a los pecadores
en santos mediante una verdadera purificación,
y que en cuanto a su estado interno los hace nuevas
criaturas--es la verdadera luz y líder de las almas.
Por medio de Sus manifestaciones directas en el corazón,
el Espíritu se vuelve el guía principal de la vida y la conducta,
y frecuentemente trae a la memoria las verdades de las Escrituras,
revelando su significado de manera provechosa para el entendimiento,
e influenciando la mente y el corazón a vivir de acuerdo con la verdad revelada de Dios.

Es evidente que el apóstol describe, en las escrituras antes mencionadas,
diversos cambios de condición, que a través de la operación y efecto del Espíritu Santo,
ciertamente había conocido y palpablemente sentido.
Sin embargo, hay muchos en el cristianismo, incluso entre los líderes del pueblo,
que desechan todas las experiencias internas e individuales del
Espíritu como si fuesen una fantasía entusiasta y distorsionada.
¡Ay!, estos hacen alarde de conocimiento al hablar de las cosas de Dios,
pero carecen del entendimiento correcto de ellas; porque en verdad,
la pompa del conocimiento natural y el adorno de la elocuencia,
no tienen más concordancia con la Verdad que la vanagloria de la vida.
Estas cosas pertenecen a la sabiduría del mundo, por la que Dios no puede ser conocido;
porque "`el mundo por medio de su sabiduría no conoció a Dios,`"^
footnote:[1 Corintios 1:21]
ni las cosas de Dios.
Todo el conocimiento del hombre natural,
del hombre cuya naturaleza permanece sin cambios (sea llamado pagano, judío o cristiano,
y su conocimiento sea llamado filosofía o teología),
no es más que la sabiduría ineficaz y el conocimiento intelectual de este mundo;
no es la sabiduría de lo alto,
la única por la que es conocido y experimentado Dios y Sus cosas.
La sabiduría de Dios está fuera del alcance de las artes,
los idiomas y las ciencias del hombre,
y sólo se descubre por la manifestación del Espíritu de Cristo en el corazón;
"`en quien están escondidos todos los tesoros de la sabiduría y del conocimiento.`"^
footnote:[Colosenses 2:3]

Sin embargo,
aunque el mundo no conoce a Dios por medio de su admirada y celebrada sabiduría,
hay una sabiduría dada al hombre por la cual Él es conocido.
Las sagradas Escrituras dicen:
"`Porque Dios que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en
la faz`"--o aparición interna--"`de Jesucristo.`"^
footnote:[2 Corintios 4:6]
El apóstol agrega: "`Pero tenemos este tesoro en vasos de barro,
para que la excelencia del poder sea de Dios, y no de nosotros.`"^
footnote:[2 Corintios 4:7]
Este luminoso y excelente poder opera en el que lo recibe con humildad y agradecimiento,
de modo que le abre el entendimiento de lo que lee,
tanto en las Escrituras como en otros escritos provenientes de una experiencia viva,
concediéndole a menudo sentir lo que está leyendo y cosechar sus provechosos efectos.
Pero el que rechaza los medios nunca podrá obtener el fin.
Aquel que rechaza o huye de la luz de la vida cuando se le ofrece,
mediante sus reprensiones y convicciones (no creyendo que sea de Dios,
ni recibiéndola como tal),
detiene su operación e impide que ella se le revele y se
extienda en él. El corazón incrédulo cierra su propio camino,
y por lo tanto, permanece insensible al poder interno del Salvador.

¿Qué hombre sobre la tierra puede decir que no ha tenido convicciones?
¿Y quién puede tener consciencia de ellas y no distinguirlas
de los esfuerzos de su propia razón,
ni distinguir al Reprobador del reprobado?
Es imposible no sentir convicciones.
¿Puede ser experimentada la obra de renovación sin ninguna percepción de su progreso?
¿Describió el apóstol Pablo, con tanta sensibilidad,
los estados dolorosos que había atravesado y los poderes
opuestos que habían hecho guerra dentro de él,
sin haber tenido nunca cierta consciencia de ellos?
¿Deben ser tratadas sus experiencias cristianas como el mero producto
de una apasionada o distorsionada fantasía? ¿Cómo podría una persona
experimentar el arrepentimiento para vida,
la remisión de pecados y los "`tiempos de refrigerio de la presencia del Señor,`"^
footnote:[Hechos 3:19]
sin un sentido interno de ellos?
¿Expresaron los escritores sagrados sus clamores,
anhelos y sed en pos de la presencia del Señor, sin un profundo sentido de su carencia?
¿Fueron expresadas todas sus triunfantes alegrías en la consolación de Su presencia,
bajo una total insensibilidad de ellas?
¿Acaso no eran sentidos los frutos del Espíritu Santo
y Sus consuelos por aquellos que los disfrutaban?
¿Quién puede afirmar estas cosas tan absurdas?
¿Hacia dónde pueden llevar estos guías ciegos a sus ciegos seguidores?
Aquellos que le dan la espalda a la luz, deben caminar en tinieblas.
Es propiedad exclusiva del Espíritu de Cristo, la Luz de los hombres,
darle verdaderas revelaciones al alma,
tanto respecto de sí misma como de todo lo demás que le concierne.
Por lo tanto, Él es correctamente llamado el "`Sol de Justicia,`"^
footnote:[Malaquías 2:14]
porque es para el alma del hombre,
exactamente lo mismo que el sol en el firmamento es para el cuerpo.
Uno es la luz externa, el otro es la luz interna.

Es el hombre incrédulo y no renovado,
ajeno a la operación efectiva de este Espíritu celestial,
el que inconscientemente lo rechaza y menosprecia,
y de este modo contribuye a mantenerse tanto a sí mismo como a otros,
en la ceguera con respecto al Espíritu y prejuiciado en Su contra.
"`El hombre natural,`" dice el apóstol,
"`no percibe las cosas que son del Espíritu de Dios, porque para él son locura,
y no las puede entender, porque se han de discernir espiritualmente.`"^
footnote:[1 Corintios 2:14]
'`¿Qué--dice el hombre poderoso en la razón--debo quitarme los ojos para poder ver?
¿Debo dejar a un lado mi razón y renunciar a ella para obtener un mejor entendimiento?
¡Es imposible y absurdo!`' No,
no es la razón correcta la que está siendo objetada ni desaconsejada,
porque la razón correcta es verdadera,
y siempre concuerda con los movimientos internos del Espíritu de Verdad.
Sin embargo, se ve evidentemente (por los diversos prejuicios, presuposiciones,
debilidades y diferencias irreconciliables entre los hombres) que la razón
humana muchas veces está lejos de concordar con la razón correcta.
Por tanto,
se advierte contra de la colocación de la sabiduría
humana por encima de su debido lugar en la religión,
haciéndola líder en lugar de seguidora de la revelación, maestra en lugar de aprendiz,
y estimándola con algún tipo de autosuficiencia,
independiente de la dirección y ayuda del Espíritu Santo de Dios

Así como la luz del sol es perfectamente dispensada por la soberana sabiduría,
de manera tal que no ciega los ojos de los hombres,
sino más bien los ayuda a usarlos adecuadamente; así también,
la iluminación e influencia divina es administrada
por la misma sabiduría en grados adecuados,
que no excluye la razón del hombre, ni la priva de su utilidad,
sino que la restaura a su uso apropiado en la religión
al disipar las neblinas del prejuicio y de la pasión,
darle un claro sentido de su deber y suministrarle la capacidad de realizarlo.
Los hombres santos de Dios no fueron privados de sus entendimientos cuando
hablaron y escribieron según fueron movidos por el Espíritu Santo.
Al contrario,
encontraron su entendimiento iluminado y altamente mejorado por Él. No fueron usados
por el Espíritu como si fuesen máquinas insensibles o vegetales irracionales,
inconscientes de la virtud que se levantaba en ellos y los capacitaba.
Sus facultades fueron iluminadas y elevadas a un nivel de utilidad mucho más alto,
del que alguna habrían podido experimentar sin la
asistencia del poder de la gracia divina.
Por lo tanto, y con mucha razón,
uno de los escritores inspirados ha dado esta tan necesaria exhortación:
"`Fíate de Jehová de todo tu corazón, y no te apoyes en tu propio entendimiento.`"^
footnote:[Proverbios 3:5]
Y además dice: "`El que confía en su corazón es necio.`"^
footnote:[Proverbios 28:26]
