== Capítulo 7. La Ley del Espíritu de Vida en Cristo Jesús

A pesar de que a muchos se les enseña a imaginar que las diversas ceremonias,
señales y sombras externas de la dispensación de
la ley tienen alguna importancia y eficacia,
es sin embargo cierto, que "`en Cristo Jesús ni la circuncisión vale algo,
ni la incircuncisión, sino la fe que obra por el amor.`"^
footnote:[Gálatas 5:6]
De hecho, ni la práctica,
ni la negación de las formas y de los rituales tienen algún valor ante Dios;
aunque es cierto que la práctica de tales cosas mantiene
a las personas ocupadas sin provecho,
y a menudo las engaña para que depositen una peligrosa confianza en sus propias obras,
o en las de sus líderes.

La religión del verdadero cristiano no consiste en una forma externa, sino en sustancia.
No surge de la actividad de la razón, imaginación u opinión humana,
sino de la genuina experiencia del amor divino en la Luz de la Vida.
Su fundamento es nada menos que la directa administración
del Espíritu Santo de Dios al espíritu del hombre.
Este Espíritu le muestra al hombre los pensamientos de Dios acerca de él,
y revela quién y qué es el Señor, en la medida que le concierne al creyente.
Abre el entendimiento y dirige los pasos del obediente;
porque "`el hombre no es señor de su camino,
ni del hombre que camina es el ordenar sus pasos.`"^
footnote:[Jeremías 10:23]
Es la luz del Cordero la que muestra el camino de salvación,
la única gran Luz designada para gobernar el día (o dispensación espiritual) del cristianismo,
en el cual deben caminar los que son salvos.

Los hombres en su estado natural pueden, mediante la lectura y el estudio,
acumular gran cantidad de conceptos sobre el Ser Supremo;
pero así como la luz manifiesta todas las cosas, y sin embargo,
no puede ser realmente conocida sino por su propia aparición,
así Dios (quien en el sentido más perfecto,
es luz) sólo puede ser verdaderamente conocido por Su propia y directa
manifestación. Lo que los hombres normalmente llaman conocimiento de Dios,
no es más que una serie de ideas acerca de Su esencia, Sus atributos y Su providencia,
pero nuestro Salvador llamó conocimiento de Dios,
a la experiencia real y consciente de Su vida.
"`Y esta es la vida eterna: que te conozcan a ti, el único Dios verdadero,
y a Jesucristo, a quien has enviado.`"^
footnote:[Juan 17:3]
Conocerlo verdaderamente, es participar del sentido vivificador de Su vida,
a través de la influencia comunicada por Su Espíritu eterno.
Así pues,
el verdadero conocimiento de Dios es la participación en el nuevo pacto
--o en la verdadera dispensación del evangelio--porque en él se declara:
"`Todos me conocerán, desde el más pequeño de ellos hasta el más grande.`"^
footnote:[Jeremías 31:34]

Por lo tanto,
el cristiano verdaderamente vivo tiene un sentido
veraz de la vida divina en su propio pecho,
la cual le proporciona instrucción, fuerza y consuelo,
de tal manera que espera con fidelidad en ella,
y no es absolutamente necesario apoyarse en las enseñanzas de otros hombres.
Sin embargo, cuando los maestros llegan en una medida de la misma vida,
él los siente y los acepta como instrumentos de Dios.
Esta vida de Dios en Cristo es el alma misma del cristianismo,
sin la cual las mejores formas y las más elevadas creencias
son sólo miembros indeseables de un cuerpo muerto.

"`El que tiene al Hijo, tiene la vida;
el que no tiene al Hijo de Dios no tiene la vida.`"^
footnote:[1 Juan 5:12]
"`Porque yo vivo:`" dice Él,
"`vosotros también viviréis. En aquel día vosotros conoceréis que yo estoy en mi Padre,
y vosotros en mí, y yo en vosotros.`"^
footnote:[Juan 14:19-20]
Es porque Él vive y comunica de Su vida a Sus seguidores espirituales,
que ellos también viven.
De éstos está compuesta la verdadera iglesia, es decir,
el cuerpo adoptado de Cristo bajo cualquier nombre.
Sólo ellos son Su especial heredad y sacerdocio.

El cuerpo de Cristo es un cuerpo vivo, hecho así por el soplo de Su vida.
Él mismo es la vida en común de todos Sus miembros verdaderos,
y a través de Su influencia viva les comunica un sentido vivo de la verdad,
los inclina hacia Sí mismo, y los inspira con el deseo y el poder de la obediencia.
Y a medida que estos avanzan en fidelidad,
Él los favorece con pruebas crecientes de gracia y amor divinos,
con el dulce sabor de la unción santa,
y con la virtud y gloria de Su presencia celestial que mora en el interior.
Sólo hay "`un cuerpo, y un Espíritu.`"^
footnote:[Efesios 4:4]
Si no hubiera un único y mismo Espíritu en toda la iglesia, no podría ser un cuerpo,
ni un cuerpo vivo.
"`El cuerpo de Cristo no puede vivir sino por el Espíritu de Cristo,`"
dijo Agustín. Él que no participa con la Cabeza del mismo Espíritu,
no es un miembro verdadero del cuerpo.
Su influencia espiritual es la sangre preciosa o manantial de vida,
que hace que todos Sus miembros vivan.
Aquel que da vida, también da un sentido de esa vida,
la cual "`está escondida con Cristo en Dios`"^
footnote:[Colosenses 3:3]--escondida del conocimiento
de aquellos que aún no han sido vivificados por ella;
de aquí se levanta toda su oposición en contra de ella.

Todos nosotros somos por naturaleza extraños a esta vida divina,
y de ninguna manera podemos obtenerla por nosotros mismos.
No es adquirida por el hombre, sino comunicada por Dios; por lo tanto,
está tan fuera del alcance del más instruido como del más iletrado.
Está escondida de los sabios y entendidos ante sus propios ojos,
y es revelada a los que son como niños para la sabiduría del mundo.
Dios no enseña al altivo ni al instruido, sino al pequeño y humilde;
y guía al manso por caminos de verdad y juicio.
Por lo tanto, los ojos de todos deben estar única y humildemente vueltos a Dios,
y no ser puestos en los sabios, en los escribas, ni en los disputadores de este mundo;
porque Dios por medio de la poderosa simplicidad y pureza de Su dispensación del evangelio,
"`ha enloquecido la sabiduría del mundo.`"^
footnote:[1 Corintios 1:20]
Sin embargo, el mundo está tan enamorado de su propia sabiduría,
que ha derribado en gran medida la cruz de Cristo,
junto con la verdadera religión espiritual,
y en su lugar ha erigido y respaldado al ídolo actual.
El mundo se ha arrodillado ante esta imagen, y de hecho, ha sido un medio para cegar,
atrapar y engañar a sus adoradores,
cuya fe está en la sabiduría del hombre y no en el poder de Dios.

A partir de la debida consideración del glorioso propósito de la creación del hombre,
así como también del estado degradado y corrupto de la humanidad desde la caída,
es evidente que la verdadera regeneración ha sido siempre la única cosa necesaria;
la obra esencial que todos tienen que experimentar.
Y así como el nacimiento del Espíritu no puede ser
producido por ninguna otra cosa que no sea el Espíritu,
su crecimiento y realización deben también ser preservados por el Espíritu.
Por lo tanto, la permanencia o morada del Espíritu en el interior,
es de absoluta necesidad para los regenerados,
para que en la medida que sus almas son vivificadas en la vida divina por el Espíritu,
en esa misma medida continúen viviendo,
moviéndose y teniendo su ser como cristianos en ella,
y ser sostenidos en unión espiritual y bendita comunión con su Hacedor.

La esencia de la verdadera religión siempre ha sido la misma, y consiste primeramente,
en que la vida de Dios sea resucitada, y el amor de Dios derramado en el corazón,
operando internamente hasta lograr una verdadera renovación,
y llevar todo fruto virtuoso y benevolente.
Cualesquiera que sean las cosas externas o ceremonias que en ciertos
momentos hayan sido añadidas por la dirección u ordenanza divina,
no tenían la intención de alterar o desviar al hombre de
su debida y constante atención a la religión vital y espiritual.
Fue sólo porque el hombre se degeneró en extremo en cuanto a lo interno y lo espiritual,
y quedó ciego a ello,
que el misericordioso Creador se plació (por medios adecuados a su condición
alejada y carnal) en señalarles y guiarlos a dicha religión,
a través de signos y símbolos.
Por lo tanto,
la ley Mosaica no tenía como objetivo ser la totalidad de la religión de los Israelitas,
ni reemplazar la religión interna de Abraham,
sino sólo ser como un "`ayo para llevarlos a Cristo`"^
footnote:[Gálatas 3:24]
en el Espíritu, en quien todo está incluido y cumplido,
y cuya presencia estaba en ese entonces con los fieles en Israel que tenían
comunión espiritual con Él. Porque de acuerdo con las Escrituras:
"`Todos comieron el mismo alimento espiritual,
y todos bebieron la misma bebida espiritual;
porque bebían de la roca espiritual que los seguía, y la roca era Cristo.`"^
footnote:[Corintios 10:3-4]

Es una vana imaginación pensar que la religión alguna vez
haya consistido enteramente en formas y modos externos,
o que el Señor haya prescindido en algún momento de la sustancia interna,
en aras de la sombra externa.
No, Él es Dios y no cambia.
Su ley es Su propio Espíritu de eterna perfección. Las diferentes modificaciones
que Dios ha usado entre los hombres en materia de religión,
han sido ocasionadas por los diferentes cambios en las condiciones de la humanidad.
El Dios Omnisciente, por algún tiempo ha dirigido a algunos, misericordiosamente,
a sombras y ceremonias externas para el buen fin mencionado anteriormente;
y los hombres han inventado y añadido muchas más,
en concordancia con sus propios malentendidos carnales de las cosas espirituales,
o para hacer avanzar sus propios propósitos siniestros.
Pero las formas externas sólo son asuntos temporales;
no son la esencia del cristianismo verdadero.
El gran Autor del cristianismo describe esta esencia
como "`una fuente de agua que salta para vida eterna.`"^
footnote:[Juan 4:14]
Surge de un Espíritu viviente, permanente y creciente en el hombre,
el cual es de una naturaleza pura y celestial.
A medida que Él es recibido con amor,
se extiende en el alma y expulsa las obras y el poder de las tinieblas,
y produce Sus propios y genuinos frutos de humildad, negación al yo, paciencia, justicia,
santidad, mansedumbre, gentileza, templanza, bondad, afecto fraternal, amor,
rendición a Dios y confianza solamente en Él. Esto
se origina en el cielo y conduce de regreso al cielo,
sacando al alma de todas las formalidades y de los falsos reposos,
y llevándola al Supremo bien mismo.
Destruye toda voluntad del yo y lleva a la perfecta rendición a la voluntad divina.
En esta humilde y contrita condición (y no en otra)
podemos sincera y verdaderamente decir:
"`¡Venga tu reino.
Hágase tu voluntad!`"
Porque mientras nuestras voluntades están separadas de la voluntad de Dios,
no podemos dirigirnos en estos términos a Él con propiedad, o en Espíritu y verdad.

Ahora, el orgullo del hombre es naturalmente hostil a esta condición abatida y contrita.
No sabe cómo someterse a ser nada, o a considerarse nada, aunque de hecho,
es peor que nada.
Gustosamente se establecería y exaltaría a sí mismo como poseedor de importancia,
estima y mérito propio; sin embargo, todas sus pretensiones son falsas y vanas.
En efecto, el hombre no es más que lo que Dios ha hecho de él,
y no posee más de lo que Dios le da.
Es completamente de Dios y no de sí mismo,
y por eso está obligado a caminar en obediencia a Él en cada momento de su vida,
la cual se le da con ese fin.
Y dado que el hombre no cumplió con su deber,
y pecó contra su Creador por medio de la desobediencia, no está en su poder,
mediante ninguna acción que pueda realizar,
merecer el cielo o comprar remisión para sí mismo.
Él tampoco puede deshacer lo que ha hecho,
ni entregarle a su Creador un equivalente por las
transgresiones que ha cometido en Su contra.
Pero tal es la misericordiosa bondad y la gracia
gratuita de Dios hacia Sus indefensas criaturas,
que Él ofrece tanto el perdón como la felicidad bajo los términos más razonables.
Para los "`dispuestos y obedientes,`"^
footnote:[Isaías 1:19]
para el que es "`fiel hasta la muerte,`"^
footnote:[Apocalipsis 2:10]
para el "`que venciere`"^
footnote:[Apocalipsis 2:7, 11, 17, 26; 3:5, 12, 21; 21:7]
(por medio del poder del Espíritu), para estos son las promesas de la vida eterna.
Sobre la base de estas ofertas gratuitas y voluntarias de la bondad divina,
y el cumplimiento de las condiciones por parte del hombre, descansa su derecho de entrar.
"`Bienaventurados los que hacen sus mandamientos,
para que tengan derecho al árbol de la vida,
y que entren por las puertas en la ciudad.`"^
footnote:[Apocalipsis 22:14 RV1602P]

En las Escrituras,
las leyes y los requisitos de Dios para el hombre a menudo son llamados pactos.
El hombre en pacto con Dios le debe su propio ser,
y todo el bien espiritual y temporal que recibe, se lo debe a su Hacedor,
con quien está en deuda por todo.
Por lo tanto, Dios tiene el derecho incuestionable de demandar todo el afecto,
la gratitud y la obediencia del hombre, y más especialmente,
cuando todos Sus tratos contribuyen a su bienestar eterno.
Hay también un pacto interno y espiritual (una conexión o unión divina),
que el corazón del hombre llega a sentir a medida que crece en fidelidad a su Creador.
Este es el Espíritu de Vida en Cristo Jesús,
el cual libera al alma del cautiverio del pecado y de la muerte,
y la une a su Salvador en el poderoso pacto de amor divino.
Por este pacto, a través de la fe, el alma es injertada en Cristo,
y mediante la obediencia permanece en Él como una rama en la vid;
porque "`el que se une al Señor, un espíritu es.`"^
footnote:[1 Corintios 6:17]
Las almas regeneradas tienen una cierta conciencia y entendimiento de esta vital unión,
en proporción a su progreso.
"`En esto conocemos que permanecemos en él, y él en nosotros,
en que nos ha dado de su Espíritu.`"^
footnote:[1 Juan 4:13]
"`Y en esto sabemos que él permanece en nosotros, por el Espíritu que nos ha dado.`"^
footnote:[1 Juan 3:24]
Por lo tanto, es evidente que el don del Espíritu comunica este entendimiento al alma.
