== Capítulo 9. La Administración Pura del Espíritu Santo

Cuando llegó el momento en el que el Señor consideró conveniente llamar
al mundo degenerado a salir de las corrupciones en las que se había sumergido,
levantó a los hijos de Israel como un ejemplo para el resto de la humanidad,
por medio de una manifestación pública de Su propio dominio justo.
Los sacó de su cautiverio egipcio con mano poderosa
y a través de muchos golpes admirables de Su poder.
Luego instituyó la ley Mosaica, la cual,
siendo la introducción de una nueva forma de Teocracia desconocida para el mundo,
fue necesariamente acompañada por señales extraordinarias de autoridad Divina,
que la autenticaron y establecieron suficientemente como venida del Creador.
Por lo tanto, en esa gran ocasión,
apareció a los israelitas de manera correspondiente a Su Omnipotente Soberanía,
introduciendo Su pacto con las más temibles y asombrosas señales de terror;
con truenos y relámpagos, con oscuridad, tinieblas y tempestad,
con la montaña ardiendo en fuego,
con el alarmante sonido de la trompeta que iba aumentando en extremo,
y con la voz que hablaba tan terriblemente, que no sólo el pueblo,
sino toda la montaña temblaron extremadamente.
Esto fue un acto obvio y sumamente solemne del Supremo Legislador del universo,
y ninguna autoridad menor que la Suya podría abolir o alterar el pacto.

Por lo tanto,
cuando llegó el período en el que Él consideró apropiado dejar
a un lado y sustituir Su ley de ordenanzas externas y carnales,
al presentar a plena vista y como única obligación
la sustancia que ella señalaba (es decir,
Su pacto espiritual y más excelente),
fue necesario que esto se realizara mediante claras
manifestaciones de la misma autoridad soberana.

En consecuencia,
la misericordiosa dispensación del evangelio fue introducida
con evidencias de autoridad divina igualmente extraordinarias.
Además de las numerosas predicciones de los profetas acerca del Mesías,
la llegada de Su precursor, el Bautista,
la concepción milagrosa de nuestro Salvador por la bendita virgen, etc.,
hubo muchas obras maravillosas realizadas por Él y grandes
señales que acompañaron el amanecer del nuevo pacto.
El velo del templo se rasgó de arriba abajo cuando Él entregó el Espíritu,
indicando la separación, la conclusión y el final de todas las señales y ceremonias,
y la revelación de la sustancia en Espíritu y verdad.
Consideren también la inexplicable oscuridad al momento de Su muerte,
Su sorprendente resurrección,
los cuerpos de los santos enterrados que resucitaron y entraron a la ciudad,
Su visible ascensión acompañada por la ministración gloriosa de ángeles, etc.
Y después de todo esto,
en el tiempo de la fiesta judía de Pentecostés (celebrada anualmente
en conmemoración de la entrega de la ley en el Monte Sinaí),
el Espíritu Santo fue derramado sobre apóstoles y discípulos, hombres y mujeres,
reunidos según el mandato del Señor, como demostración del inicio del pacto espiritual,
sin ninguna mezcla de figuras legales o sombras.
Esta demostración fue de dos maneras: Primero,
por la aparición de lenguas como de fuego que se asentaron sobre cada uno de ellos;
y segundo, al llenar sus corazones del Espíritu Santo a tal grado,
que comenzaron a hablar en otras lenguas, o en otros idiomas además de los suyos,
según el Espíritu les daba que hablasen.
Dotados de sabiduría y poder celestiales, y ardiendo en amor y fervor divinos,
estuvieron entonces calificados para poner en práctica la comisión
previamente dada (de manera verbal) por el gran Señor y Legislador.
A muchos de ellos se les añadieron también los poderes
milagrosos para sanar toda clase de enfermedades.
Hicieron que los mudos hablaran, los sordos oyeran,
los cojos caminaran y los ciegos vieran; liberaron endemoniados,
y resucitaron muertos restaurándolos a la vida.

Ahora bien, estos poderes extraordinarios no fueron conferidos a todos,
ni se limitaron sólo a los apóstoles,
sino que una medida del mismo Espíritu fue comunicada a cada uno de ellos,
tanto a mujeres como a hombres (de acuerdo con la
aplicación que Pedro hizo de la profecía de Joel).
Todos fueron llenos del Espíritu Santo,
pero dotados y capacitados por Él de formas diferentes, para servicios diferentes,
según la voluntad y sabiduría del gran Dispensador.
"`Porque a éste es dada por el Espíritu palabra de sabiduría; a otro,
palabra de ciencia según el mismo Espíritu; a otro, fe por el mismo Espíritu; y a otro,
dones de sanidades por el mismo Espíritu.
A otro, el hacer milagros; a otro, profecía; a otro, discernimiento de espíritus; a otro,
diversos géneros de lenguas; y a otro, interpretación de lenguas.
Pero todas estas cosas las hace uno y el mismo Espíritu,
repartiendo a cada uno en particular como él quiere.`"^
footnote:[1 Corintios 12:8-11]
De esto se desprende que no toda inspiración divina
va acompañada de lo que comúnmente se llaman milagros,
sino que éstos son una de las diversas operaciones del Espíritu que a veces son añadidas.
Por lo tanto,
pueden cesar totalmente cuando terminan las ocasiones por las que fueron agregadas,
o continuar siendo utilizadas conforme le parezca necesario a la sabiduría Divina.

Así pues,
cuando el evangelio fue suficientemente difundido y establecido
en los lugares que el Señor entonces pretendía,
de modo que el fin para el cual se concedieron esos
poderes extraordinarios se había cumplido,
fueron en gran medida retirados de la iglesia, la cual quedó, en general,
sobre su fundamento apropiado y permanente; es decir,
la directa inspiración del Espíritu Santo.
Por consiguiente,
no se puede abogar por la necesidad de una constante presencia de los poderes milagrosos,
ni de un espíritu de profecía que implique la predicción de acontecimientos futuros,
sino únicamente por aquellas influencias sobrenaturales
del Espíritu que son necesarias para iluminar,
vivificar, regenerar, santificar y producir los frutos del Espíritu en el hombre.
Éstas son absolutamente necesarias en cada época, ya que son de carácter moral,
y influyen directamente en la transformación y salvación de cada hombre.

Creo que se han evidenciado algunas manifestaciones divinas de naturaleza milagrosa--tanto
bajo la administración del antiguo pacto como bajo la del nuevo,
así como también antes de ellas--ya sea para convencer a personas dudosas,
o para dar peso y autoridad adicionales al ministerio de algunos siervos ungidos de Dios,
o para alentarlos o confirmarlos en su servicio.
No tengo duda de que esto ha sucedido en ocasiones desde el primer siglo,
y puede seguir sucediendo hasta el final de los tiempos;
pues ni el poder ni la bondad del Todopoderoso han cambiado.
Sin embargo,
también soy de la opinión de que las manifestaciones milagrosas han sido
menos públicas y más moderadas después del primer siglo que antes,
lo cual puede deberse en parte a la apostasía espiritual de las iglesias profesantes.
También creo, según las declaraciones proféticas de los apóstoles,
que bajo el estado caído y oscuro tanto de los maestros como de los oyentes,
han sido permitidos y aún pueden permitirse muchas señales extrañas y prodigios mentirosos,
impuestos sobre personas crédulas y desobedientes por engañadores,
para apoyar y propagar sus intereses corruptos.

Dado que nunca más habrá un cambio en las dispensaciones,
ni se predicará ninguna otra doctrina sino la de
nuestro Salvador y Sus apóstoles (la cual,
en su comienzo recibió una confirmación milagrosa
suficiente para su establecimiento duradero),
las personas ahora no deben esperar ni pedir milagros
de quienes predican la doctrina cristiana.
En lugar de eso,
todos deben volverse y prestarle atención a ese Espíritu divino señalado por las Escrituras,
el cual se manifiesta en el corazón de cada individuo:
la ministración de Cristo en Espíritu.
Esta le dará al receptor sincero y humilde una demostración más clara
y particular que la que podrían dar todos los signos y señales externos;
pues los poderes de los que proceden los milagros externos pueden ser cuestionados,
pero la evidencia interna de la luz de Cristo, la vida de los hombres,
cuando se espera y se aferra correctamente,
no deja duda en la mente acerca de su naturaleza y autoridad divinas.

Pero, regresando al ministerio del evangelio,
el apóstol muestra (2 Corintios 3) que éste supera con creces al de la ley,
y que su excelencia consiste en su espiritualidad.
Habiendo hablado de la ley en el versículo 8, añade:
"`¿Cómo no será más bien con gloria el ministerio del Espíritu?
Porque si el ministerio de condenación fue con gloria,
mucho más abundará en gloria el ministerio de justificación. Porque aun lo que fue glorioso,
no es glorioso en este respecto, en comparación con la gloria más eminente.
Porque si lo que perece tuvo gloria, mucho más glorioso será lo que permanece.`"
¿Por qué el evangelio es así de preeminente sobre la ley,
siendo la ley una institución divina?
Principalmente, porque el evangelio no es un código externo como lo era la ley,
sino _una ley interna de vida,_ "`escrita no con tinta, sino con el Espíritu del Dios vivo;
no en tablas de piedra, sino en tablas de carne del corazón;`"^
footnote:[2 Corintios 3:3]
y porque hace "`ministros competentes de un nuevo pacto, no de la letra,
sino del espíritu; porque la letra mata, más el espíritu vivifica.`"^
footnote:[2 Corintios 3:6]

Ningún hombre puede ser un verdadero cristiano sin el Espíritu de Cristo;
porque "`si alguno no tiene el Espíritu de Cristo, no es de él.`"^
footnote:[Romanos 8:9]
Todo cristiano debe experimentar la presencia del Espíritu en su interior.
"`¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros,
el cual tenéis de Dios, y que no sois vuestros?`"^
footnote:[1 Corintios 6:16]
Es un requisito que todo cristiano conozca al Espíritu como su guía y líder;
porque sólo "`los que son guiados por el Espíritu de Dios, éstos son hijos de Dios.`"^
footnote:[Romanos 8:14]
Ningún hombre puede ser una oveja de Cristo sin un
sentido distintivo del Espíritu de Cristo.
"`Yo soy el buen pastor; y conozco mis ovejas,
y las mías me conocen... Mis ovejas oyen mi voz, y yo las conozco,
y me siguen... Las ovejas le siguen, porque conocen su voz.
Mas al extraño no seguirán.`"^
footnote:[Juan 10:14, 27, 4-5]
La voz de Cristo es la manifestación de Su Espíritu al alma.

Ningún hombre puede entrar en el Reino de Dios sin nacer de nuevo del Espíritu.
Esto es tan necesario para nosotros ahora como lo fue para los primeros creyentes.
Ciertamente,
nosotros no tenemos más capacidad para regenerarnos y prepararnos para el reino
que la que ellos tenían. No hay facultades naturales o adquiridas en nuestro
estado no regenerado que sean suficientes para alcanzar un propósito tan grande,
ni para permitirnos decir verdaderamente (con el pueblo de Dios en tiempos antiguos):
"`Señor, tú nos darás paz; porque también obraste en nosotros todas nuestras obras.`"^
footnote:[Isaías 26:12 RV1602P]

Ningún hombre puede ser ministro del Espíritu sin el Espíritu.
La instrucción apostólica es: "`Cada uno según el don que ha recibido,
minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios.
Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra,
ministre conforme al poder que Dios da,
para que en todo sea Dios glorificado por Jesucristo.`"^
footnote:[1 Pedro 4:10-11]
En la era apostólica,
todo verdadero creyente y fiel seguidor de Cristo recibió una medida
del mismo Espíritu Santo que los profetas y apóstoles recibieron,
aunque en menor grado.
El apóstol Pablo dice:
"`Porque por un solo Espíritu fuimos todos bautizados en un cuerpo,
sean judíos o griegos, sean esclavos o libres;
y a todos se nos dio a beber de un mismo Espíritu.`"^
footnote:[1 Corintios 12:13]
Compartir este único Espíritu los hizo un solo cuerpo, y los unió a la única Cabeza viva.
Hay "`un cuerpo, y un Espíritu,
como fuisteis también llamados en una misma esperanza de vuestra vocación; un Señor,
una fe, un bautismo, un Dios y Padre de todos, el cual es sobre todos, y por todos,
y en todos.`"^
footnote:[Efesios 4:4-6]
Por lo tanto, según las diversas medidas que se les repartieron,
todos eran partícipes del mismo Espíritu Santo; y así como era entonces, así es ahora,
y siempre debe ser en la iglesia verdadera y espiritual de Jesucristo.

El sol del evangelio se levantó con gran esplendor,
aunque a ninguno se le mostró todo su brillo de una sola vez.
La revelación de la verdad en las mentes de los primeros
cristianos (tanto los apóstoles como los demás) fue gradual.
A medida que avanzaban en la nueva naturaleza,
llegaban a ver más y más. Durante un tiempo, ocasionalmente se circuncidaban,
hacían votos, se ungían con aceite, se bautizaban con el bautismo de Juan, etc.,
todo lo cual era de naturaleza externa y legal.
De hecho, al principio,
ni siquiera se habían dado cuenta de que el Espíritu Santo
iba a ser dado a los gentiles tanto como a los judíos,
a pesar de que Joel había profetizado claramente que sería derramado sobre toda carne.
Pero después, a medida que seguían a Cristo en la regeneración,
fueron llevados más allá de la mezcla inicial de cosas.
Con el tiempo,
llegaron a ver claramente que el Espíritu Santo caía
sobre los gentiles tanto como sobre los judíos,
y declararon que "`ni la circuncisión vale nada, ni la incircuncisión,
sino una nueva creación.`"^
footnote:[Gálatas 6:15]
Descubrieron que "`la unción del Santo`"^
footnote:[1 Juan 2:20]
es absolutamente suficiente para dar instrucción y juicio verdadero;
y entendieron que "`el bautismo que salva`" no es aquel que alcanza sólo la carne,
sino el del Espíritu,
que bautiza el corazón y produce el "`testimonio de una buena conciencia delante de Dios,
por la resurrección de Jesucristo,`"^
footnote:[1 Pedro 3:21]
es decir, por Su levantamiento espiritual en el alma.

Es común escuchar que a la era apostólica se le llama la infancia del cristianismo;
y así como lo fue en cuanto al tiempo,
también lo fue en relación con la continuación temporal
de algunas ceremonias y sombras externas.
Al principio, los creyentes no podían ver a través del velo de tales cosas.
Y luego,
se mantuvieron por un tiempo en consideración a los
que estaban tan aferrados a las prácticas simbólicas,
que no podían ser llevados rápidamente al punto de no usarlas.
Sin embargo, a medida que crecían en la gracia y en el conocimiento de Jesucristo,
el Espíritu estaba obrando en ellos para "`quitar lo primero, y establecer lo último,`"^
footnote:[Hebreos 10:9]
"`removiendo las cosas movibles, como cosas hechas,
para que quedaran las inconmovibles.`"^
footnote:[Hebreos 12:27]

En gran contraste con esto,
muchos de los actuales líderes y gobernantes de las
iglesias que profesan el nombre cristiano,
parecen pensar que,
aunque la asistencia del Espíritu Santo fue necesaria para la introducción
y sostén del cristianismo en los tiempos primitivos,
no hay necesidad de ella ahora.
Se cree que la iglesia ha madurado tanto por la sabiduría
y aprendizaje del hombre (algo que no tuvo parte en su origen),
que es perfectamente capaz de continuar sola.
De esta forma, la iglesia ha llegado a ser, en gran medida, otra cosa,
y se asienta sobre un fundamento distinto al anterior.
Aunque todavía llama a Cristo su cabeza y se considera a sí misma Su cuerpo,
ella no recibe directa dirección de Él, ni siente la circulación de Su sangre,
que es la vida y la virtud de toda religión verdadera.
Por lo tanto,
la iglesia de hoy merece la reprensión del apóstol implícita en esta pregunta:
"`¿Tan necios sois?
¿Habiendo comenzado por el Espíritu, ahora os perfeccionáis por la carne?`"^
footnote:[Gálatas 3:3 RV2009]
En realidad, es demasiado evidente que la mayoría de las iglesias cristianas profesantes,
en lugar de haber avanzado hacia la madurez en el cristianismo,
están en una gran decadencia y apostasía de ese estado; de lo contrario,
no podrían ser tan insensibles,
ni se atreverían a mostrarse tan opuestas a la vida de la religión
como para rechazar o menospreciar la parte más vital de ella,
tratándola como si estuviera extinta, fuera innecesaria, o, al menos, imperceptible.
Ciertamente,
una iglesia en esta condición bien merece la descripción
que el Espíritu le da a la iglesia degenerada de Sardis:
"`Yo conozco tus obras, que tienes nombre de que vives, y estás muerto.`"^
footnote:[Apocalipsis 3:1]
Sin embargo, aunque este parece ser en gran medida el caso, espero y verdaderamente creo,
que hay muchos miembros vivos y sensibles del cuerpo de Cristo dentro de esas iglesias.

La vitalidad y gloria del cristianismo radica en
la administración pura del Espíritu Santo,
sin ningún velo de sombras legales o rituales.
El aprendizaje académico es sólo un logro humano,
y aunque puede ser muy útil como siervo, no constituye una parte real del cristianismo.
Ni los logros universitarios, ni las formalidades de la autoridad humana,
pueden producir esa humildad que prepara el corazón para las enseñanzas de Dios.
Los seres humanos débiles, poseedores de habilidades e idiomas,
se llenan de una presunción de superioridad que los
aleja de la negación de sí mismos y de la cruz diaria,
y los conduce al orgullo y autosuficiencia.

Estos, en lugar de esperar y depender de la sabiduría y del poder de Dios,
desarrollan una confianza en la sabiduría de este mundo y una satisfacción
en la repetición de las formas y ordenanzas externas.
Por otro lado, aquellos que "`adoran a Dios en Espíritu,
gloriándose en Cristo Jesús,`" no ponen su "`confianza en la carne.`"^
footnote:[Filipenses 3:3]
¿Y por qué? Porque "`el Espíritu es el que da vida; la carne para nada aprovecha.`"^
footnote:[Juan 6:63]
Por lo tanto,
cualquiera que niegue que el Espíritu Santo y sus operaciones
internas deben experimentarse palpablemente hoy,
sólo demuestra su propia falta de experiencia de ello.
El verdadero pueblo de Dios, en todas las épocas,
ha declarado su propia e indudable experiencia de la iluminación y poder divinos;
y los apóstoles testifican unánimemente que tenían un sentido
claro y distintivo del Espíritu Santo en Sus diversas operaciones.
Así como fue entonces, lo es ahora,
y debe continuar así mientras los hombres estén sobre la tierra.

La misma obra interna de Dios es absolutamente necesaria en cada hombre,
y una conciencia correspondiente de ella (según su medida) es clara
y cierta para todos los que experimentan la regeneración. Porque,
tan cierto como que el hombre no puede obtener verdadera
felicidad fuera del reino de Dios,
ni entrar en él sin haber nacido del Espíritu,
tampoco puede experimentar la obra del nuevo nacimiento sin percibirlo.
Aunque los hombres puedan alegar que Dios obra de maneras secretas y desconocidas,
la verdad es que una operación indiscernible del Espíritu Santo no es regeneración,
sino un mero engaño. Ya sea que el Espíritu de Dios
opere a través de palabras e instrumentos o sin ellos,
siempre viene en poder, un poder que da un sentido innegable,
perfectamente distinto y superior a todos los demás poderes,
y que manifiesta un resplandor que, en ocasiones,
supera por mucho todas las luces naturales,
tal como el sol radiante excede el brillo tenue de una luciérnaga.
Este Espíritu Santo de luz y poder de vida es el
gran principio fundamental de los despreciados Cuáqueros,
el único y verdadero principio salvador para toda la humanidad.
Cristo en el Espíritu es la "`luz de los Gentiles,
y la salvación de Dios hasta lo postrero de la tierra,`"^
footnote:[Isaías 49:6]
quien siempre ha sido y siempre está listo a ser,
el "`autor de eterna salvación para todos los que le obedecen.`"^
footnote:[Hebreos 5:9]
