== Capítulo 10. La Operación de la Gracia Divina

Habiendo tratado de mostrar claramente algo de la caída del hombre,
y de la necesidad y los medios para su restauración a Dios,
ahora procederé a observar particularmente algunos
de los errores y malentendidos más comunes,
empezando por las doctrinas concernientes a la predestinación
individual y a la operación de la gracia divina.

Aunque el hombre no puede dar un solo paso hacia su salvación sin la ayuda de la gracia
de Dios como la primera y continua causa habilitadora (tanto del querer como del hacer),
esto no significa necesariamente (como algunos reformadores han insistido) que Dios sea,
por tanto, el autor de la salvación de unos, y el autor de la destrucción de otros.
La verdad de este asunto, como está establecida claramente en las Escrituras,
es como sigue: 1. Que el hombre no tiene la capacidad de salvarse a sí mismo,
ni está naturalmente en un estado de igual libertad
para hacer el bien o el mal según su antojo,
ni está en posesión de aquella fe que es necesaria para su salvación. 2. Que
el Redentor proporciona una manifestación de Su Espíritu al alma de cada hombre,
mediante la cual, en ciertos momentos,
reprueba las inclinaciones corruptas de los hombres,
los detiene en seco y pone en su poder la capacidad
de reflexionar sobre su condición presente,
y de entregarse a la operación de este Espíritu interno.
Si no se resiste, sino que permanece en sumisión,
entonces el Espíritu se apodera de él aún más, dándole la capacidad de creer,
de unirse y de permanecer en la operación del Espíritu que está sobre él. En esta situación,
siente fuerza y consuelo brotando de la Semilla (o medida
de gracia) que incrementan su fe y confianza en ella,
y gradualmente lo habilitan y lo llevan a volverse activo, es decir,
a unirse de corazón en consentimiento con Sus operaciones, y a avanzar de fe a fe,
y de un grado de gracia a otro.
Esto progresa hasta que el alma llega a sentir y a experimentar
el verdadero nuevo nacimiento del Espíritu,
participando (en medida) de la luz, vida y naturaleza gloriosas del reino celestial.

Dios ha hecho al hombre una criatura racional, y por lo tanto,
requiere su obediencia voluntaria: "`Si queréis y obedecéis,
comeréis el bien de la tierra.`"^
footnote:[Isaías 1:19 RV1977]
¿Es posible pensar que Él pone el bien y el mal,
la vida y la muerte delante de los hombres (como testifican los registros sagrados),
y que una y otra vez los llama a escoger la vida y el bien,
y sin embargo no los capacita para hacerlo?
De hecho, cada precepto divino, cada exhortación, cada mandamiento,
cada advertencia implica una libertad concedida para aceptar o rechazar;
para obedecer o desobedecer.
Sin embargo, si Dios repetidamente visita a todos con las persuasiones de Su gracia,
y continúa una y otra vez tratando de convencerlos,
inclinarlos y atraerlos (como declaran las Escrituras) para
poder prevalecer sobre ellos y llevarlos al arrepentimiento,
¿acaso no hace todo lo posible sin violar la libertad racional que les proporciona?
Que el hombre sólo rinda obediencia a Sus convicciones,
y entonces vea si puede acusar a su Creador de parcialidad o de duro trato.
Es el siervo inútil y perezoso el que hace tales acusaciones en contra de su Amo.

La educación y la tradición ciertamente predisponen a las personas,
y crean un prejuicio en la mente contra toda doctrina
diferente de la que se les ha enseñado.
Sin embargo, la luz divina, en ocasiones, se abalanza repentinamente sobre el alma,
tan rápido como un relámpago,
y penetra a través de toda oscuridad y de toda falsa apariencia,
perturbando al alma en sus descansos impuros y en sus gratificaciones carnales,
mostrándole su esclavitud bajo todo ello,
e inspirando en ella un deseo y suspiro secretos por ser redimida.
Esto, al ser una revelación de la luz divina en la mente,
es llamado el día de la visitación de Dios,^
footnote:[Lucas 19:44; 1 Pedro 2:12]
el tiempo de gracia para el hombre,
en el que la vida y la muerte se distinguen en él. Durante este tiempo,
no sólo se le concede al hombre la libertad de elegir
la vida (lo que antes no podía hacer),
sino que también se le da una correspondiente medida de
capacidad para amar y adherirse a la gracia que lo visita,
y de ese modo llegar al arrepentimiento y a la salvación.
Porque esta gracia es el Espíritu del Salvador,
y por tanto, trae consigo el poder de salvación, como dice el apóstol:
"`Porque la gracia de Dios se ha manifestado para salvación a todos los hombres,
enseñándonos que, renunciando a la impiedad y a los deseos mundanos,
vivamos en este siglo sobria, justa y piadosamente,
aguardando la esperanza bienaventurada y la manifestación
gloriosa de nuestro gran Dios y Salvador Jesucristo.`"^
footnote:[Tito 2:11-13]

Estas visitaciones misericordiosas de la gracia divina a menudo se repiten,
tanto de noche como de día. "`Dios,`" dice el inspirado Eliú,
"`en una o en dos maneras habla; pero el hombre no entiende.
Por sueño, en visión nocturna, cuando el sueño cae sobre los hombres,
cuando se adormecen sobre el lecho, entonces revela al oído de los hombres,
y les señala su consejo, para quitar al hombre de su obra,
y apartar del varón la soberbia.`"^
footnote:[Job 33:14-17]
Luego procede a mostrar cómo opera el Señor sobre el alma
sumisa en la obra de arrepentimiento y quebrantamiento,
y cuál será el resultado.
Entonces, resume con estas palabras: "`Él mira sobre los hombres; y al que dijere: Pequé,
y pervertí lo recto, y no me ha aprovechado,
Dios redimirá su alma para que no pase al sepulcro, y su vida se verá en luz.
He aquí, todas estas cosas hace Dios dos y tres veces con el hombre,
para apartar su alma del sepulcro, y para iluminarlo con la luz de los vivientes.`"^
footnote:[Job 33:27-30]

De hecho,
el gran Padre de misericordias se complace en continuar
sus visitaciones de gracia desde lo alto a los hombres rebeldes,
hasta que se han vuelto tan determinados en su iniquidad,
y tan habitualmente unidos a su servidumbre,
que al igual que los siervos en Éxodo 21:5-6, no quieren ser liberados de ella.
Entonces la noche viene sobre ellos, y el día de su visitación pasa;
porque Dios no contenderá para siempre con aquellos
que larga y frecuentemente han sido reprobados,
y sin embargo siguen endureciendo su cerviz. No, después de una larga paciencia,
Él retira el alcance de Su misericordiosa bondad y los deja caer bajo esa terrible sentencia:
"`El que es injusto, sea injusto todavía; y el que es inmundo, sea inmundo todavía.`"^
footnote:[Apocalipsis 22:11]

Cuando las personas están judicialmente endurecidas,
y entregadas a los deseos de su propio corazón y a sus amados engaños,
y son dejadas en un estado de insensibilidad al Espíritu divino, pueden, en su ceguera,
confundir su condición con una de paz y seguridad.
A estos se les oscurece la conciencia, como un libro cerrado que no pueden leer.
Pero en el día de la justa retribución del gran Juez de los vivos y de los muertos,
este volumen oculto será otra vez abierto por Aquél que abre y ninguno cierra,
y se hará una justa distribución a cada uno conforme a lo que está escrito allí.
Esto resultará ser para cada hombre un libro de vida o un libro de muerte:
"`Vida eterna a los que, perseverando en bien hacer,
buscan gloria y honra e inmortalidad,
pero ira y enojo a los que son contenciosos y no obedecen a la verdad,
sino que obedecen a la injusticia.`"^
footnote:[Romanos 2:7-8]

Por lo tanto,
concluimos razonablemente que Dios no sólo pone delante
del hombre el bien y el mal en sus respectivas distinciones,
sino que, al mismo tiempo, le da la capacidad de escoger qué quiere seguir.
Además de esto, Dios despierta y ayuda al hombre a desear la felicidad verdadera,
y mientras el corazón permanezca en este deseo, Él le da poder al hombre para batallar,
esforzarse y luchar eficazmente por su liberación y preservación.

Las más íntimas motivaciones de la voluntad humana son imposibles
de discernir sin la luz del Espíritu de Dios,
y por falta de discernimiento,
algunos han aprovechado la ocasión para acusar a Dios de ser el responsable de
las diversas respuestas de la humanidad a la visitación de la gracia divina,
haciéndolo a Él el autor principal de la maldad, rebelión y condenación del hombre.
¿Pero no es absurdo suponer que Dios produciría voluntariamente
lo que es contrario a Su naturaleza?
¿No es todo pecado una transgresión a la voluntad de Dios,
y todo vicio contrario a Su naturaleza?
¿Cómo entonces podrían estas cosas ser producidas por un acto de Su voluntad,
o ser el fruto genuino de Su poder, ya sea directa o indirectamente?
¿Puede un entendimiento correcto llevar a un hombre a pensar que la voluntad de Dios es,
en algún momento, contraria a Su naturaleza?
De la pureza, bondad y virtud no podría surgir naturalmente ninguna impureza,
vicio ni maldad.

Pero algunas Escrituras han sido objetadas, tales como:
"`Imposible es que no vengan tropiezos.`"
Cierto; ¿pero de dónde vienen?
No de Dios, sino de esa raíz de corrupción que entró y se esparció en el mundo.
Mientras esta raíz corrupta permanezca, los tropiezos surgirán naturalmente de ella;
y el mismo texto pronuncia: "`¡Ay de aquel por quien vienen!`"^
footnote:[Lucas 17:1]
Pero el Señor dice que Él creó el mal,^
footnote:[Isaías 45:7 RV1602P]
y el profeta dice: "`¿Habrá algún mal en la ciudad, el cual Jehová no haya hecho?`"^
footnote:[Amos 3:6]
Esto no se refiere al mal moral, sino más bien al mal y a la calamidad natural,
como el dolor y la angustia causados por la hostilidad, la enfermedad, la hambruna, etc.,
que son los juicios de Dios sobre el hombre debido a su
desobediencia y por cometer maldades de tipo moral.

Por lo tanto, según mi entendimiento,
el pecado consiste en que la criatura prefiera complacer
su naturaleza depravada antes que obedecer a la gracia divina.
Esta autocomplacencia conduce al abuso de esa gracia, y así, a pensar,
hablar y actuar en contra de la voluntad manifiesta de su Creador.
Ahora,
es ciertamente verdad que algunos obedecen y que otros rehúsan
obedecer la manifestación de la gracia divina;
pero creemos que Dios no es la causa de esta diferencia,
sino que recae enteramente en el individuo.
De hecho,
no es difícil creer que la misma naturaleza tenga efectos
diferentes en sujetos que se encuentran en condiciones diferentes.
Pues es evidente, a la vista de todo hombre,
que los rayos del sol ablandarán el alquitrán y endurecerán la arcilla.
Estos efectos contrarios no provienen de una diferencia en los rayos del sol,
sino de una diferencia en la disposición del alquitrán y del barro para recibirlos.
De la misma manera,
el Espíritu Santo opera de forma diferente en personas diferentes debido
a sus estados y disposiciones diferentes para recibir Sus influencias.
Que aquel que duda de esto indague en su propia conciencia,
y el Testigo fiel allí (por medio de Sus condenaciones por
el mal) le mostrará claramente que la falta es suya.
¿Qué hombre sobre la tierra no ha sido golpeado por la culpa y el remordimiento?
¿Quién no ha sentido en algunos momentos que se encienden dentro de él
inclinaciones y disposiciones hacia la virtud y hacia una vida piadosa?
Y tras seguir esta guía, ¿no ha encontrado paz en su obediencia?
Pero habiéndose vuelto de ella para perseguir algo de la naturaleza contraria,
¿no ha sufrido angustia y condenación? ¿Necesitará una criatura razonable
más pruebas de que tanto las reprensiones condenatorias como los consuelos
son los juicios internos y directos de un Espíritu justo,
bueno, poderoso, omnipresente y omnisciente?
¿Y con qué fin trata Dios el alma de cada hombre de esta manera,
sino para que todos lleguen al arrepentimiento y experimenten la salvación?

Entonces, la primera causa iniciadora,
verdadera y legítima de la salvación del hombre es
la bondad y el amor de Dios para con él,
y la operación de Su propio Espíritu Santo en el alma del
hombre es el medio esencial por el cual obra la salvación,
a menudo directamente y otras veces haciendo uso de medios secundarios como la predicación,
la lectura de las Escrituras y de otros libros buenos, conversaciones piadosas,
adoración, misericordias, angustias, etc.
Pero es Dios, a través de Su propio Espíritu Santo,
quien obra todo lo bueno en el hombre, tanto el querer como el hacer.
Es por gracia que somos salvos, por medio de la fe, o en el camino de la fe.
Esta fe obra por el amor de Dios^
footnote:[Gálatas 5:6]
para purificar el corazón,^
footnote:[Hechos 15:9]
y producir buenas obras.^
footnote:[Santiago 2:14-26]
Estas obras son los frutos genuinos de la verdadera fe, y son inseparables de ella;
por lo tanto, sin obras no podemos ser salvos.^
footnote:[Santiago 2:24]
Sin embargo, no es por las obras que somos salvos,
como la causa de la salvación para nosotros,
sino por la gracia (raíz de ellas) y por la fe, por medio de la cual creemos en Dios,
nos abrimos a Él y lo recibimos, nos aferramos a Él, confiamos en Él,
y así a echamos mano de la vida eterna.

Esta fe no es facultad nuestra, sino un don de Dios para nosotros.^
footnote:[Hebreos 12:2, 2 Pedro 1:1, Filipenses 1:29]
Viene por gracia, la gracia gratuita de Dios, quien no quiere "`que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Aquél cuyas obras son malas no tiene esta fe salvadora,
sin importar qué doctrinas o creencias tenga.
Porque donde está la fe verdadera, necesariamente produce buenas obras.
De hecho, esta raíz nunca está sin sus frutos.
El apóstol Santiago dice: "`Muéstrame tu fe sin tus obras,
y yo te mostraré mi fe por mis obras.`"^
footnote:[Santiago 2:18]
Sin embargo, estas obras no merecen la salvación,
porque no deben ser atribuidas a nosotros, sino totalmente Al que, a través de Su gracia,
nos ha llevado al bendito estado de fe viva en el que ellas se producen.
"`Porque por gracia sois salvos por medio de la fe; y esto no de vosotros,
pues es don de Dios; no por obras, para que nadie se gloríe. Porque somos hechura suya,
creados en Cristo Jesús para buenas obras,
las cuales Dios preparó de antemano para que anduviésemos en ellas.`"^
footnote:[Efesios 2:8-10]

Todas las almas que Dios ha creado son igualmente Suyas,
y Aquél cuyas "`misericordias están sobre todas Sus obras,`"^
footnote:[Salmo 145:9]
no se olvida de ninguna de Sus criaturas en la distribución de Sus misericordias.
Él no le niega a nadie Sus talentos,
sino que los distribuye en porciones diferentes a personas diferentes.
A una le da cinco talentos, a una segunda le da dos, y a una tercera, uno;
pero a cada una se le da la manifestación divina suficiente para obrar su salvación,
si cree en ella y la obedece.
El Creador justamente requiere un incremento correspondiente a la medida que proporciona;
y como Él sabe perfectamente hasta qué grado de progreso podría llegar cada uno,
al final juzgará a todos según su incremento,
su negligencia o su total rechazo del talento recibido.

Por una interpretación errónea del segundo mandamiento,
el pueblo de Israel en tiempos de Ezequiel,
había adoptado la idea de que los niños eran castigados por los pecados de sus padres,
por lo que se había convertido en un refrán entre ellos:
"`Los padres comieron las uvas agrias, y los dientes de los hijos tienen la dentera.`"
Por lo tanto,
el profeta fue comisionado particularmente para declarar
la voluntad inmutable de Dios en oposición a esto:
"`Vivo yo, dice Jehová el Señor,
que nunca más tendréis por qué usar este refrán en Israel.
He aquí que todas las almas son mías; como el alma del padre,
así el alma del hijo es mía; el alma que pecare, esa morirá.`"^
footnote:[Ezequiel 18:3-4]
"`El hijo no llevará el pecado del padre, ni el padre llevará el pecado del hijo;
la justicia del justo será sobre él, y la impiedad del impío será sobre él.`"^
footnote:[Ezequiel 18:20]
"`Y si dijereis: No es recto el camino del Señor; oíd ahora, casa de Israel:
¿No es recto mi camino?
¿no son vuestros caminos torcidos?
Apartándose el justo de su justicia, y haciendo iniquidad, él morirá por ello;
por la iniquidad que hizo, morirá. Y apartándose el impío de su impiedad que hizo,
y haciendo según el derecho y la justicia, hará vivir su alma.
Porque miró y se apartó de todas sus transgresiones que había cometido, de cierto vivirá;
no morirá.`"^
footnote:[Ezequiel 18:25-28]
"`Por tanto, yo os juzgaré a cada uno según sus caminos, oh casa de Israel,
dice Jehová el Señor. Convertíos, y apartaos de todas vuestras transgresiones,
y no os será la iniquidad causa de ruina.`"^
footnote:[Ezequiel 18:30]
El profeta repite aún más con el mismo propósito,
tanto en este capítulo como en el 33. "`Vivo yo, dice Jehová el Señor,
que no quiero la muerte del impío, sino que se vuelva el impío de su camino, y que viva.
Volveos, volveos de vuestros malos caminos; ¿por qué moriréis, oh casa de Israel?`"^
footnote:[Ezequiel 33:11]
"`Luego dirán los hijos de tu pueblo: No es recto el camino del Señor;
el camino de ellos es el que no es recto.
Cuando el justo se apartare de su justicia, e hiciere iniquidad, morirá por ello.
Y cuando el impío se apartare de su impiedad, e hiciere según el derecho y la justicia,
vivirá por ello.`"^
footnote:[Ezequiel 33:17-19]
Ahora bien,
es evidente que la muerte de la que se habla en estas
Escrituras no es la muerte común del cuerpo,
porque en cuanto a eso, lo mismo sucede con los justos y los impíos. Sin duda,
la muerte que se menciona aquí se refiere al estado eterno e infeliz de las almas
que salen del tiempo a la eternidad sin arrepentimiento y regeneración.

Es evidente, por todas estas expresas declaraciones,
que el Todopoderoso "`no aflige ni entristece voluntariamente a los hijos de los hombres;`"^
footnote:[Lamentaciones 3:33]
que "`no quiere que ninguno perezca, sino que todos procedan al arrepentimiento,`"^
footnote:[2 Pedro 3:9]
y que quiere "`que todos los hombres sean salvos y vengan al conocimiento de la verdad.`"^
footnote:[1 Timoteo 2:4]
Todas estas escrituras son manifestaciones claras
de la mente de Dios con respecto a este punto,
y deberían ser concluyentes.
Los pecados de los hombres deben atribuirse a su propia voluntad,
y no a la voluntad de Dios.
"`¿Por qué moriréis, casa de Israel?`"^
footnote:[Ezequiel 18:31, 33:11]
En efecto, queda claro que Él hace todo lo posible por medios justos para impedirlo.
Por esa apremiante repetición: "`Volveos,
volveos de vuestros malos caminos,`" es manifiesto como Él pone
en poder de los hombres la capacidad de volverse de ellos.
¿Quién puede, entonces, justificar su perversidad, o de algún modo,
cargar su pecado--ya sea directa o indirectamente--a Su cuenta?
Los hombres no son destruidos por ninguna malevolencia en su Creador;
más bien son salvados por Su gracia,
la cual Él otorga a todos desde esa incomparable
benevolencia que surge puramente de Su bondad infinita.
El hombre pecador no tiene nada que ofrecer.
Por lo tanto, Dios tendrá misericordia porque quiere tener misericordia.
Sí, debido a que está lleno de misericordia,
Él la otorgará a sus indefensas e indignas criaturas.
"`Yo,`" dice el Señor al pecador arrepentido,
"`yo soy el que borro tus rebeliones por amor de mí mismo,
y no me acordaré de tus pecados.`"^
footnote:[Isaías 43:25]

Varios textos y porciones de las Escrituras han sido argumentados y utilizados
para atribuir una cruel parcialidad a nuestro Creador y Benefactor.
Se nos ha dicho que Él ordenó la obstinación de Faraón,
el pecado y locura de Sehón y de los reyes de Canaán,
la rebelión desleal de Sedequías en contra del rey de Babilonia,
los estragos de Nabucodonosor, etc.
Sin embargo, al considerarse debidamente,
se revela que Dios asigna castigo a causa del pecado,
pero no asigna pecado para ser castigado.
El Señor no endurece a ninguno hasta que se haya endurecido
a sí mismo más allá de toda posibilidad de arrepentimiento,
y entonces lo entrega al desorden de sus propias concupiscencias y amados vicios.
Y lo que es considerado como injustas devastaciones--aunque realmente
lo sean en quienes las comenten--con respecto al Todopoderoso,
son la ejecución justa de Su justicia en contra de
aquellos que han colmado su medida de iniquidad,^
footnote:[Ver, por ejemplo, Génesis 15:16, "`Y en la cuarta generación volverán acá;
porque la maldad del amorreo aún no ha llegado a su colmo.`"]
y han abusado de Su gracia bondadosa y de Su larga paciencia hacia ellos,
hasta que Él decide oportuno no extendérselas más. Y así,
castiga la iniquidad arraigada de algunos por medio de la iniquidad de sus enemigos,
la cual Él permite que se vuelva contra ellos.
Pero después procede de la misma manera con aquellos
que fueron Sus instrumentos de castigo,
cuando también han colmado su medida.

El Ser divino es una sola esencia, perfectamente pura y simple.
Él es un solo poder eterno e inmutable, que crea y sustenta a todos los demás seres,
y que opera de diversas maneras según el estado de cada persona,
pero nunca contrariamente hacia los que están en la misma condición.
Puesto que todas las almas son igualmente Su creación directa,
no existe ninguna razón justa que pueda ser alegada para explicar por qué Él,
que es justo en todos Sus caminos, santo y misericordioso en todas Sus obras,
las trataría con tanta desigualdad,
predestinando a unas a la felicidad eterna y a otras a la inevitable miseria.
¡Oh, Sus misericordias están sobre todos, son para todos,
con una intención justa y bondadosa hacia todos!
El bondadoso Redentor compró dones de gracia tanto para aquellos que prueban ser rebeldes,
como para los demás,
y todos son visitados con una manifestación de Su Espíritu
para que puedan obtener provecho a través de ella.
Y aunque los hombres se vuelven del poder que los visita,
y muchas veces se apartan de la ayuda que se les brinda, Él todavía los sigue,
una y otra vez, con mucha paciencia, y con frecuencia los vuelve a visitar,
debido a Su abundante gracia y misericordia,
con el fin de convencerlos de que se arrepientan y sean salvos.
La condenación de los hombres, según nuestro Salvador,
no es el fruto de ningún decreto hecho de antemano, porque "`esta es la condenación:
que la luz vino al mundo, y los hombres amaron más las tinieblas que la luz,
porque sus obras eran malas.`"^
footnote:[Juan 3:19]
