== Capítulo 11. Las Escrituras y el Espíritu

Con respecto a las Escrituras,
estamos tan lejos de quitarles importancia o de oponernos al sentido verdadero de ellas,
que creemos firmemente y afirmamos sinceramente, que el Espíritu Santo,
en cualquier grado de iluminación en que aparezca, nunca puede contradecirlas.
Lo que objetamos son las interpretaciones privadas o particulares del hombre,
sin iluminación divina,
ya que son insuficientes para dar el verdadero significado de las Escrituras en disputa.
Además de la incapacidad natural del hombre, sus diversos prejuicios,
sus pasiones predominantes, sus diferentes intereses y sus variados líderes,
todo contribuye a dar interpretaciones diferentes, y a veces opuestas, del texto sagrado.
Muchos tienen las palabras del Espíritu en las Escrituras,
pero no tienen la mente del Espíritu en sus corazones.

Sin iluminación divina,
el hombre no tiene capacidad suficiente para determinar
el sentido correcto de los textos dudosos y discutidos,
que son muchos.
De hecho, la gran diferencia en las interpretaciones hechas
por personas aparentemente igual de sinceras,
y con las mejores habilidades tanto naturales como aprendidas,
entre las mismas denominaciones y entre diferentes,
indica claramente cuán indispensable es la ayuda del propio
Autor Divino para el entendimiento correcto de ellos.
Anteriormente mostré que la razón del hombre está demasiado
nublada e influenciada por sus pasiones y prejuicios,
como para que sea justamente llamada razón correcta,
porque a menudo manifiesta una gran diversidad en cuanto a asuntos espirituales,
e incluso una inestabilidad en la misma persona.
La razón correcta es la verdad, inmutablemente la misma e incapaz de errar,
y por lo tanto sólo existe en la naturaleza divina, de la que el hombre debe, en medida,
hacerse partícipe para rectificar su razón caída y falible.

Ni la naturaleza ni la educación pueden darle al hombre el sentido del Espíritu Santo,
ni interpretar las expresiones del Espíritu con certeza.
Por lo tanto, se afirma verdaderamente, no sólo por los Cuáqueros,
sino también por muchos escritores distinguidos de diversas profesiones,
antiguos y modernos,
que la iluminación interna del Espíritu Santo es absolutamente necesaria
para que cada hombre entienda correctamente las Escrituras.

Ahora,
muchos imponen su propia opinión particular sobre algunas partes de las Escrituras,
como la intención verdadera del Espíritu Santo,
aunque niegan la experiencia de la iluminación del Espíritu Santo en sus corazones.
Pero, ¿por qué debería dárseles algún crédito a tales afirmaciones,
viendo que existe tanta diversidad de opiniones?
Ellos alegan: "`¡Las Escrituras son infalibles!`"
Estoy de acuerdo; pero,
¿cómo se transmite infaliblemente su verdadero significado a cada lector?
¿A través del estudio e instrucción humanos?
¡Eso ha llevado a todas las diferencias y desacuerdos con respecto a ellas!
La simple verdad del asunto es que nada más que el Espíritu de la Sabiduría divina,
de donde provienen las Escrituras, puede dar el sentido genuino de ellas.
Porque "`nadie conoce las cosas de Dios, sino el Espíritu de Dios.`"^
footnote:[1 Corintios 2:11]
¿Qué es la infalibilidad de las Escrituras para alguien
que no conoce al Maestro infalible de ellas?
Si todos los que tuvieran las Escrituras conocieran a este Maestro,
ninguno podría malentenderlas o diferir entre sí acerca de ellas.
Sin embargo, es demasiado evidente, por las diferencias entre los cristianos,
que ellos sí las malentienden.
Tal confusión no debe ser atribuida a ningún defecto en los escritos sagrados,
sino a la incapacidad común en el entendimiento de los hombres,
para descubrir el sentido correcto de las palabras de Dios.
¿Qué, pues,
es capaz de abrir las Escrituras al entendimiento
de los hombres aparte del Espíritu Santo?
La pregunta no es si las Escrituras, tal como están escritas por la inspiración divina,
son infaliblemente correctas.
Sin duda lo son.
La pregunta es si todos los que las leen son infaliblemente capaces de entenderlas.
Algunos dicen que, si las Escrituras no pueden entenderse sin el Espíritu,
son dadas en vano.
Pero esto es contradecir las Escrituras mismas,
que claramente declaran que "`a cada uno le es dada
la manifestación del Espíritu para provecho.`"^
footnote:[1 Corintios 12:7]
Las palabras del apóstol son claras en este asunto:
"`Nosotros no hemos recibido el espíritu del mundo,
sino el Espíritu que proviene de Dios, para que sepamos lo que Dios nos ha concedido,
lo cual también hablamos, no con palabras enseñadas por sabiduría humana,
sino con las que enseña el Espíritu, acomodando lo espiritual a lo espiritual.
Pero el hombre natural no percibe las cosas que son del Espíritu de Dios,
porque para él son locura, y no las puede entender,
porque se han de discernir espiritualmente.`"^
footnote:[1 Corintios 2:12-14]

Las doctrinas de las Escrituras son de varios tipos.
Muestran la moral justa y la conducta benevolente de forma superior
a los mejores escritores éticos de todas las edades y naciones.
Estas son aceptadas general y apropiadamente como de obligación natural,
universal e inalterable,
y son suficientemente sencillas y claras para el entendimiento común de cada hombre.
Pero los asuntos relacionados con la fe y la adoración,
habiendo pasado por muchas adiciones y alteraciones circunstanciales,
según las diferentes dispensaciones de la Sabiduría divina,
no han sido tan claros para el entendimiento de los hombres,
ni los hombres han estado tan unidos en su opinión
acerca de ellos como en el caso de los deberes morales.
Desde la publicación del Nuevo Testamento,
las diferencias de opinión sobre el verdadero significado,
especialmente en asuntos de fe, han persistido y abundado;
¿y cómo se pueden resolver estas diferencias?
El erudito A dice que un texto particular significa esto y lo otro.
El erudito B insiste en que se debe entender en un sentido diferente, tal vez contrario.
Apelan al contexto, y sin embargo,
siguen igualmente con opiniones diferentes y seguros de estar en lo correcto.
Pasan de un texto a otro, y de críticos a comentaristas,
hasta agotar a todos los que puedan encontrar o forzar para su propósito,
y continúan en la misma, si no más, discordia que al principio.
¿Qué les queda para resolver el asunto?
¿Podrán hacerlo las iglesias o concilios?
Ellos debaten de año en año, o de siglo en siglo,
y dejan la diferencia tan amplia como la encontraron.
El sentido verdadero le sigue perteneciendo solamente
al Autor divino de los textos en disputa,
y sólo Él puede comunicarlo.
¡Ay!, este ha sido el caso por muchos siglos,
y continuará siempre mientras los hombres prefieran sus propios prejuicios,
imaginaciones y razonamientos a la guía interna del Espíritu de Verdad.

Sostenemos que las Escrituras son la regla que gobierna y guía a todos los que las tienen,
en la medida que tengan un entendimiento correcto de ellas.
No obstante, no podemos afirmar que son el único,
principal y universal director de la humanidad en cuestiones de deberes religiosos,
por las siguientes razones: 1. No son el único director,
porque el Espíritu de Dios en el corazón y conciencia del hombre,
es también un director innegable.
2+++.+++ No son el director principal,
porque la iluminación del Espíritu Santo que las dio es necesaria
para abrir el sentido verdadero de muchas de sus partes,
sobre las cuales las interpretaciones de los hombres difieren tanto.
El Espíritu, de quien provienen las Escrituras, siendo su origen,
es por lo tanto superior a ellas;
y dado que sólo el Espíritu puede revelar el significado de Sus palabras,
las palabras son secundarias al Espíritu, como un instrumento en Sus manos.
3+++.+++ No son el director universal, porque no es probable que uno de diez,
incluso uno de cada veinte de los hombres,
haya tenido alguna vez la oportunidad de poseerlas.
Por lo tanto, viendo que este es el caso,
no pueden ser debidamente declaradas como la regla perfecta,
adecuada y universal de la humanidad.

Por consiguiente,
estimamos las Escrituras como la regla o guía secundaria de los cristianos,
las cuales han sido divinamente comunicadas para el uso de todos a quienes lleguen.
Y puesto que son intrínsecamente superiores en excelencia a todos los demás escritos,
las preferimos por encima de todos ellos,
y las utilizamos con la misma gratitud y consolación que cualquier cristiano en la tierra,
creyendo verdaderamente que "`para nuestra enseñanza fueron escritas,
a fin de que por la paciencia y la consolación de las Escrituras, tengamos esperanza.`"^
footnote:[Romanos 15:4]
No despreciamos las Escrituras, de hecho las mantenemos en su lugar apropiado,
como superiores a todas las obras de los hombres,
pero subordinadas a su Comunicador Supremo y único Intérprete seguro.
Porque el Espíritu Santo es necesario para el uso correcto de ellas,
como un agente con un instrumento;
¿y qué es un instrumento sin una mano para guiarlo y darle fuerza?
¿Y cuál es superior, el agente o el instrumento?
El Espíritu Santo es la sabiduría original de la cual provienen las Escrituras,
y el único poder que puede abrirlas y darles su efecto correcto.
El Espíritu de la Verdad es dado para guiar a toda verdad,
y es el único que puede hacerlo, siendo, por lo tanto,
el Guía Supremo proporcionado a la humanidad.

Es tanto insostenible como irracional afirmar que
algo podría actuar como el director único y principal,
cuando el Espíritu de Dios se ha comunicado con ese propósito.
Los mismos pasajes de la Escritura se muestran tan diferentes a cada persona,
como difieren sus entendimientos entre sí. Por lo tanto,
el entendimiento humano debe ser rectificado para que sean
capaces de ver esas verdades en la misma luz.
El Espíritu de la Verdad es el Rectificador,
Él único que puede unir a los hombres en el sentido verdadero.
No dudamos en llamar a las Escrituras colectivamente una regla divina;
pero nos oponemos a llamarlas la regla de fe y práctica,
no sea que esto implique que no buscamos nada más para ser nuestro guía o líder.

Las mismas Escrituras testifican abundantemente que hay algo superior a ellas,
que todos deben buscar y atender.
Ese algo es el Espíritu Santo del Legislador Supremo de los hombres,
el Espíritu del Autor de los escritos sagrados.
Y es en y por Su luz y poder,
que las Escrituras se vuelven un instrumento útil y adecuado
para los propósitos que se pretenden con ellas.
Como un buen reloj de sol,
las Escrituras son verdaderas y perfectas según su propósito y naturaleza, es decir,
como escritos.
Sin embargo,
ellas apropiadamente pueden tener el mismo lema que
el reloj de sol--Non sine lunine (Es decir:
'`Nada sin luz`'). Porque,
así como un reloj de sol no tiene un verdadero uso sin los rayos del sol,
tampoco un pasaje ambiguo de las Escrituras comunica infaliblemente
la mente del Espíritu Santo a diferentes entendimientos,
a menos que los rayos luminosos del Sol de Justicia lo revelen a la mente atenta.

Nuestros oponentes llaman a las Escrituras la regla principal.
Confesamos que es la regla escrita principal,
y en todas las disputas entre ellos y nosotros, respetamos sus decretos,
según nuestro entendimiento del significado de ellas,
lo cual ellos también dicen hacer según el suyo.
Por lo tanto,
en todas las diferencias públicas recurrimos intencionalmente a la misma regla con ellos.
Pero nosotros también tenemos tanto la Escritura clara como
la experiencia para respaldar nuestra creencia de que,
con respecto al deber de cada individuo en particular,
todos tienen en su propio pecho una regla o guía
de la conciencia más cercana y segura que las Escrituras,
a saber: "`la manifestación del Espíritu dada para provecho.`"^
footnote:[1 Corintios 12:7]
Y cuando esta guía es debidamente observada,
da tanto la interpretación correcta de la Escritura (hasta donde sea necesario),
como también un sentido del deber de cada persona en particular.
De hecho, cuando alguien siente al testigo fiel de Dios en su conciencia,
condenándolo por lo que está mal y aprobándolo por lo que está bien,
¿acaso no encuentra que este testigo le habla más claro,
particular y convincentemente a su caso y estado que lo
que puede leer en las palabras de las Escrituras?
¿Y concluirá entonces que este testigo verdaderamente
discernidor es menos que aquel Espíritu de Verdad,
o Consolador, que "`convence al mundo de pecado, de justicia y de juicio?`"^
footnote:[Juan 16:8]
Pero ¡ay! he observado en los que no obedecen a este testigo celestial,
que la opinión de cada hombre sobre las Escrituras es su Escritura,
y cuando le propone a su oponente que todo sea determinado por las Escrituras,
quiere decir de acuerdo con su propia compresión de su significado.

Cuando Cristo, después de Su resurrección, "`abrió el entendimiento de sus discípulos,
para que entendiesen las Escrituras,`"^
footnote:[Lucas 24:45]
¿no fue la iluminación divina en sus entendimientos una evidencia mucho más clara,
cierta y superior de su significado,
que toda su lectura y estudio podrían haberles proporcionado sin
tal iluminación? ¿Se ha vuelto la humanidad tan sabia y perceptiva
que ya no tiene necesidad de Su ayuda para abrirle su entendimiento?
¿Es su aprendizaje en escuelas y universidades tan perfecto como
para hacer la iluminación de Dios completamente innecesaria?
¿Son los innumerables enfrentamientos y debates de los sacerdotes y maestros intelectuales
sobre el significado de las Escrituras una prueba de la unidad en sus sentimientos?
¡Oh,
consideren! ¿Cómo pueden afirmar que las Escrituras son el criterio final y definitivo,
cuando es precisamente el significado de las Escrituras
lo que da lugar a toda incertidumbre y diferencia?
Es evidente, por lo tanto, que sin la iluminación divina,
cada lector de los textos sagrados acepta cualquier
significado que sus suposiciones le dicten,
lo cual es la causa de las innumerables diferencias entre los que se profesan cristianos.
