== Capítulo 12. El Poder Purificador del Evangelio

Considero que esta es una oportunidad apropiada para hacer una
advertencia en contra de las posiciones corruptas y peligrosas,
que algunos han declarado públicamente acerca de la verdadera justicia
y santificación. Muchos han enseñado abiertamente o dado a entender:

[.numbered-group]
====

[.numbered]
1+++.+++ Que el hombre, al mismo tiempo que es realmente injusto en sí mismo,
es justo en Cristo.
Es decir, que él no es en realidad lo que es, sino lo que se convence a sí mismo ser,
por causa de una imaginación falsa acerca del sacrificio de Cristo.
Estos son como aquella "`generación que es pura en sus propios ojos,
más nunca ha sido lavada de su inmundicia.`"^
footnote:[Proverbios 30:12 RV1602P]

[.numbered]
2+++.+++ Que el Ser supremo de la verdad inmutable mira al hombre con una luz falsa,
estimándolo puro, mientras Él sabe que es pecador y corrupto.

[.numbered]
3+++.+++ Que Cristo, la Verdad, es algo así como un medio falso,
que muestra los estados de los hombres de manera contraria a lo que realmente son.

[.numbered]
4+++.+++ Que el hombre puede ser siervo de Cristo mientras está bajo la influencia del anticristo;
que es santo por imputación, incluso cuando es gobernado por el autor de la corrupción,
el adversario de toda santidad;
y que está obrando en la voluntad de Dios mientras hace las obras del diablo.

====

Muy al contrario leemos:
"`¿No sabéis que si os sometéis a alguien como esclavos para obedecerle,
sois esclavos de aquel a quien obedecéis, sea del pecado para muerte,
o sea de la obediencia para justicia?`"^
footnote:[Romanos 6:16]

Es una ilusión vana esperar que la Pureza en su más alta perfección,
se una al hombre mientras permanece en la causa misma de
la separación de Él. El pecado causó la separación al principio,
y su continuación mantiene la separación. Si se pregunta:
¿Acaso no murió Cristo para reconciliar a los pecadores con Dios?
Respondo: Sí, pero no para reconciliar a Dios con el pecado, ni para salvar el pecado.
Él sufrió,
no para comprar una licencia para que los pecadores continúen siendo pecadores,
sino para abrirles el camino para que lleguen al arrepentimiento,
a través del don de la gracia procurado por Él. "`Antes,`" dice Él,
"`si no os arrepentís, todos pereceréis igualmente.`"^
footnote:[Lucas 13:3, 5]
Él no vino para mantener, sino "`para deshacer las obras del diablo,`"^
footnote:[1 Juan 3:88]
que incluyen toda clase de pecado y corrupción. El hombre de Dios dice:
"`¿No sabéis que los injustos no heredarán el reino de Dios?
No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados,
ni los que se echan con varones, ni los ladrones, ni los avaros, ni los borrachos,
ni los maldicientes, ni los estafadores, heredarán el reino de Dios.`"^
footnote:[1 Corintios 6:9-10]
Por lo tanto, la idea de la justicia imputada a quienes continúan cometiendo estos males,
es un error vano y peligroso.
Debemos morir al pecado, o no podemos vivir para Dios;
y en la medida que morimos al pecado, vivimos en Cristo,
y no más allá. Debemos revestirnos de Cristo por medio de la verdadera fe y obediencia,
las cuales nunca están separadas;
porque es una fe falsa la que permanece en la desobediencia.
La "`fe sin obras está muerta,`"^
footnote:[Santiago 2:26]
dice el siervo de Cristo; y añade: "`Muéstrame tu fe sin tus obras,
y yo te mostraré mi fe por mis obras.`"^
footnote:[Santiago 2:18]

El evangelio no sólo prohíbe las obras externas del pecado,
sino que también somete el deseo e inclinación interna hacia él. La ley dice:
'`No matarás; no cometerás adulterio; no jurarás en falso, etc.`' El evangelio ordena:
'`No des lugar a la ira; no codiciarás; no jures en ninguna manera,
etc.`' De esta forma el evangelio no destruye la ley moral, sino que la cumple,
al quitar la sede del pecado y poner el hacha del Espíritu a la raíz de la corrupción.
¿Puede un hombre razonable creer que la Fuente eterna de sabiduría y poder no
sabe cómo expulsar el reino de Satanás en el hombre mientras vive sobre la tierra?
¿O piensan que Dios se complace en las ofensas de los hombres contra Su pureza y bondad,
y que está dispuesto a que Satanás reine sobre Sus
criaturas hasta el último momento de sus vidas?
¿No sería más para la gloria de Dios liberar del presente reino del pecado,
al salvar del mal y de la miseria tanto aquí como en el porvenir,
en lugar de sólo salvar de la miseria futura?
¿Es preferible o más gloriosa una redención incompleta que aquella que es perfecta?
Cuando doctrinas contrarias a la purificación del corazón y a la vida
de santidad son activamente propagadas entre los cristianos profesantes,
es deber de todos estar alarmados y temerosos, no sea que, al darles lugar en sus mentes,
queden cegados por el engaño del pecado.
De hecho, esto finalmente los llevará al paraíso de los necios,
en lugar de a la ciudad de Dios, la Jerusalén celestial,
a la cual "`no entrará ninguna cosa inmunda, o que hace abominación y mentira.`"^
footnote:[Apocalipsis 21:27]

El apóstol Pedro habló de una fe que "`purifica el corazón,`"^
footnote:[Hechos 15:9]
y haríamos bien en considerar qué es esta verdadera fe del evangelio.
Así como la entrada de la Palabra divina vivifica el alma,
así también comunica primero una medida de fe por la cual opera.
Porque toda fe verdadera es don de Dios, y el Espíritu Santo es el Espíritu de la fe,
la cual no es una simple creencia en las verdades acerca de Cristo,
sino la fe en Él. La fe en Cristo no consiste en
darle crédito o aceptación a historias y doctrinas,
junto con modos de prácticas formulados por la sabiduría de los hombres.
En verdad, todo esto queda muy corto de la sustancia esencial de la fe.
La fe del evangelio que opera en el hombre cree la
verdad de todo lo que es revelado por el Espíritu,
tanto en el corazón como en las sagradas Escrituras, porque ella siente la verdad,
la saborea y es una con ella.
No solamente está de acuerdo con los relatos bíblicos de
la encarnación y de todo el proceso de Cristo en Judea,
sino que también recibe Su aparición interna,
cede a Su operación interior y concuerda con ella.
La fe que se basa totalmente en palabras, tradición, lectura o imaginación,
no es más que un tipo distante de creencia ineficaz que le permite
al alma permanecer en la esclavitud de la corrupción. El impío
puede avanzar hasta este punto en cuanto a la fe del evangelio,
pero la fe verdadera echa mano y se adhiere al Espíritu
de Verdad en Sus manifestaciones internas,
en el cual está firme y por el cual crece hasta que el corazón es purificado,
el mundo vencido y la salvación obtenida.

La fe del evangelio es como una llama de amor puro en el corazón hacia Dios.
Impulsa hacia Él, tiene sed de Él, se rinde a Él,
confía y vive en Él. "`El misterio de la fe se guarda en una conciencia limpia`"^
footnote:[1 Timoteo 3:9]
y en el poder eficaz del evangelio eterno.
Por esta fe,
la dispensación cristiana a menudo se distingue en las Escrituras
de la dispensación externa de la ley Mosaica.
Aunque el término fe es utilizado ocasionalmente por los autores
de las Escrituras en diversos sentidos (aunque no contrarios),
esta parece ser la única fe permanente mencionada en Efesios 4:5,
la cual es en Cristo Jesús,
y es el fruto de Su gracia y buen Espíritu en el corazón. Sólo a través de esta fe las
Escrituras se vuelven efectivamente instructivas para el hombre de Dios y útiles para
el cristiano en el camino de la vida y de la salvación. Esta es la fe por la cual los
miembros de Cristo verdaderamente viven y permanecen como tales.
Sí, la fe es su escudo invencible,
y el conocimiento de Cristo en ellos es la prueba de que la poseen.

Se podría decir mucho más de la naturaleza,
el poder y los efectos de esta fe que lo vence todo,
pero espero que esto sea suficiente para demostrar que, aunque surge en el hombre,
no es del hombre.
Y aunque en su sentido completo incluye una creencia de todo lo
que se dice acerca de Cristo y por Cristo en las Sagradas Escrituras,
ella va mucho más profundo, pues nace y crece por la operación del Espíritu Santo,
el cual obra por ella la santificación del corazón
y la producción de toda virtud cristiana.

Al continuar en esta fe, el hombre echa mano de la esperanza del evangelio;
un evangelio _descrito_ por los textos evangélicos y apostólicos,
pero _definido y experimentado_ como el "`poder de Dios para salvación.`"^
footnote:[Romanos 1:16]
De hecho, Cristo mismo es llamado el "`poder de Dios,`"^
footnote:[1 Corintios 1:24]
quien espiritual e internamente administra luz y vida a las almas de los hombres.
Esta administración espiritual y poderosa es la esencia del evangelio.
Tanto el Antiguo como el Nuevo Testamento dan testimonio de la encarnación, muerte,
sepultura, resurrección y ascensión del Señor Jesucristo,
pero la sustancia verdadera del evangelio apostólico no consiste en historia y doctrina,
sino en la operación viva y palpable del poder de Dios.

Leemos que la luz y la inmortalidad fueron sacadas a luz por el evangelio,^
footnote:[2 Timoteo 1:10]
pero ¿qué es esta vida e inmortalidad que el evangelio reveló? ¿Acaso
no creía la humanidad en un estado futuro antes de la encarnación de Cristo?
Sí, indudablemente.
La mayoría de los judíos y de los gentiles ya creían y sostenían esa verdad.
Entonces,
¿en qué consiste la vida e inmortalidad que son propias
del evangelio y que es su propiedad particular revelar?
No consiste enteramente en una explicación del proceso^
footnote:[Con "`proceso,`" se refiere al curso completo del nacimiento, vida, obediencia,
sufrimientos, muerte, sepultura, resurrección y ascensión de Cristo.]
externo y de las doctrinas de nuestro Señor,
sino principalmente en ese don espiritual que Él
adquirió para nosotros a través de Sus sufrimientos,
el cual es la vida y el poder que el Espíritu inmortal
de Dios manifiesta en el alma creyente y obediente;
es decir, el Espíritu que vivifica a los que estaban muertos en delitos y pecados,
y separados de la vida de Dios.

El corazón del evangelio es la emanación de este
Espíritu de vida en los corazones de los hombres.
"`Sobre toda cosa guardada, guarda tu corazón;`" dice el hombre sabio,
"`porque de él mana la vida.`"^
footnote:[Proverbios 4:23]
Ahora, estas emanaciones de vida surgen _en_ el corazón del hombre,
pero no _desde_ el corazón mismo; porque si fuera así,
el corazón o el alma sería su propio vivificador y salvador.
Pero sólo Cristo es "`el Camino, y la Verdad, y la Vida,`"^
footnote:[Juan 14:6]
y por lo tanto, las emanaciones de vida obran en y a través del corazón por Su Espíritu.
La influencia divina de este Espíritu es la verdadera vida del alma,
aquello que la hace vivir;
y sin esto no puede (en un sentido evangélico) ser considerada un alma viviente.
Aunque todas las almas perduran hasta la eternidad, la duración eterna no es vida eterna.
Existir sin esta vida es estar muerto espiritualmente.
Por lo tanto, es indispensable que cada alma espere,
busque y encuentre esta vida inmortal,
y además aprenda a mantenerse en ella con toda diligencia,
para que pueda experimentar a diario sus emanaciones para su consuelo y preservación,
como "`una fuente de agua que salte para vida eterna.`"^
footnote:[Juan 4:14]
