== Capítulo 13. La Adoración y Revelación Espiritual

Es cierto que recomendamos el silencio y la quietud en nuestras reuniones religiosas;
y dado que nuestra manera de adorar es malentendida
por muchos y a menudo tratada con burla,
aprovecharé esta oportunidad para ofrecer una explicación al respecto.
Nosotros consideramos la adoración divina como el
acto más solemne que el hombre es capaz de realizar;
y teniendo en cuenta la inmensa e inconcebible majestad del Dios Todopoderoso,
creemos que es nuestro deber acercarnos a Él con la mayor reverencia.
Toda persona reflexiva, que sea en algún grado consciente del amor y del temor de Dios,
debe saber que es algo serio presentarse ante la vista del Ser infinito,
omnipresente y eterno.
En este sentido, el hombre sabio aconseja:
"`Cuando fueres a la casa de Dios,`"--o entres a la adoración--"`guarda tu pie;
y acércate más para oír que para ofrecer el sacrificio de los necios;
porque no saben que hacen mal.
No te des prisa con tu boca,
ni tu corazón se apresure a proferir palabra delante de Dios;
porque Dios está en el cielo, y tú sobre la tierra; por tanto,
sean pocas tus palabras.`"^
footnote:[Eclesiastés 5:1-2]
Este hombre sabía bien, como él lo expresa,
que tanto "`las disposiciones del corazón en el hombre, como la respuesta de la lengua,
son de Dios;`"^
footnote:[Proverbios 16:1, Traducción Literal del Inglés]
y esto concuerda con lo que dice nuestro Salvador:
"`Porque separados de mí nada podéis hacer.`"^
footnote:[Juan 15:5]
Por lo tanto,
no podemos llevar a cabo la adoración divina de manera
aceptable sino por medio de Su ayuda.
De hecho, esta capacidad debe ser recibida en el espíritu; porque el apóstol dice:
"`El Espíritu nos ayuda en nuestra debilidad; pues qué hemos de pedir como conviene,
no lo sabemos.`"^
footnote:[Romanos 8:26]
Siendo ciertamente este nuestro caso,
así como fue el caso de los apóstoles y los primeros creyentes,
nos corresponde esperar ese Espíritu que es necesario para ayudarnos en nuestra debilidad,
a fin de orar como conviene.
Ninguna forma de devoción inventada por los hombres puede tomar el lugar del Espíritu.
El mismo apóstol añade:
"`Por medio de él los unos y los otros tenemos entrada por un mismo Espíritu al Padre.`"^
footnote:[Efesios 2:18]
Por lo tanto,
dado que tanto nuestra ayuda como nuestra entrada son por medio del Espíritu de Cristo,
cuya renovación es según Su voluntad y no la nuestra, debemos necesariamente esperarla.

Ahora, este esperar debe ser en la quietud de la mente,
apartada del curso común de nuestros propios pensamientos,
libre de todas las imaginaciones errantes,
y también en el silencio de la expresión de palabras; porque hablar no es esperar,
sino actuar.
Las palabras son necesarias para comunicar el sentir de una persona a otra,
pero no es así con el Ser Omnisciente,
que es un Espíritu universal y Todopoderoso en todas partes, y por lo tanto,
no tiene ninguna necesidad de utilizar órganos corporales,
instrumentos o el sonido de palabras para comunicarse con el espíritu del hombre.
Si para adorar, la mente no permanece en quietud, las pasiones entrarán en acción,
y a menudo despertarán emociones descontroladas y vagas imaginaciones.
Pero en la verdadera quietud y sencillez del alma hacia Dios éstas son acalladas y sometidas.
Entonces la voz apacible y delicada del Inspirador de toda bondad llega a ser oída,
y la mente,
estando cuidadosamente ocupada en atenderla y respondiendo en fe y en humilde sumisión,
siente brotar la vida y el amor divinos.
En esto,
el alma recibe la capacidad de adorar verdaderamente al gran Autor
de su existencia y al Proveedor celestial de sus necesidades,
con una devoción que ninguna forma externa puede alcanzar.

A esta adoración no se entra dejando a un lado todas nuestras facultades,
ni cayendo en un estupor insensible,
como algunos observadores superficiales han imaginado,
sino mediante un verdadero vuelco de la mente y del corazón,
con la atención fija sólo e interiormente en el único Objeto de toda adoración,
con un deseo paciente pero ferviente por Él. Así, según el hebreo,
el experimentado Salmista aconseja: "`Guarda silencio ante Jehová,
y espera pacientemente en él.`"^
footnote:[Salmos 37:7, Traducción Literal del Hebreo]
Y con respecto a su propia práctica, dice:
"`En Dios verdaderamente está mi alma en silencio,`" agregando esta poderosa razón:
"`De él viene mi salvación.`"^
footnote:[Salmos 62:1, Traducción Literal del Hebreo]
En el verso 5 del mismo Salmo se aplica a sí mismo la siguiente exhortación: "`Alma mía,
en Dios solamente espera, porque de él es mi esperanza.`"
Él tenía un gran estímulo para esperar de esta manera, como aparece en el Salmo 40,
donde dice: "`Pacientemente esperé a Jehová, y se inclinó a mí, y oyó mi clamor.
Y me hizo sacar del pozo de la desesperación, del lodo cenagoso;
puso mis pies sobre peña, y enderezó mis pasos.
Puso luego en mi boca cántico nuevo, alabanza a nuestro Dios.`"^
footnote:[Salmos 40:1-3]

Jeremías da testimonio de la misma doctrina práctica y provechosa:
"`Bueno es esperar en silencio la salvación de Jehová.
Bueno le es al hombre llevar el yugo desde su juventud.
Que se siente solo y calle, porque es Dios quien se lo impuso.`"^
footnote:[Lamentación 3:26-28]
Esperar en silencio era una práctica de los profetas y de aquellos que acudían a ellos,
como aparece en la profecía de Ezequiel.
Vemos que mientras el espíritu del profeta estaba ocupado en una visión divina,
los ancianos de Judá estaban sentados delante de él,
como se describe al comienzo del capítulo ocho.
Durante el tiempo de esta visión, no puede suponerse que él les hablara a ellos,
o ellos a él, o unos a otros.
Este no fue un caso particular en el que se reunieron de esta forma,
porque esta era la manera en la que el pueblo de Dios se congregaba con los profetas,
como lo indica la siguiente reprobación: "`Vendrán a ti como viene el pueblo,
y estarán delante de ti como pueblo mío, y oirán tus palabras,
y no las pondrán por obra.`"^
footnote:[Ezequiel 33:31]

Le damos gracias a Dios porque en esta práctica solemne,
muchas veces hemos sido capaces de reconocer la verdad
de esta misericordiosa declaración de nuestro Señor:
"`Porque donde están dos o tres congregados en mi nombre,
allí estoy yo en medio de ellos.`"^
footnote:[Mateos 18:20]
Aquí hemos hallado el cumplimiento de aquella promesa:
"`Los que esperan a Jehová tendrán nuevas fuerzas,`"^
footnote:[Isaías 40:31]
y la certeza de aquella afirmación: "`Bueno es Jehová a los que en él esperan,
al alma que le busca;`"^
footnote:[Lamentaciones 3:25]
así como también la necesidad y autoridad de aquel sabio mandato: "`Estad quietos,
y conoced que yo soy Dios.`"^
footnote:[Salmos 46:10]

Debido a que esperar en silencio nos parece indispensable, antes de cualquier otra cosa,
para poder adorar a Dios en Espíritu y en verdad,
siempre es nuestra práctica comenzar las reuniones de esta manera;
porque creemos que el Señor debe tener la dirección y la atención de nuestros corazones.
Y si le agrada al Señor influenciar a alguien (en
la debida preparación) para que intervenga vocalmente,
ya sea, dirigiéndolo hacia Sí mismo en oración, o a nosotros en predicación,
nunca impedimos esas intervenciones,
sino más bien las ayudamos silenciosamente según nuestras medidas.
Si parece que ninguno siente la dirección para hablar, pasamos el tiempo en silencio,
en donde a menudo se experimenta la verdadera adoración interna.
Sin embargo,
nunca planificamos ninguna reunión con la intención de que sea enteramente en silencio,
como algunos erróneamente han imaginado;
porque nuestro objetivo es ser dirigidos y guiados por el buen Espíritu de Dios,
especialmente en los actos solemnes de adoración divina.
Sería muy bueno que todos (entre nosotros,
como entre otros) fueran guiados así por el Espíritu,
pero el caso es distinto en la gran mayoría;
pues muchos se sientan sin verdadero interés,
con la expectativa de escuchar el ministerio de palabras en lugar de esperar en Dios,
y por tanto muchas veces quedan decepcionados.
El apóstol dijo en su época: "`No todos los que son de Israel son israelitas.`"^
footnote:[Romanos 9:6]
Así mismo debemos reconocer que no todos los que han descendido
de fieles antepasados son fieles ellos mismos;
pero el defecto está en ellos mismos y no en el principio.

Es cierto, insistimos en que el Espíritu de la Verdad debe ser nuestro líder,
y el de todo hombre, y que este Espíritu es el guía infalible,
y en la medida en que alguien lo sigue fielmente, es dirigido infaliblemente,
y no más allá. Sin embargo, nunca hemos dicho, ni lo hacemos ahora,
que todos los que están con nosotros en la sociedad sean así guiados,
o siquiera que busquen suficientemente serlo.
Tampoco fue este el caso entre los primeros cristianos.
De hecho, sabemos bien, y reconocemos libremente,
que todos hemos pecado y estamos destituidos de la gloria de Dios,
y que sin arrepentimiento y regeneración siempre estaremos destituidos de ella.
También somos conscientes de que, con la debida confesión,
sumisión y obediencia sincera a las manifestaciones de Cristo, la Luz de los hombres:
"`Él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.`"^
footnote:[1 Juan 1:9]
Y: "`Si andamos en luz, como él está en luz, tenemos comunión unos con otros,
y la sangre de Jesucristo su Hijo nos limpia de todo pecado.`"^
footnote:[1 Juan 1:7]

Pero ahora, estimado lector honesto, ¿qué otra cosa, aparte de la gran ignorancia,
envidia o malevolencia, podría llevar a nuestros adversarios inferir,
que por nuestra total dependencia del Espíritu, nos consideramos infalibles?
Sin embargo,
así es como nuestras doctrinas han sido distorsionadas
por nuestros adversarios desde el mismo principio,
y actualmente nuestros oponentes siguen el mismo camino,
reprochándonos repetidamente con esta acusación. No obstante,
así como "`la vida es más que la comida, y el cuerpo que el vestido,`"^
footnote:[Lucas 12:23]
nosotros profesamos que la influencia directa del Espíritu de Cristo
es mayor que las Escrituras que testifican de Él,
así como también es mayor que la interpretación humana,
y que las prácticas que se deriven de dichas interpretaciones.
La guía original, esencial y primordial en toda la vida,
el ministerio y la adoración cristiana,
es esa revelación y poder que viene directamente
del Espíritu de Dios al corazón del hombre.

Que muchos (que se llaman a sí mismos cristianos) no estén familiarizados
con las revelaciones y movimientos del Espíritu Santo,
no es un argumento contra esta doctrina,
ya que la capacidad de cada alma creada es ser "`guiada por el Espíritu de Dios.`"^
footnote:[Romanos 8:14]
Porque "`si vivimos por el Espíritu,`" dice el apóstol,
"`andemos también por el Espíritu,`"^
footnote:[Gálatas 5:25]
aprendiendo a "`adorar a Dios en espíritu,`"^
footnote:[Filipenses 3:3]
"`orar en el Espíritu,`"^
footnote:[Judas 1:20]
"`amar en el Espíritu,`"^
footnote:[Colosenses 1:8]
"`obedecer mediante el Espíritu,`"^
footnote:[1 Pedro 1:22]
etc.

Para demostrar aún más esto, permíteme decir,
que el alma del hombre no sólo tiene la facultad de comprensión,
por la cual comúnmente piensa, une, divide, compara o forma ideas,
sino que también tiene un poder oculto de percepción interna,
o de discernir objetos espirituales mediante un sentido interno y espiritual.
Hasta que los rayos de la luz divina resplandecen sobre él,
el hombre permanece necesariamente en total inconsciencia de este sentido; sí,
así como un niño que no ha nacido permanece inconsciente de sus facultades
de la vista y el oído. Porque aunque un niño esté completamente formado
en el vientre y posea todos los órganos propios de los sentidos corporales,
todavía no tiene la capacidad para utilizarlos, ni siquiera para saber que los tiene,
hasta que es traído al entorno necesario para el uso de ellos,
compuesto de la luz y el aire de este mundo.
Entonces, repentinamente descubre los diversos sentidos y poderes naturales que,
antes de su nacimiento, no podría haber entendido ni utilizado.

De la misma manera, el hombre natural debe ser liberado de su oscuridad natural,
para ser introducido en la influencia resplandeciente
y vivificante de aquella Palabra divina,
o Espíritu, que más enfáticamente es llamada la verdadera luz y vida de los hombres.
Y así, nacida del Espíritu y llevada a este ámbito apropiado para el conocimiento divino,
el alma toma conciencia de ese sentido espiritual,
que mientras estaba en su estado natural no podía descubrir,
ni creer que le pertenecía. Esta no es una nueva facultad natural añadida,
sino un poder interno del alma recién despertado, y traído a su lugar y uso apropiado.
Las palabras son insuficientes para expresar esta sensación interna
que se experimenta en el alma bajo la influencia divina.
No puede ser comunicada con claridad al entendimiento del que no lo ha experimentado;
porque no es una imagen, sino una sensación,
que es imposible concebir de otra forma que no sea por su propia
impresión. Así de verdadera es esa expresión del apóstol:
"`Antes bien, como está escrito: Cosas que ojo no vio, ni oído oyó,
ni han subido en corazón de hombre, son las que Dios ha preparado para los que le aman.
Pero Dios nos las reveló a nosotros por el Espíritu.`"^
footnote:[1 Corintios 2:9-10]

Es sobre esta consideración que insistimos en que la luz divina es una sensación interna,
la cual no puede comunicarse adecuadamente de un hombre
a otro mediante el razonamiento o la descripción verbal.
Porque si una persona le diera la descripción más clara y viva
posible de la luz del sol a un hombre ciego de nacimiento,
sólo comunicaría una idea o noción de la luz, pero no la luz misma.
Esto podría llamarse una revelación acerca de la luz,
pero no es la revelación de la luz en sí;
la cual ningún hombre puede recibir salvo por su propia experiencia directa.
La revelación divina es algo que se abre al entendimiento por medio del Espíritu Santo,
que no está en el poder de la mente descubrirlo.
El Espíritu Santo hace esto de varias maneras, por ejemplo:
Develándose a Sí mismo por Su propia influencia (en medida) sobre el alma,
y concediéndole un sentido interno de Su presencia;
o dándole al alma una clara percepción de su propio estado y condición;
o abriendo la mente al conocimiento de la voluntad divina acerca de personas o cosas,
o a un sentido verdadero de las Escrituras;
o dándole una compresión más profunda de las doctrinas
que la que podría alcanzar sin la iluminación divina, etc.
Todo esto es una revelación verdaderamente interna y directa.
Lo que ahora comúnmente se considera la única revelación que existe,
y que siempre existirá--es decir,
la Biblia--debería llamarse más correctamente el fruto de la revelación,
que considerarla la revelación misma, porque es un registro escrito de cosas reveladas.
Estos escritos indudablemente fueron inspirados por
el Espíritu a aquellos que los recibieron directamente;
pero las muchas y diferentes interpretaciones del hombre puestas sobre ellos,
por muchas generaciones pasadas,
demuestran que estas palabras no son verdaderamente
una revelación para aquellos que las malinterpretan;
ni llegarán a serlo para el hombre hasta que conozca al santo Autor como su Intérprete.
Porque: "`Ninguna profecía de la Escritura es de interpretación privada,
porque nunca la profecía fue traída por voluntad humana,
sino que los santos hombres de Dios hablaron siendo inspirados por el Espíritu Santo.`"^
footnote:[2 Pedro 1:20-21]

Nuestro Señor les enseñó a Sus discípulos que el Espíritu de Verdad, el Consolador,
no sólo iba a recordarles lo que Él les había dicho,
mostrarles las cosas que habían de suceder y guiarlos a toda verdad, sino que también,
"`convencerá al mundo de pecado, de justicia y de juicio.`"^
footnote:[Juan 16:8]
Este Visitante divino puede aparecer en la mente del hombre con palabras o sin palabras,
mediante la sensación de compunción y remordimiento, en la agudeza de la reprensión,
o en los toques curativos de la consolación; ya sea que se manifieste como la luz,
o que derrame Su vida y amor en el corazón;
ya sea que lo penetre tan rápido como un relámpago,
o que lo establezca en una santa serenidad; ya sea que lo llene de fe,
o que lo encienda con celo;
en todas estas maneras--puesto que Él no actúa por medio de un mensajero,
sino por Su propia comunicación directa con el alma racional del
hombre--esto es correctamente llamado la revelación interna y directa.
Este Espíritu divino es la fuente viva de la verdad y la virtud en el hombre,
sin el cual todas las leyes y preceptos externos serían de muy poco provecho.
Y cuando el Espíritu de Dios, a través de la fidelidad a Él,
se incrementa y avanza sobre todo lo demás en el alma,
es hallado ser un fundamento seguro, que ni la sabiduría de los sabios,
ni el razonamiento de los que confían en sí mismos, ni la astucia de los impostores,
ni la burla del escarnecedor, ni la furia del perseguidor,
ni las puertas del Hades pueden prevalecer en Su contra.
