== Capítulo 14. El Espíritu, el Evangelio y el Reino

=== Con Respecto al Espíritu

Creemos que todos los hombres, en algún momento,
han sentido el testimonio reprobador del Espíritu de Dios en sus conciencias,
el cual les da un conocimiento convencedor de Él;
y si ellos continúan rebelándose en contra de esta luz,
progresivamente se oscurecerán con respecto a ella.
Job testifica: "`Ellos son los que, rebeldes a la luz, nunca conocieron sus caminos,
ni estuvieron en sus veredas.`"^
footnote:[Job 24:13]
Y Pablo de la misma manera dice:
"`Y como a ellos no les pareció bien tener a Dios en su conocimiento,`" (mostrando que
ellos tenían por lo menos una medida de ello) "`Dios los entregó a una mente reprobada.`"^
footnote:[Romanos 1:28 RV1602P]
Nuestro principio enseña que "`la gracia de Dios
se ha manifestado para salvación a todos los hombres,`"^
footnote:[Tito 2:11]
primero como aquello que redarguye o convence de pecado.
Por lo tanto, el Señor está a la puerta del corazón del hombre y llama para entrar,
y si el corazón se abre a Él y permanece en la capacidad que Él provee,
deseando y buscando sinceramente obedecer Sus movimientos,
el Señor aumentará gradualmente la operación de Su gracia allí,
hasta que se manifieste como el poder de Dios para salvación. Entonces, y no antes,
la mente se vuelve sensible al conocimiento salvador de este Espíritu divino.
Sin embargo, incluso antes de esto,
cuando el alma no conocía nada más que Sus simples convicciones,
no podía decirse que el hombre fuera totalmente ignorante de un sentido interno y directo
de esa gracia que es salvadora (tanto por su naturaleza como por su intención),
aunque todavía no estaba dotado con el verdadero conocimiento salvador de ella.

Siempre hemos reconocido unánimemente,
con la misma firmeza que cualquier otro profesante del cristianismo puede hacerlo,
que el evangelio vino tanto en palabra como en poder; pero no en palabras solamente,
sino también en poder, es decir, en el poder del Espíritu Santo.
Y somos conscientes de que este poder divino, del cual brotaron las palabras,
es la esencia misma del evangelio, y que las palabras son sólo la expresión externa,
o la declaración exterior, por la que se predica y se recomienda el poder.
Los apóstoles llamaron e instaron a sus oyentes a esta gracia, poder y Espíritu de Dios,
internos y esenciales, así como también a creer en la venida y proceso^
footnote:[Phipps utiliza la palabra "`proceso`" en el mismo sentido en el que
utilizó "`proceder`" más arriba--refiriéndose al curso completo del nacimiento,
vida, obediencia, sufrimientos, muerte, sepultura, resurrección y ascensión de Cristo.]
externos del Mesías que ya habían sucedido.
Ellos les enseñaron que "`Cristo fue ofrecido una
sola vez para llevar los pecados de muchos;
y que aparecería por segunda vez, sin relación con el pecado,
para salvar a los que le esperan.`"^
footnote:[Hebreos 9:28]
No entendemos esta segunda aparición de Cristo como Su venida
en juicio en el gran día de la decisión general;
porque en ese día Él determinará el estado final
de los justos y de los injustos--es decir,
no sólo para salvación,
sino también para condenación. Pero esta segunda aparición
es para salvar a los que le esperan con ese fin.
En consecuencia, el apóstol ora de esta manera por los creyentes:
"`El Señor enderece vuestros corazones en el amor de Dios,
y en la paciente expectación de Cristo.`"^
footnote:[2 Tesalonicenses 3:5 RV1602P]
Y describe a los Corintios como, "`esperando la manifestación,`" o reaparición,
"`de nuestro Señor Jesucristo.`"^
footnote:[1 Corintios 1:7]

Aunque nuestro Salvador empodera y emplea a Sus mensajeros
para declarar públicamente Su voluntad,
y llamar a las personas a la obra del arrepentimiento y regeneración,
no los comisiona para que hagan la obra por Él. No
son las palabras que predican Sus mensajeros,
ni ninguna aplicación humana de ellas,
las que realizan esta gran obra de salvación. "`Señor,`" dice el profeta,
"`tú nos depararás paz; porque también obraste en nosotros todas nuestras obras.`"^
footnote:[Isaías 26:12]
El Espíritu del Alto y Sublime es la fuente y causa
verdadera de todo bien real que es hecho,
de toda virtud verdadera que es forjada, ya sea en la iglesia en general,
o en alguno de sus miembros.
Es el Espíritu que da entendimiento, y revela el conocimiento de las cosas de Dios;^
footnote:["`Yo decía: Los días hablarán,
y la muchedumbre de años declarará sabiduría. Ciertamente espíritu hay en el hombre,
y el soplo del Omnipotente le hace que entienda.`" Job 32:7-8.
"`Antes bien, como está escrito: Cosas que ojo no vio, ni oído oyó,
ni han subido en corazón de hombre, son las que Dios ha preparado para los que le aman.
Pero Dios nos las reveló a nosotros por el Espíritu;
porque el Espíritu todo lo escudriña, aun lo profundo de Dios.
Porque ¿quién de los hombres sabe las cosas del hombre,
sino el espíritu del hombre que está en él? Así tampoco nadie conoció las cosas de Dios,
sino el Espíritu de Dios.`"
1 Corintios 2:9-11]
que vivifica y da vida,^
footnote:["`El espíritu es el que da vida; la carne para nada aprovecha.`"
Juan 6:63 "`la letra mata, mas el espíritu vivifica.`"
2 Corintios 3:6 "`Y si el Espíritu de aquel que levantó
de los muertos a Jesús mora en vosotros,
el que levantó de los muertos a Cristo Jesús vivificará también
vuestros cuerpos mortales por su Espíritu que mora en vosotros.`"
Romanos 8:11]
hace morir,^
footnote:["`Porque si vivís conforme a la carne, moriréis,
mas si por el Espíritu hacéis morir las obras de la carne, viviréis.`" Romanos 8:13, RVG]
circuncida,^
footnote:["`Circuncisión es la del corazón, en espíritu, no en letra`" Romanos 2:29]
bautiza,^
footnote:["`Por un solo Espíritu fuimos todos bautizados en un cuerpo.`"
1 Corintios 12:13]
santifica,^
footnote:["`Mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`"
1 Corintios 6:11]
regenera,^
footnote:["`El que no naciere de agua y del Espíritu, no puede entrar en el reino de Dios.
Lo que es nacido de la carne, carne es; y lo que es nacido del Espíritu, espíritu es.`"
Juan 3:5-6]
libera,^
footnote:["`Porque la ley del Espíritu de vida en Cristo
Jesús me ha librado de la ley del pecado y de la muerte.`"
Romanos 8:2]
fortalece y hace posible obedecer.^
footnote:["`Para que os dé, conforme a las riquezas de su gloria,
el ser fortalecidos con poder en el hombre interior por su Espíritu;`" Efesios 3:16]
En el Espíritu está la luz verdadera,^
footnote:["`En él estaba la vida,
y la vida era la luz de los hombres&hellip; Aquél era la Luz verdadera,
que alumbra a todo hombre que viene en este mundo.`"
Juan 1:4, 9 RV1602P "`Dios, que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de
Dios en la faz de Jesucristo`" 2 Corintios 4:6]
la vida,^
footnote:["`El espíritu vivifica.`"
2 Corintios 3:6]
el amor,^
footnote:["`Quien también nos ha declarado vuestro amor en el Espíritu.`"
Colosenses 1:8]
el esperar,^
footnote:["`Pues nosotros por el Espíritu aguardamos por fe la esperanza de la justicia.`"
Gálatas 5:5]
el caminar,^
footnote:["`Si vivimos por el Espíritu, andemos también por el Espíritu.`"
Gálatas 5:25]
la comunión^
footnote:["`Si alguna comunión del Espíritu`" Filipenses 2:1]
y unidad del evangelio.^
footnote:["`A todos se nos dio a beber de un mismo Espíritu.`"
1 Corintios 12:13]
En el Espíritu se hace la verdadera oración,^
footnote:["`El Espíritu nos ayuda en nuestra debilidad;
pues qué hemos de pedir como conviene, no lo sabemos,
pero el Espíritu mismo intercede por nosotros`" Romanos 8:26]
se abre el acceso al trono de la gracia,^
footnote:["`Orando en todo tiempo con toda oración y súplica en el Espíritu,
y velando en ello con toda perseverancia.`"
Efesios 6:18 "`Orando en el Espíritu Santo.`" Judas 20]
y se lleva a cabo la adoración aceptable.^
footnote:["`Por medio de él los unos y los otros
tenemos entrada por un mismo Espíritu al Padre.`" Efesios 2:18]
El Espíritu es la cubierta del pueblo de Dios,^
footnote:["`Ay de los hijos que se apartan, dice Jehová, para tomar consejo, y no de mí;
para cobijarse con cubierta, y no de mi espíritu.`" Isaías 30:1]
su guía,^
footnote:["`Pero cuando venga el Espíritu de verdad,
él os guiará a toda la verdad.`" Juan 16:13]
su líder,^
footnote:["`Pero si sois guiados por el Espíritu, no estáis bajo la ley.`"
Gálatas 5:18 "`Porque todos los que son guiados por el Espíritu de Dios,
éstos son hijos de Dios.`" Romanos 8:14]
su consolador,^
footnote:["`Y yo rogaré al Padre, y os dará otro Consolador,
para que esté con vosotros para siempre: el Espíritu de verdad.`"
Juan 14:16-17]
su sello,^
footnote:["`Es Dios, el cual también nos ha sellado,
y nos ha dado las arras del Espíritu en nuestros corazones.`"
2 Corintios 1:22 "`En él también vosotros, habiendo oído la palabra de verdad,
el evangelio de vuestra salvación, y habiendo creído en él,
fuisteis sellados con el Espíritu Santo de la promesa.`"
Efesios 1:13. "`No contristéis al Espíritu Santo de Dios,
por el cual estáis sellados para el día de la redención.`" Efesios 4:30]
las arras internas de una herencia eterna para ellos.
En resumen,
el Espíritu de Dios es el poder y virtud eficaz que
hace todo en la ministración del Evangelio,
de lo cual todas las Escrituras citadas aquí dan un testimonio innegable.
En todos estos aspectos, el Espíritu Santo operó poderosamente en los primeros creyentes,
y sostenemos que estas mismas operaciones espirituales
son necesarias en esta y en toda generación.

=== Con Respecto al Evangelio

Reconocemos que la palabra evangelio, en su más amplio sentido,
puede incluir tanto la historia como el misterio,
tanto el proceso externo como el interno de nuestro Salvador;
porque el evangelio no viene sólo en palabra,
sino también en poder y en el Espíritu Santo.^
footnote:[1 Tesalonicenses 1:5]
Creemos que este poder del Espíritu Santo es la parte interna y esencial,
y que las palabras son la declaración o expresión externa de dicho poder.
Admitimos que la historia merece una parte del título,
pero no debe restar valor al poder, que es la vida y realidad del evangelio,
no sea que las personas sean engañadas creyendo que el evangelio
consiste esencialmente en nada más que palabras.

Reconocemos de corazón que los apóstoles predicaron el evangelio cuando, por inspiración,
declararon el proceso histórico de Cristo;
pero no podemos conceder que esto comprendiera el todo de su evangelio.
Porque leemos en sus escritos que el evangelio es poder de Dios para salvación,
y que resplandece como una luz en el corazón para
dar el conocimiento de la gloria de Dios.
Las doctrinas del evangelio también son llamadas el evangelio,
y su predicación se denomina predicar el evangelio,
pero es evidente que ni la historia ni las doctrinas
son la esencia o la sustancia de la cosa.
Porque en Gálatas, después de que el apóstol había dicho:
"`Si alguno os predica diferente evangelio del que habéis recibido, sea anatema;`"^
footnote:[Gálatas 1:9]
luego muestra a qué se refería con el evangelio que ellos habían recibido:
"`Mas os hago saber, hermanos, que el evangelio anunciado por mí, no es según hombre;
pues yo ni lo recibí ni lo aprendí de hombre alguno,
sino por revelación de Jesucristo... Pero cuando agradó a Dios,
que me apartó desde el vientre de mi madre, y me llamó por su gracia,
revelar a su Hijo en mí, para que yo le predicase entre los gentiles,
no consulté en seguida con carne y sangre.`"^
footnote:[Gálatas 1:11-16]
El evangelio aquí descrito es, claramente,
la revelación directa del Hijo de Dios dentro de él,
y no el relato histórico o doctrinal de cosas fuera de él. De hecho,
es en contra de los que se oponen a este evangelio
interno y esencial--que no es de hombre,
ni por hombre,
sino por la revelación de Jesucristo dentro del hombre--que
el apóstol dos veces declara "`sea anatema.`"

Pablo no predicó el evangelio "`con palabras persuasivas de humana sabiduría,
sino con demostración del Espíritu y de poder,`"^
footnote:[1 Corintios 2:4]
para que la fe de sus oyentes estuviera fundada en dicho poder de Dios,
y no en las interpretaciones privadas de la sabiduría de los hombres.
Sus consiervos predicaron bajo la influencia del mismo poder divino,
el cual compungía los corazones de los que los escuchaban;
y asimismo debe ser con todos los que verdaderamente predican el evangelio.
El apóstol dijo, al dirigirse a los Corintios, que conocería "`no las palabras,
sino el poder de los que andan envanecidos.
Porque el reino de Dios no consiste en palabras, sino en poder.`"^
footnote:[1 Corintios 4:19-20]
Este poder eterno es el Espíritu del evangelio,
en quien este consiste principal y esencialmente; y por ello,
Pablo dirige a sus lectores a evitar a los que tienen "`la apariencia de piedad,
más niegan el poder de ella.`"^
footnote:[2 Timoteo 3:5 RV1602P]
Limitar todo el evangelio simplemente a los relatos históricos,
o reducirlo a nada más que a un reporte, es excluir la poderosa realidad que liberta,
como si el relato fuera el Salvador,
y el concepto la salvación. Esto no lo podemos admitir,
porque no conocemos a otro Salvador sino a Cristo, ni otra salvación sin Su poder.

Tertuliano escribió con el mismo propósito hace mil quinientos años. Él dice en su Apología,
capítulo 17: "`Ciertamente el alma fue antes que la letra,
y la Palabra antes que el libro... y si estás dispuesto a entender:
no son las palabras del libro, sino el mismo Cristo,
quien ha sido enviado al mundo y quien es el evangelio.`"
También leemos en 2 Corintios: "`Pero si nuestro evangelio está aún encubierto,
entre los que se pierden está encubierto +++[+++Literalmente,
'`en los que se pierden está encubierto;`' griego '`en tois`'];
en los cuales el dios de este siglo cegó el entendimiento de los incrédulos,
para que no les resplandezca la luz del evangelio de la gloria de Cristo,
el cual es la imagen de Dios.
Porque no nos predicamos a nosotros mismos, sino a Jesucristo como Señor,
y a nosotros como vuestros siervos por amor de Jesús. Porque Dios,
que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en la faz de Jesucristo.`"^
footnote:[2 Corintios 4:3-6]
Aquí el apóstol enseña que el evangelio que predicaban era Cristo, mostrando Su rostro,
o manifestándose a Sí mismo como la imagen de Dios en sus corazones;
y que este evangelio estaba encubierto, u oscurecido, sólo en la mente de aquellos que,
por incredulidad o infidelidad a él,
habían sido cegados por el que es llamado el dios de este mundo,
porque él es obedecido por los que caminan siguiendo la corriente de este mundo.

Juan el Evangelista afirma que Cristo, el Logos o Palabra de Dios,
es la única luz o vida verdadera de los hombres,
y la fuente de todo conocimiento verdadero de Dios que alguna vez haya
sido revelado a cualquier pueblo para la vida y felicidad de sus almas.
Esto concuerda con las profecías del pacto del evangelio: "`Daré mi ley en su mente,
y la escribiré en su corazón,`" y "`porque todos me conocerán,
desde el más pequeño de ellos hasta el más grande.`"^
footnote:[Jeremías 31:33, 34]
Esto no puede referirse al conocimiento de Cristo en la carne,
porque esa aparición fue externa,
limitada a una sola nación y de corta duración. Tampoco
puede referirse al conocimiento de las Escrituras,
porque un hombre puede conocerlas de principio a fin, creer que son verdaderas,
conformar su conducta según sus interpretaciones del significado de ellas,
y aun así no conocer al Señor. Los judíos tenían la ley,
los profetas y las Escrituras que existían en su tiempo; sin embargo, el Todopoderoso,
por la boca del mismo profeta, declara: "`Porque mi pueblo es necio, no me conocieron.`"^
footnote:[Jeremías 4:22]
Tampoco era posible que lo conocieran sin ayuda divina; por eso dice:
"`Les daré corazón para que me conozcan.`"^
footnote:[Jeremías 24:7]
Y en Ezequiel: "`Os daré corazón nuevo,
y pondré espíritu nuevo dentro de vosotros...pondré dentro de vosotros mi Espíritu.`"^
footnote:[Ezequiel 36:26-27]

Por lo tanto,
el evangelio de Dios debe ser recibido y conocido por la
escritura interna de la Palabra divina en el corazón,
que pone la ley de la luz y de la vida dentro del hombre.
De hecho, este es "`el evangelio del reino de Dios,`"^
footnote:[Marcos 1:14]
Cuyo reino comienza como un grano de mostaza, una perla, una pizca de levadura,
o una piedra pequeña "`cortada de la montaña,
no con manos,`" pero que se convierte en una gran montaña,
hace pedazos y consume todos los otros reinos, y llena la tierra del corazón del hombre.
Este reino, dice Jesús, "`no vendrá con observación; ni dirán: Helo aquí, o helo allí;
porque, he aquí, el reino de Dios dentro de vosotros está.`"^
footnote:[Lucas 17:21 RV1602P]
Algunos, para favorecer su propósito, deciden leer así estas últimas palabras,
"`el reino de Dios está entre vosotros.`"
Pero leerlo de esta manera destruye el contraste
que nuestro Señor evidentemente quería hacer,
quien en ese momento estaba respondiendo una pregunta de los fariseos
acerca de la expectativa que tenían de un reino externo.
El Señor les informa que el reino de Dios es un reino interno,
y aquí les muestra la diferencia entre una forma externa
y visible (que los hombres podrían señalar con su '`helo
aquí`' y '`helo allí`') y Su propio dominio interno y espiritual.
Además, la palabra en el griego original es
// lint-disable invalid-characters
"`ἐντός,`" que claramente significa dentro o adentro, y no "`εν`"
que puede ser interpretado como en o en medio.

=== Con Respecto al Reino

Si alguno pregunta: '`¿Qué es el reino de los cielos, o de Dios?`' Respondo:
Aunque Él es, verdaderamente, el Soberano Todopoderoso del universo entero, Su reino es,
más particularmente,
aquel en el que Él gobierna tan completamente como
para ser siempre alegre y perfectamente obedecido;
donde es el único autor de todo lo que es hecho;
donde es glorificado en todo lo que se hace,
y donde comunica Su propia gloria y felicidad sin mezcla.
Los hombres no pueden entrar a este reino, ni siquiera verlo,
excepto a través del nuevo nacimiento del Espíritu Santo,
por el cual el alma experimenta un nacimiento en él--una libertad del
poder de las tinieblas y un traslado al reino del amado Hijo de Dios.
Sólo a través de esto el espíritu del hombre entra en el reino,
y por medio de la fidelidad,
es capacitado para avanzar en él mientras todavía está en el cuerpo.
Este reino no consiste en lugares físicos,
tampoco en ningún '`aquí o allí,`' y por lo tanto,
es vano dirigir a los hombres a él con "`helo aquí,`" o "`helo allí.`" Mas bien,
se encuentra en un Espíritu infinito y celestial,
en una vida y naturaleza en la que nada impuro puede vivir o entrar.
Es el dominio interno, o poder gobernante del Espíritu Santo en hombres y ángeles.
Es esa influencia pura que fluye de la gloria del Altísimo, la cual,
al entrar a las almas santas, las hace amigas de Dios.
En resumen, el reino de Dios es el dominio de la luz y la vida del Espíritu de Dios.
Cualquiera que viva bajo la palpable influencia y gobierno de esto, vive en el reino.
Este es el reino de los santos militantes en la tierra,
y de los santos triunfantes en el cielo,
que sólo experimentan los santificados en Cristo Jesús;
en parte mientras están en este mundo, y en plenitud en el mundo por venir.
