== Capítulo 2. La Criatura Sujeta a Vanidad

Las Sagradas Escrituras muestran que todos somos afectados naturalmente por la
transgresión de nuestros primeros padres mucho antes de nuestras propias ofensas.
"`Por tanto, como el pecado entró en el mundo por un hombre, y por el pecado la muerte,
así la muerte pasó a todos los hombres, por cuanto todos pecaron.`"^
footnote:[Romanos 5:12]
Esto no debe entenderse sólo con respecto a la muerte del cuerpo,
porque en efecto todos vienen al mundo a la imagen del hombre terrenal,
sin la vivificante y sensible influencia de la vida divina.

Y aunque esto es verdad,
no se desprende de ello la necesidad de concluir que todos venimos
al mundo siendo justamente objetos de la venganza divina,
por causa de una ofensa cometida por nuestros antepasados
antes de que viniéramos al mundo.
¿Con qué propiedad puede un niño incapaz de cometer
algún delito ser tratado como un transgresor?
La Escritura nos asegura positivamente que "`el camino del Señor es recto,`"^
footnote:[Ezequiel 18:25, 29]
"`el alma que pecare, esa morirá,`" y "`el hijo no llevará el pecado del padre,`"^
footnote:[Ezequiel 18:20] etc.
Todo lo que la posteridad de Adán perdió a través de él, eso y más lo ganan en Cristo,
y sin ninguna duda, Su misericordia y bondad, y la extensión de Su propiciación,
son tan aplicables a los niños que no han pecado personalmente,
como a los adultos que sí.

Las Escrituras muestran que el alma inmortal y racional del hombre, en cada individuo,
es la fabricación inmediata de su Creador, porque el profeta Zacarías,
hablando de los grandes hechos de Dios en la creación,
afirma que Dios "`forma el espíritu del hombre dentro de él.`"^
footnote:[Zacarías 12:1]
Y en Eclesiastés 12:7, con respecto a la muerte del cuerpo leemos,
"`el polvo vuelva a la tierra, como era, y el espíritu vuelva a Dios que lo dio.`"
Por lo tanto, el alma misma^
footnote:[Es decir, como un vaso creado para una naturaleza.]
al recibir su existencia directamente de la perfección de la pureza inmutable,
no puede tener una impureza o corrupción original en ella.
Sin embargo, al ser inmediatamente e íntimamente conectada con un cuerpo natural,
e incapaz de resistir las pasiones de la naturaleza carnal,
el alma es susceptible a la influencia de estas pasiones,
al punto de participar con ellas en sus indulgencias sensuales.
En este estado los descendientes de Adán vienen al mundo,
destituidos de aquella vida divina de la cual Adán cayó.

Cualesquiera que sean las peculiaridades que resulten
de la caída del primer hombre y de la primera mujer,
esto es un hecho--que sus descendientes no vienen al mundo en el
mismo estado de gloria en el que ellos fueron creados al principio.
Los que han estado a cargo del cuidado de niños,
no pueden evitar notar que las primeras acciones voluntarias y visibles en ellos,
evidentemente provienen de los poderes del deseo carnal y de la pasión,
y que estos son propensos a aumentar y a predominar en ellos a medida que crecen.
De hecho,
¡cuánto esfuerzo y dedicación se requieren para mantener a los niños fuera del
desenfreno y de la falta de sobriedad mientras avanzan hacia la juventud! ¡Con
qué avidez permiten que deseos desordenados gobiernen sus facultades racionales!
Y ¡qué gran esmero es necesario (a través de una cuidadosa y virtuosa educación),
para meramente regular o mitigar estas tendencias naturales!
Sin duda,
ellas nunca podrían ser realmente sometidas y gobernadas
sin la operación de un principio superior.

El Creador consideró conveniente que mediante Su poder el alma fuera unida al cuerpo,
antes de que recibiera algún conocimiento.
"`Porque,`" dice el apóstol, "`la criatura fue sujeta a vanidad, no de su voluntad,
sino por causa de aquél que la sujetó en esperanza,
porque también la misma criatura será librada de la servidumbre de corrupción,
a la libertad gloriosa de los hijos de Dios.`"^
footnote:[Romanos 8:20-21]
Aquí el alma racional es denominada con el término
"`criatura,`" que apropiadamente se refiere al hombre.
Aquí radica la verdadera distinción entre la especie
humana y las criaturas de clases inferiores.

El alma es una sustancia indivisible e inmaterial que no puede ser generada por el hombre,
y por lo tanto, no se transmite con el cuerpo de los padres a los hijos.
El alma del niño nunca estuvo en el padre, por lo tanto,
nunca pudo pecar en él ni derivar culpa por su transgresión.
Tampoco la culpa puede recaer sobre el alma del niño simplemente
por estar unida a un cuerpo físico que vino de su padre,
porque dicha unión es un acto de su Creador.
No es congruente con la justicia y la misericordia de Dios
considerar a un niño culpable o digno de castigo,
simplemente por una ofensa cometida por sus padres
antes de que pudiera tener conciencia de sí mismo.
Por lo tanto, ningún infante nace con culpa sobre su cabeza,
aunque carece de vida espiritual.^
footnote:[Nota de Joseph Phipps--Con respecto a los pequeños
niños que parten antes de que personalmente hayan pecado,
no pueden ser culpados con equidad, y con una confianza justa,
pueden resignarse como perfectamente salvos en los
brazos de su Salvador quien declaró que,
"`De los tales es el Reino de los Cielos.`"]

Sin embargo,
además de nuestra separación natural e ignorancia
de la vida interna de Dios en nuestro estado caído,
hay que reconocer que todos los que han llegado al grado de madurez
en el que son capaces de recibir un entendimiento correcto y distinguir
las advertencias internas de la Verdad en sus conciencias,
han incrementado y fortalecido sobre sí mismos los
lazos de corrupción en diferentes medidas,
por medio de la indulgencia repetida y a menudo habitual de la parte carnal,
al actuar en contra del sentido del deber que recibieron.
Estos han entrado más profundamente a la oscura región de
sombra de muerte a través de sus propios delitos y pecados.
Y así, "`todos pecaron, y están destituidos de la gloria de Dios.`"^
footnote:[Romanos 3:23]
