== Capítulo 4. La Revelación de Cristo en el Corazón

Todas las formas y las ceremonias exteriores,
sin importar cuán erradamente sean estimadas y celebradas en la humanidad,
son sólo señales externas y visibles,
completamente ineficaces para lograr cualquier cambio o reforma real de la persona.
La parte vital de la religión y el deber del hombre reside principalmente,
en una atención correcta y obediencia fiel a la manifestación
del Espíritu de Cristo en el corazón y en la conciencia.
Aquel que presta la debida y constante atención a esto,
en su medida es un seguidor de Cristo,
y en cierto grado tiene la realidad del cristianismo en él--independientemente
de su sistema de profesión religiosa o su ubicación en el mundo.
Porque, ¿quién es siervo de Cristo, sino aquel que lo obedece voluntariamente?
Y si el que actúa según los mandamientos verbales de Cristo es un seguidor,
¿no es también un seguidor él que carece del conocimiento de estos preceptos escritos,
pero que sigue voluntariamente las directrices de Su Espíritu?

De este Espíritu participaron en algún grado los que entre
los gentiles eran verdaderamente piadosos y religiosos,
"`Porque,`" dicen las Sagradas Escrituras, "`cuando los gentiles que no tienen ley,
hacen por naturaleza lo que es de la ley, éstos, aunque no tengan ley,
son ley para sí mismos, mostrando la obra de la ley escrita en sus corazones,
dando testimonio su conciencia, y acusándoles o defendiéndoles sus razonamientos.`"^
footnote:[Romanos 2:14-15]
Me parece que aquí las palabras "`por naturaleza,`" no deben entenderse
como si el apóstol pretendiera que los gentiles habían llegado
a ser piadosos por alguna bondad en su naturaleza caída,
que debe ser la misma que la del resto de los hombres.
El contexto muestra que él estaba haciendo una distinción entre aquellos
que gozaban del ministerio de la ley Mosaica y aquellos que no.
Él usa la expresión "`por naturaleza`" en el mismo sentido que si hubiera
dicho "`sin educación bajo la ley,`" y procede a demostrar que,
a pesar de que ellos no tenían la ley, practicaban la sustancia de ella.
Esto de ninguna manera implica que sus corazones fueran su ley,
sino más bien (como el apóstol lo explica) que la
obra de la ley estaba escrita en sus corazones.
Aunque estaban sin la ley de Moisés, no estaban sin la ley de Dios.
Porque al recibir, retener y someterse a las impresiones divinas en sus conciencias,
estaban bajo la ley de Cristo,
o sujetos a la manifestación de Su Espíritu en sus corazones;
y en proporción a su obediencia fueron partícipes
de la naturaleza del Espíritu Santo dentro de ellos.

Es por la operación interna de esta naturaleza que llegaron a ser reformados en sus
corazones y corregidos en su vida y práctica (en cualquier medida que alcanzaran),
o como el texto lo tiene, que fueron capacitados para "`hacer lo que es de la ley.`"
Su propia naturaleza como hombres, originalmente desordenada y depravada,
nunca habría podido llevarlos a esto, ni facultarlos para hacerlo,
porque es propensa al mal y la reforma y religión
verdaderas no provienen de ese terreno corrupto.
De hecho, todo lo que es bueno, puro,
justo y verdadero no viene de nada en la naturaleza del hombre, sino por gracia.
Estos son los frutos de aquella buena Semilla sembrada universalmente
en cada corazón por el gran y buen Sembrador,
que arroja semillas en todo tipo de tierra con ese fin.
El hombre sólo habría podido continuar en el aumento de la corrupción,
la impiedad y la miseria,
si no fuera por la luz y poder comunicados por este interno
Espíritu Santo--como se muestra muy evidentemente por la
conducta de los que no le prestan atención. Por lo tanto,
no fue al seguir su propia naturaleza,
que los hombres sensibles y piadosos entre los gentiles
pudieron realizar las cosas contenidas en la ley Mosaica,
sino por la obediencia a la ley interna de la naturaleza
divina escrita en el corazón. De esta manera,
en sus medidas,
ellos pusieron en evidencia la eficaz operación y
autoridad del Legislador divino dentro de ellos.

Por lo tanto,
no se puede decir que los Gentiles que participaron de la ley escrita en el corazón,
han sido excluidos de tener alguna parte en el evangelio.
Porque el evangelio, tomado en toda su extensión,
es la revelación del amor y la misericordia,
y la oferta y operación de la gracia de Dios por medio de Cristo al hombre
caído en su estado natural y corrupto con el fin de lograr su restauración
y salvación. El evangelio no está limitado a las meras nuevas.
Además de las palabras,
va mucho más profundo y consiste esencialmente en lo que ellas declaran, a saber,
el poder de Dios administrado para la salvación del alma.
Al recibir y rendirse a este poder,
la venida física de Cristo se hace verdadera y plenamente efectiva en cada individuo.
Aquellos que creen en Él y le obedecen en Sus manifestaciones internas y espirituales
(por las cuales el evangelio "`se predica en toda criatura que está debajo del cielo`"^
footnote:[Colosenses 1:23, Traducción Literal]),
pueden llegar a ser partícipes de Su vida y ser salvados
por Él de la segunda muerte de miseria eterna,
aunque por providencia divina estén incapacitados
para conocer la historia externa de Su encarnación,
muerte, resurrección, etc.

Que los gentiles piadosos y devotos fueron aceptados por Dios,
aparece en el caso de Cornelio,
porque nosotros hallamos que incluso antes de recibir el cristianismo histórico y verbal,
su sincera devoción y reverencia a su Creador,
y sus obras de caridad hacia los pobres "`subieron para memoria delante de Dios.`"^
footnote:[Hechos 10:4]
Es más,
el Señor le enseñó a Pedro (verso 15) que a los Gentiles que Él había limpiado así,
no los llamara comunes o más inmundos que los creyentes judíos,
y le hizo comprender claramente "`que Dios no hace acepción de personas,
sino que en toda nación se agrada del que le teme y hace justicia.`"^
footnote:[Hechos 10:34-35]
Por lo tanto,
es manifiesto que aquellos que obedecen conscientemente
las manifestaciones espirituales de Cristo en ellos,
son internamente (aunque no necesariamente con una
profesión externa) sus discípulos y sus seguidores,
y creen verdaderamente en Él hasta donde Él les es revelado internamente;
porque la obediencia es la prueba segura de una fe correcta.

Con respecto a los que no tienen la oportunidad de escuchar la historia del cristianismo,
en cualquier parte del globo, por causa de obstáculos ineludibles,
no me cabe duda de que son aceptados en su obediencia a
la aparición espiritual de Cristo en sus corazones y,
por lo tanto, participan de los beneficios de Su muerte.
¿Por qué no pueden ser tan capaces de recibir las ventajas del sacrificio de Cristo,
como son capaces de recibir las desventajas de la caída de Adán,
viendo que desconocen igualmente la historia de ambos?
Pero ciertamente,
aquellos a quienes las Sagradas Escrituras son por providencia divina comunicadas,
están bajo doble obligación,
puesto que son favorecidos con la ventaja adicional del
relato histórico y la revelación escrita de Dios al hombre.
Y seguramente esto contribuirá a su mayor condenación si no creen para obedecer.
Porque los que mantienen la parte externa y no experimentan la interna,
son creyentes imperfectos, superficiales e ineficaces,
independientemente de cuán fuerte y estrictamente profesen la letra escrita.
Estos son cristianos de nombre, pero no de hecho y en verdad.
Es esencial para nosotros que tenemos las Escrituras, creer tanto en la venida externa,
como en el ministerio interno de nuestro Salvador, rindiendo todo a Él,
y confiando en Él con aquella "`fe de la operación de Dios`"^
footnote:[Colosenses 2:12 (RV 1602 Purificada)]
que obra por amor la purificación del corazón y es la fe salvadora del evangelio.

Un Cristianismo completo tiene tanto un interior
como un exterior--una profesión o apariencia corporal,
y una vida y virtud que son como un alma para ese cuerpo.
Los que están en posesión de ambos son cristianos completos.
Los que tienen la parte interna sin la externa, aunque incompletos en este respecto,
ciertamente, ante los ojos de la perfecta equidad,
serán preferidos a los que tienen la parte externa sin la interna.
Y de hecho,
en el caso de aquellos que tienen la historia y profesan la religión cristiana,
pero caminan en contra de sus requerimientos,
creo que sería mejor para ellos que al final cambiaran sus condiciones
por las de aquellos Gentiles sensibles que no tenían las Escrituras.
¡Qué aquellos que son como éstos consideren debidamente
el siguiente texto! "`De cierto os digo,
que ni aun en Israel he hallado tanta fe.
Y os digo que vendrán muchos del oriente y del occidente,
y se sentarán con Abraham e Isaac y Jacob en el reino de los cielos;
más los hijos del reino serán echados a las tinieblas de afuera;
allí será el lloro y el crujir de dientes.`"^
footnote:[Mateos 8:10-12]

El verdadero Cristianismo no consiste en una profesión exterior
de artículos o credos formulados por el hombre,
tampoco en la práctica de señales y ceremonias,
no importa con cuánta pompa y celo se expongan,
o cualquier significado que les puedan atribuir sus partidarios.
La forma y la profesión no hacen un cristiano verdadero,
sino el revestirse de una nueva naturaleza.
"`Pero los que son de Cristo han crucificado la carne con sus pasiones y deseos`"^
footnote:[Gálatas 5:24]
y, "`Si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron;
he aquí todas son hechas nuevas.
Y todo esto proviene de Dios.`"^
footnote:[2 Corintios 5:17-18]
La necesidad de regeneración verdadera,
el poder con el que se efectúa y la cooperación de Dios y el hombre en ella,
están todos incluidos en este texto: "`Porque si viviereis según la carne, moriréis;
más si por el Espíritu mortificareis las obras de la carne,
viviréis. Porque todos los que son guiados por el Espíritu de Dios,
los tales son hijos de Dios.`"^
footnote:[Romanos 8:13-14 RV1602P]

Este nuevo nacimiento no es producido en el hombre sin que lo perciba.
El nuevo hombre es "`renovado en conocimiento,`"^
footnote:[Colosenses 3:10 RV1602P]
con una experiencia certera y sensible.
El alma en la que esto está tomando lugar tiene una
sensación interna de ello durante todo el progreso,
y debe mantenerle un ojo firme para que pueda seguir avanzando.
"`Nosotros todos,`" dice el apóstol "`mirando a cara
descubierta como en un espejo la gloria del Señor,
somos transformados de gloria en gloria en la misma imagen,
como por el Espíritu del Señor.`"^
footnote:[2 Corintios 3:18]
El hombre cae y crece en el pecado al mirar la engañosa belleza de la tentación,
pero manteniendo un ojo firme internamente en Cristo en el espíritu,
con una humilde entrega a Él y un ferviente deseo por Él,
el hombre consigue su preservación y gradualmente avanza de un grado de gracia a otro.
Esto continúa hasta que realmente experimenta una renovación de
la semejanza divina en su alma y un traslado interno del pecado,
la oscuridad y la muerte a la luz divina, la vida y la santidad, y por lo tanto,
un cambio de la ansiedad y la miseria a la paz y la felicidad.

El hombre natural puede embellecerse y adornarse
a sí mismo con una variedad de literatura,
artes y educación, pero aún en sus mejores logros,
todavía no es más que el hombre natural--uno del que el apóstol
declara que "`no percibe las cosas que son del Espíritu de Dios,
y no las puede entender.`"^
footnote:[1 Corintios 2:14]
Esta es la condición natural de todos los hombres
antes de que comience la obra de renovación en ellos.
Por lo tanto,
viendo que todos están en necesidad de la gracia divina para llevar a cabo esto,
y sabiendo que "`Dios quiere que todos los hombres
sean salvos y vengan al conocimiento de la verdad,`"^
footnote:[1 Timoteo 2:4]
es por eso que "`la gracia de Dios se ha manifestado para salvación a todos los hombres,
enseñándonos`"--por sus convicciones--"`que,
renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria,
justa y piadosamente.`"^
footnote:[Tito 2:11]
Así, "`El Dios de dioses, Jehová, ha hablado, y convocado la tierra,
desde el nacimiento del sol hasta donde se pone.`"^
footnote:[Salmo 50:1]
De hecho,
los escritos de los profetas y de los apóstoles nunca se han extendido
tan universalmente en la humanidad como la gracia y poder de Dios.

Cristo fue dado "`por pacto del pueblo,
por luz de las gentes`" ... y como "`la salvación de Dios hasta los fines de la tierra.`"^
footnote:[Isaías 42:6, 49:6]
No solamente ofrece Su gracia universal e individualmente,
sino que incluso Él "`aguardará para otorgarnos su gracia.`"^
footnote:[Isaías 30:18 RV1977]
"`He aquí,`" dice Él, "`yo estoy a la puerta y llamo;
si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.`"^
footnote:[Apocalipsis 3:20]
Cuando "`le dijo Judas (no el Iscariote): Señor, ¿cómo es que te manifestarás a nosotros,
y no al mundo?
Respondió Jesús y le dijo: El que me ama, mi palabra guardará; y mi Padre le amará,
y vendremos a él, y haremos morada con él.`"^
footnote:[Juan 14:22-23]
Quien proclama esto es Cristo en el Espíritu, "`el que tiene oídos para oír, oiga.`"^
footnote:[Marcos 4:9, 23; 7:16, etc.]

Pregunta: Pero si el hombre en su estado caído está muerto ¿cómo pueden oír los muertos?

Respuesta: Cuando el Salvador clamó: "`¡Lázaro, ven fuera!`"^
footnote:[Juan 11:43]
el hombre muerto fue vivificado e inmediatamente obedeció.
La voz de Aquel que es un "`Espíritu vivificante`"^
footnote:[1 Corintios 15:45]
tiene poder vivificador.
"`Viene la hora, y ahora es, cuando los muertos oirán la voz del Hijo de Dios;
y los que la oyeren vivirán.`"^
footnote:[Juan 5:25]

Pregunta: ¿Qué quiere decir que Él está a la puerta?

Respuesta: Su maravillosa condescendencia, paciencia y longanimidad,
al esperar en el alma del hombre para entrar.
Cristo desea que todos los hombres sean persuadidos
a abrir sus corazones voluntariamente a su Redentor.

Pregunta: ¿Cómo Cristo en el Espíritu toca a la puerta y llama?

Respuesta: Al influenciar el alma en sus temporadas de quietud y tranquilidad,
despertando inclinaciones y deseos hacia lo que es bueno y verdadero; y en otros tiempos,
al afligirla con dolorosas sensaciones de culpa y
remordimiento por sus pecaminosos deseos y prácticas.

Pregunta: ¿Cómo puede el hombre abrirle a Él y recibirlo?

Respuesta:
Al renunciar a su amor a sí mismo y a las propensiones y deseos de sus sentidos carnales,
y humildemente adherirse a la voz o manifestaciones presentes del Espíritu.

Pregunta: ¿Cómo entra el Señor en el hombre y come con él,
y lo hace participar de Su cena?

Respuesta: Cuando el alma recibe al Espíritu de Cristo en fe,
en amor y en debida sumisión,
éste procede gradualmente a liberarla de la esclavitud e influencia de la corrupción,
porque "`donde está el Espíritu del Señor,`"--en
experiencia y posesión--"`allí hay libertad.`"^
footnote:[2 Corintios 3:17]
Y cuando Cristo ha traído al alma a un grado apropiado de purificación,
Él derrama el consuelo de su amor en ella y la hace
partícipe de la comunión de los santos,
la cual es interior y espiritual.
Esta es la verdadera cena del Señor. Él que participa de esto,
discierne y prueba el cuerpo espiritual del Señor,
y lo experimenta como verdadera comida y Su sangre como verdadera bebida.
