== Capítulo 5. El Nacimiento de la Vida Divina en el Alma

La humanidad no ha sido dejada en manos de Satanás,
tampoco ha sido entregada a sus propias concupiscencias,
ni ha de vivir sin Dios en el mundo.
Se ha allanado un camino.
Se ha proporcionado un medio.
Dios ha sembrado un testigo divino en el corazón de cada individuo,
el cual verdaderamente manifestará lo correcto y lo incorrecto
en las conciencias de aquellos que fielmente le presten atención,
proporcionándoles luz y poder para hacerlos libres
de las neblinas del prejuicio y de las mentiras,
convirtiéndose para ellos en un guía seguro,
y en el apoyo perfecto en los caminos de justicia y verdad.
¿Qué otro instructor es igual a este testigo tan íntimo?
¡Un centinela tan cercano, tan constante, tan fiel, tan infalible!
En efecto, este es el gran privilegio de cada hombre en el nuevo pacto:
escuchar el evangelio predicado día a día en su propio corazón, sin dinero y sin precio,
y sin embargo, con certeza.

Ahora bien, ¿acaso es razonable concluir que este discernidor bueno,
verdadero y penetrante sea algo menos que divino?
¿Puede alguna persona, después de una seria consideración,
imaginar que esto sea la naturaleza del hombre caído? ¿Es posible que una naturaleza
tan corrupta y nublada distinga entre el bien y el mal tan clara e instantáneamente?
Y el corazón del hombre (que en las inspiradas Escrituras
es declarado ser "`engañoso más que todas las cosas y perverso`"^
footnote:[Jeremías 17:9]) ¿se reprobaría a sí mismo tan fielmente?
Aquello que se deleita en su propia indulgencia y que no tolera restricción,
¿actuaría como un control diario en contra de sus propias inclinaciones?
¿Es propiedad del mal hacer el bien?

Ahora consideremos; lo que es natural, guía según lo natural,
y lo que es espiritual según el Espíritu.
Estas dos cosas se distinguen en la Escritura por los términos carne y Espíritu,
y se dice que verdaderamente luchan entre sí dentro del hombre.
Tal como lucha el pecado contra el Espíritu para destruir el alma,
así lucha el Espíritu contra el pecado para salvarla.
Ahora,
ustedes que desprecian e injurian este testigo interno
en lugar de recibirlo con humildad y agradecimiento,
permítanme hacerles la siguiente pregunta:
Mientras confiesan que este testigo distingue entre
lo bueno y lo malo en sus propios pechos,
por medio de su aprobación de lo primero y su condenación de lo último,
¿pueden reconocer que es infaliblemente bueno y al
mismo tiempo atribuírselo a ustedes mismos?
"`Yo sé,`" dice Pablo, "`que en mí, esto es,
en mi carne,`" o perteneciente a mi naturaleza, "`no mora el bien.`"^
footnote:[Romanos 7:18]
¿Está la naturaleza de ustedes en una mejor condición que en la
que estaba la de él? ¿Hay alguna cosa buena en la de ustedes,
aunque no había ninguna en la de él? Él confesó que no tenía nada bueno como hombre.
Supongo que ustedes no tienen más de lo que él tenía. ¿De dónde, pues,
proviene este rápido y justo Juez que aparece en sus conciencias?
No dirán que es de Satanás; entonces, debe ser del hombre o de Dios;
pero por las razones arriba mencionadas no puede ser del hombre, por lo tanto,
debe ser de Dios.
Maravillosa es la misericordia y grande la ventaja para cada hombre, que Dios mismo,
según las Escrituras,
consienta de esta forma ser el Maestro de Su pueblo a través
de la manifestación de Su Espíritu en cada corazón. En verdad,
este testigo interior debe ser aceptado y guardado
con la mayor reverencia y agradecimiento.

La operación e incremento de este Espíritu vivo se
convierten en una nueva vida en y para el alma obediente,
vivificándola y refrescándola con una experiencia de amor, fuerza y consuelo divinos.
Esta vida, engendrada y dada a luz por el Espíritu Santo en la mente dispuesta,
es llamada el _nacimiento_ del Espíritu;
y viendo que nuestros primeros padres fueron favorecidos con este
nacimiento espiritual inmediatamente después de ser creados,
pero que lo perdieron por desobediencia,
a la reaparición de este nacimiento se le ha denominado _regeneración_ y _renovación,_
o renacimiento de la vida divina en el hombre.
Puesto que somos herederos de la muerte espiritual en Adán,
o en el estado y naturaleza caídos,
nacemos de nuevo a la vida en Jesucristo sólo por el poder y virtud de Su Espíritu Santo,
quien es la resurrección y la vida.

Cada poder reproductor produce su propia semejanza;
el espíritu maligno produce un nacimiento maligno,
y el buen espíritu produce un nacimiento que corresponde a su bondad.
Y así como todo nacimiento natural permite un crecimiento,
también lo hace este nacimiento espiritual en el alma.
Nuestro Salvador representa su progreso gradual con las
analogías del crecimiento de la semilla de mostaza,
el proceso de la levadura, el agua viva que salta para vida eterna, etc.
Los apóstoles Pedro y Juan también muestran que hay
varios grados de experiencia entre los creyentes,
usando las metáforas de bebes recién nacidos, niños, jóvenes y padres; y ciertamente,
incluso el estado de padres permite un crecimiento continuo,
de lo que el mismo Pablo dio testimonio.
Porque aunque Pablo afirmó que la ley del Espíritu de vida en Cristo Jesús,
en verdad lo había hecho libre de la ley del pecado y de la muerte,
todavía era consciente de que aún tenía delante de sí grados más altos de crecimiento,
y después de treinta años en el apostolado reconoce lo siguiente:
"`No que lo haya alcanzado ya, ni que ya sea perfecto; sino que prosigo,
por ver si logro asir aquello para lo cual fui también asido por Cristo Jesús. Hermanos,
yo mismo no pretendo haberlo ya alcanzado; pero una cosa hago:
olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante,
prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús.`"^
footnote:[Filipenses 2:12-14]

Aquellos que consideran que la necesidad de que el hombre sea regenerado,
transformado y guiado por el Espíritu de su Creador, es un insulto a la razón humana,
deshonran grandemente la Suprema sabiduría, bondad y poder.
La dignidad de la naturaleza humana no consiste en absoluto en la autosuficiencia.
El más excelso de los seres angelicales no desea
ni actúa de forma independiente a su Creador;
mucho menos el hombre,
que incluso en su pureza primitiva fue "`hecho menor que los ángeles.`"^
footnote:[Salmo 8:5]
En efecto, el hombre está en constante necesidad de la ayuda divina,
y su verdadera dignidad consiste en ser capaz de _recibir conscientemente_ esta asistencia,
y de este modo tener acceso a una bendita unión y
comunión con su Hacedor y preservación en ellas.
¡No es un menosprecio para un inferior ser dirigido y guiado por un Ser superior;
especialmente por el Supremo Señor y único Autor de toda existencia!
La criatura dotada con Su Espíritu, en cualquier grado,
es levantada por encima del más alto nivel de su propia naturaleza;
y cuánto más revestida es de Él, más dignificada y exaltada es.
En verdad,
sólo cuando el Sol de Justicia emite Sus rayos vivificadores sobre el espíritu del hombre,
el pobre gusano es capaz de tomar alas y ascender por encima
de sus límites terrenales hacia las regiones celestiales.
