== Capítulo 5. El Nacimiento de la Vida Divina en el Alma

La humanidad no fue dejada en manos de Satanás,
tampoco fue entregada a sus propias concupiscencias, ni a vivir sin Dios en el mundo.
Un camino es establecido.
Un medio es proporcionado.
Dios ha sembrado un testigo divino en el corazón de cada individuo,
el cual verdaderamente manifiesta lo correcto y lo incorrecto en
las conciencias de aquellos que fielmente le prestan atención,
proporcionándoles luz y poder para libertarlos de
las neblinas del prejuicio y de las mentiras,
y convirtiéndose en un conductor seguro para ellos y en
el apoyo perfecto en los caminos de justicia y verdad.
¿Qué otro instructor es igual a este testigo tan íntimo?
¡Un monitor tan cercano, tan constante, tan fiel, tan infalible!
Verdaderamente,
este es el gran privilegio de cada hombre en el nuevo pacto--escuchar
el evangelio predicado día a día en su propio corazón,
sin dinero y sin precio, pero con certeza.

Ahora bien ¿Acaso es razonable concluir que este discernidor bueno,
verdadero y penetrante sea algo menos que divino?
¿Puede alguna persona, después de una seria consideración,
imaginar que esto es de la naturaleza del hombre caído? ¿Es posible que una naturaleza
tan corrupta y nublada distinga entre el bien y el mal tan clara e instantáneamente?
Y,
¿podrá el corazón del hombre (que en las inspiradas Escrituras
es declarado ser "`engañoso más que todas las cosas y perverso`"^
footnote:[Jeremías 17:9]) tan fielmente reprobarse a sí mismo?
¿Podrá aquello que se deleita en su propia indulgencia y que no tolera restricción,
actuar como un control diario en contra de sus propias inclinaciones?
¿Es propiedad del mal hacer el bien?

Ahora consideremos: Aquello que es natural guía de acuerdo a lo natural,
y aquello que es espiritual según el Espíritu.
Estas dos cosas se distinguen en la Escritura por los términos carne y Espíritu,
y se dice verdaderamente que luchan entre sí dentro del hombre.
Tal como el pecado lucha contra el Espíritu para destruir el alma,
así el Espíritu lucha contra el pecado para salvarla.
Ahora,
ustedes que desprecian e injurian este testigo interno
en lugar de recibirlo con humildad y agradecimiento,
permítanme hacerles la siguiente pregunta:
Mientras que confiesan que este testigo distingue
entre lo bueno y lo malo dentro de ustedes,
por medio de su aprobación de lo primero y su condenación de lo último,
¿pueden reconocer que es infaliblemente bueno y al
mismo tiempo atribuírselo a ustedes mismos?
"`Yo sé`" dice Pablo, "`que en mí, esto es,
en mi carne,`" o perteneciente a mi naturaleza, "`no mora el bien.`"^
footnote:[Romanos 7:18]
¿Está la naturaleza de ustedes en una mejor condición que en la
que estaba la de él? ¿Hay alguna cosa buena en la de ustedes,
a pesar de que no había ninguna en la de él? Él confesó
que no tenía nada bueno como hombre.
Supongo que ustedes no tienen más de lo que él tenía. ¿De dónde, pues,
proviene este eficaz y justo Juez que aparece en sus conciencias?
Ustedes no dirán que es de Satanás, entonces, debe ser o del hombre o de Dios;
pero por las razones arriba mencionadas no puede ser del hombre, por lo tanto,
debe ser de Dios.
Maravillosa es la misericordia y grande la ventaja dada a cada hombre, que Dios mismo,
según las Escrituras,
de esta forma condesciende para ser el Maestro de Su pueblo a través
de la manifestación de Su Espíritu en cada corazón. Ciertamente,
este testigo interior debe ser aceptado y guardado con la mayor reverencia y agradecimiento.

La operación e incremento de este Espíritu vivo se
convierten en una nueva vida en y para el alma obediente,
vivificándola y refrescándola con una experiencia de divino amor, fuerza y consuelo.
Esta vida, engendrada y dada a luz por el Espíritu Santo en la mente dispuesta,
es llamada el _nacimiento_ del Espíritu;
y viendo que nuestros primeros padres inmediatamente después de
ser creados fueron favorecidos con este nacimiento espiritual,
pero que por desobediencia lo perdieron,
a la reaparición de este nacimiento se le ha denominado _regeneración_ y _renovación_,
o el nacimiento de la vida divina renovado en el hombre.
Puesto que somos herederos de la muerte espiritual en Adán,
o en el estado y naturaleza caídos,
sólo podemos nacer de nuevo para vida en Jesucristo
por el poder y virtud de Su Espíritu Santo,
quien es la resurrección y la vida.

Cada poder reproductor produce su propia semejanza--el
espíritu maligno un nacimiento maligno,
y el buen espíritu un nacimiento que corresponde a su bondad.
Y así como todo nacimiento natural permite un crecimiento,
este nacimiento espiritual en el alma también lo hace.
Nuestro Salvador representa su progreso gradual con las
analogías del crecimiento de la semilla de mostaza,
el proceso de la levadura, el agua viva que salta para vida eterna, etc.
Los apóstoles Pedro y Juan también muestran que hay
varios grados de experiencia entre los creyentes,
usando las metáforas de bebes recién nacidos, niños, jóvenes y padres,
y ciertamente hasta el estado de padres permite un crecimiento continuo,
como el mismo Pablo dio testimonio.
Porque,
aunque Pablo verdaderamente afirmó que la ley del Espíritu de vida en
Cristo Jesús lo había hecho libre de la ley del pecado y de la muerte,
todavía era sensible a grados más altos de crecimiento aún puestos delante él,
y después de treinta años en el apostolado él reconoce lo siguiente:
"`No que lo haya alcanzado ya, ni que ya sea perfecto; sino que prosigo,
por ver si logro asir aquello para lo cual fui también asido por Cristo Jesús. Hermanos,
yo mismo no pretendo haberlo ya alcanzado; pero una cosa hago:
olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante,
prosigo a la meta, al premio del supremo llamamiento de Dios en Cristo Jesús.`"^
footnote:[Filipenses 2:12-14]

Aquellos que consideran que la necesidad de que el hombre sea regenerado,
transformado y guiado por el Espíritu de su Creador es un insulto a la razón humana,
deshonran grandemente la Suprema sabiduría, bondad y poder.
La dignidad de la naturaleza humana no consiste, en lo absoluto, en la autosuficiencia.
El más alto de los seres angelicales no desea ni actúa de forma independiente a su Creador,
mucho menos el hombre, que en su pureza primitiva fue "`hecho menor que los ángeles.`"^
footnote:[Salmo 8:5]
En verdad, el hombre está en una necesidad continua de ayuda divina,
y su verdadera dignidad consiste en ser capaz de _recibir conscientemente_ esta asistencia,
y de este modo tener acceso a una bendita unión y
comunión con su Hacedor y preservación en ellas.
No es un menosprecio para un inferior ser dirigido y guiado por un Ser superior.
¡Especialmente por el Supremo Señor y único Autor de toda existencia!
Dotada con Su Espíritu, en cualquier grado,
la criatura es levantada por encima del más alto nivel de su propia naturaleza,
y cuánto más es revestida de Él, más es dignificada y exaltada.
En verdad,
solamente cuando el Sol de Justicia emite Sus rayos
vivificadores sobre el espíritu del hombre,
es que el pobre gusano es capaz de volar y ascender por encima
de sus límites terrenales hacia las regiones celestiales.
