== Capítulo 6. La Regeneración: Una Experiencia Perceptible

Ahora bien, hombre, ¿cuál es el gran asunto de tu vida en este mundo,
sino volver al paraíso de Dios y asegurar la herencia eterna que es incorruptible,
incontaminada e inmarcesible?
Para lograr esto, debes ser despojado de todo lo que te hace indigno de tener una entrada.
Lo que haya sido la causa de la exclusión, debe ser removida.
Lo que no pueda tener un lugar o habitación allí, debe ser separado de ti,
o no podrás ser admitido.
"`Aquello que detiene, detendrá hasta que sea quitado del medio.`"^
footnote:[2 Tesalonicenses 2:7]
Cualquier cosa que tengas en ti o alrededor de ti a la que estés apegado como consecuencia
de la caída--todo el yo independiente y la mente carnal--debe ser entregada,
o nunca podrás experimentar la restauración. El hacha del evangelio,
el poder del Espíritu de Dios, debe ser puesta a la raíz del árbol corrupto en ti,
para que sea desarraigado y la Vid de la vida plantada en su lugar.
Entonces la Palabra implantada, la cual puede regenerar y salvar el alma,
podrá florecer y producir sus frutos celestiales donde la naturaleza pecaminosa
por tanto tiempo ha esparcido sus productos venenosos en el corazón. Es de aquí,
solamente, que surge toda la verdadera felicidad en la criatura,
y las alabanzas vivas para el eterno Autor de Salvación.

En el tiempo primitivo,
la necesidad de regeneración no fue solamente predicada a los pueblos,
sino que realmente fue experimentada por los creyentes.
Tenemos un ejemplo claro y significativo en 1 Corintios 6:9-11
"`¿No sabéis que los injustos no heredarán el reino de Dios?
No erréis; ni los fornicarios, ni los idólatras, ni los adúlteros, ni los afeminados,
ni los que se echan con varones, ni los ladrones, ni los avaros, ni los borrachos,
ni los maldicientes, ni los estafadores, heredarán el reino de Dios.
Y esto erais algunos; mas ya habéis sido lavados, ya habéis sido santificados,
ya habéis sido justificados en el nombre del Señor Jesús,
y por el Espíritu de nuestro Dios.`"
Aquí el apóstol testifica claramente que algunos de los hermanos Corintios,
que habían sido de corazones contaminados y de vidas viciosas, fueron regenerados,
lavados y santificados.
Él muestra que este gran cambio en ellos fue hecho
en el nombre (o poder) del Señor Jesús,
y explica que es por medio del Espíritu de nuestro Dios.
El apóstol Pedro coincide con Pablo al dar el mismo testimonio--"`Habiendo
purificado vuestras almas por la obediencia a la verdad,
mediante el Espíritu, para el amor fraternal no fingido,
amaos unos a otros entrañablemente, de corazón puro; siendo renacidos,
no de simiente corruptible, sino de incorruptible,
por la palabra de Dios que vive y permanece para siempre.`"^
footnote:[1 Pedro 1:22-23]
Muchos otros textos podrían ser añadidos para este mismo propósito.

El apóstol muestra particularmente la naturaleza y la manera
de esta obra en los capítulos 7 y 8 de Romanos,
que muchos, por falta de una experiencia verdadera,
han sido inducidos a imaginar que fueron escritos con el
fin de describir su propia condición en ese momento.
Sin embargo,
es evidente que estos capítulos comprenden diversas e incluso contrarias
condiciones que él y otros habían experimentado en su progreso cristiano,
y que era imposible que él estuviera en ellas al mismo tiempo, a saber:
en un estado de oscuridad y en un estado de luz;
en un estado de impureza y en un estado de pureza;
en un estado de esclavitud y en un estado de libertad;
en un estado de vida y en un estado de muerte.

En el capítulo 7:5, él dice,
"`Porque mientras estábamos en la carne,`"--bajo el dominio de
la naturaleza carnal--"`las pasiones pecaminosas que eran por la
ley obraban en nuestros miembros llevando fruto para muerte.`"
Aquí se refiere al estado de pecado y muerte en el que anteriormente estaban esclavizados,
pero que ahora había pasado, como claramente aparece en el siguiente verso,
"`Pero ahora estamos libres de la ley,
por haber muerto a aquello en que estábamos sujetos,
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra.`"
En el verso 7, él vuelve a hablar del estado anterior y es más específico:
"`yo no conocí el pecado,`" dice él, "`sino por la ley.`"
Antes de llegar a sentir condenación en su propia consciencia,
en la que le fue abierto un sentido del requerimiento de Dios,
él permanecía en su primer estado natural de ceguera, aunque no sabía que era así,
a pesar de su amplia educación y rigor legal.
Aunque "`muerto`" en cuanto al sentido de la vida divina,
él estaba "`vivo`" en el espíritu del mundo.
"`Y,`" dice él, "`yo sin la ley vivía en un tiempo; pero venido el mandamiento,
el pecado revivió y yo morí.`" Ahora al quedar la naturaleza pecaminosa
en oposición por la aparición y la administración interna de la ley espiritual,
que trajo verdadera convicción,
dicha naturaleza fue agitada nuevamente por el poder del mal,
y se levantó como con nueva vida y vigor para evitar que él escapara de ella;
"`porque sin la ley el pecado está muerto.`"
Es decir, la naturaleza de pecado permaneció quieta y sin perturbaciones,
disfrutando su indulgencia sin interrupción,
hasta que la ley de la vida fue ministrada en su contra.
Entonces "`hallé que el mismo mandamiento que era
para vida,`" por la resistencia de esa naturaleza,
"`a mí me resultó para muerte; porque el pecado, tomando ocasión por el mandamiento,
me engañó, y por él me mató,`" o me oscureció y trajo una sensación de muerte sobre mí.

Parece que el pecado lo engañó primero con la creencia de que la ley produce muerte,
porque él experimentó una sensación de muerte como
resultado de las convicciones de esta ley.
Pero en realidad, la muerte es el fruto del pecado, el cual es condenado por la ley.
Entonces él dice, "`la ley a la verdad es santa, y el mandamiento santo, justo y bueno.
¿Luego lo que es bueno, vino a ser muerte para mí? En ninguna manera.`"^
footnote:[Romanos 7:12-13]
Mas bien,
encontró que aquello que se oponía tan violentamente a la ley fue lo que produjo
la muerte y ocasionó que la condenación de la ley viniese sobre él,
la cual descubrió esta muerte dentro de él. Esto fue permitido para que "`el pecado,
pueda mostrarse pecado,`" y para que por la fuerza convencedora
del mandamiento "`llegase a ser sobremanera pecaminoso`" a su vista,
y fuera tenido por él con aborrecimiento.

Luego él expresa con un vivo sentido de experiencia
la esclavizante situación de este convencido,
pero no cambiado estado, en el verso 14--"`La ley es espiritual; mas yo soy carnal,
vendido al pecado.
Porque lo que hago, no lo entiendo.`"
Estoy convencido de que es malo y con mucho gusto quisiera ser libre,
pero a pesar de mis convicciones estoy bajo su poder y no puedo librarme.
"`Porque no hago el bien que quiero, sino el mal que no quiero, eso hago.`"
Sin embargo, en paciente sumisión y aferrado fervientemente a Dios,
algo de consolación y entendimiento acompañó este estado despierto;
"`Y si hago lo que no quiero, ya no lo hago yo,
sino el pecado que mora en mí. Porque según el hombre interior,
me deleito en la ley de Dios; pero veo otra ley`"--o poder--"`en mis miembros,
que se rebela contra la ley de mi mente,
y que me lleva cautivo a la ley`"--o poder--"`del pecado que está en mis miembros.`"
Por tanto, impedido de lo que amo y llevado cautivo por lo que odio,
¡estoy en una miserable esclavitud! "`¡Miserable de mí!
¿quién me librará de este cuerpo de muerte?`"

En conclusión, él procede a mostrar que,
aunque en otro tiempo esa había sido su condición,
ahora experimentaba libertad perfecta de todas las circunstancias confusas e hirientes,
y de los distintos estados de ejercicio por los que anteriormente había pasado.
"`Ahora, pues,`" él dice,
"`ninguna condenación hay para los que están en Cristo Jesús,`" (aunque
antes claramente la había) "`los que no andan conforme a la carne,
sino conforme al Espíritu.
Porque la ley del Espíritu de vida en Cristo Jesús
me ha librado de la ley del pecado y de la muerte.`"^
footnote:[Romanos 8:1-2]
Esto nuevamente testifica de su libertad y corresponde al verso citado previamente,
"`ahora estamos libres de la ley,`" la cual condena por causa del pecado;
"`habiendo muerto a aquella en que estábamos sujetos +++[+++a saber, la naturaleza pecaminosa],
de modo que sirvamos bajo el régimen nuevo del Espíritu
y no bajo el régimen viejo de la letra.`"
Colosenses 1:12-14 está de acuerdo con estas Escrituras:
"`con gozo dando gracias al Padre que nos hizo aptos
para participar de la herencia de los santos en luz;
el cual nos ha librado de la potestad de las tinieblas,
y trasladado al reino de su amado Hijo.`"

Evidentemente, el experimentado apóstol en los pasajes de Romanos 7 y 8 citados arriba,
incluye una representación de tres condiciones muy diferentes,
mostrando el curso de su progreso y las diferencias entre ellas.
Primero, el estado natural, ciego y no convencido,
el cual es aquel de oscuridad y de muerte,
que corresponde al caos original antes de que la luz resplandeciera.
Segundo, el estado de iluminación y descubrimiento, de convicción y de guerra interna,
con la expectativa de alcanzar una conversión completa.
Este estado experimenta una mezcla,
en la que la luz y la oscuridad están en el acto de separación,
como aquello en Génesis 1:3-5. Tercero,
el estado de redención del poder del pecado a través de la purificación,
y traslado al reino espiritual de Cristo.
Este es el estado del cristiano perfecto y completa la nueva creación,
en la que todo toma su debido lugar y se mueve en el orden correcto.

Ahora apelo al lector--¿No es absurdo imaginar que estos tres estados diferentes,
y en algunos aspectos contrarios,
puedan subsistir juntos en la misma persona al mismo tiempo?
En esta corta sección de su carta (que contiene una descripción
breve pero completa de la obra del nuevo nacimiento),
el apóstol muestra los diferentes estados por los que los
nuevos en la fe tienen que pasar en su viaje preparatorio,
y además, en palabras de su propia experiencia les recuerda a los realmente regenerados,
lo que ellos ya han experimentado.
Él describe los diversos pasos y las principales directrices del Espíritu Santo,
hasta que por su operación efectiva,
el alma se convierte en una nueva criatura y le es
otorgada una generosa entrada al Reino de Dios;
al cual, siendo espiritual y en el interior, se entra por un camino interno y espiritual.

Por lo tanto, es muy claro que un hombre puede adquirir todo el aprendizaje,
y recibir todos los grados que las escuelas y universidades otorguen,
con toda la autoridad que los hombres proporcionen,
y también puede ser estricto en la práctica de todas
las formas y aspectos externos de religión,
y sin embargo, seguir siendo un hombre natural.
De hecho,
esas cosas no pueden acercarlo más a la verdadera regeneración
de lo que él estaba al momento de su nacimiento natural,
porque el nuevo nacimiento es sólo obra del Espíritu Santo.
Solamente el Espíritu de Santidad puede hacer a un hombre santo,
porque nada puede comunicar o impartir lo que no posee.
Nada puede liberar a los hombres del poder del pecado (y de su paga de muerte),
excepto la ley o poder del Espíritu de vida en Cristo Jesús, ministrado individualmente.
Este Espíritu Santo--que convierte a los pecadores
en santos mediante una verdadera purificación,
y que en cuanto a su estado interno los hace nuevas
criaturas--es la verdadera luz y líder de las almas.
Por medio de Sus manifestaciones inmediatas en el corazón,
el Espíritu se vuelve el guía principal de la vida y la conducta,
y también frecuentemente trae a la memoria las verdades de la Escritura,
abriendo su significado de manera provechosa para el entendimiento,
e influenciando la mente y el corazón a vivir de acuerdo a la verdad revelada de Dios.

Es evidente que el apóstol describe, en las escrituras antes mencionadas,
diversos cambios de condición, que a través de la operación y efecto del Espíritu Santo,
él ciertamente había conocido y sensiblemente sentido.
Sin embargo, hay muchos en el cristianismo, incluso entre los líderes del pueblo,
que desechan todas las experiencias internas e individuales del
Espíritu como si fuesen una fantasía entusiasta y distorsionada.
¡Ay!, estos hacen un espectáculo de su conocimiento al hablar de las cosas de Dios,
pero carecen de un entendimiento correcto de ellas;
porque en verdad la soberbia del conocimiento natural y el adorno de la elocuencia
no tienen más concordancia con la Verdad que la vanagloria de la vida.
Estas cosas pertenecen a la sabiduría del mundo, por la que Dios no puede ser conocido;
porque "`el mundo por medio de su sabiduría no conoció a Dios,`"^
footnote:[1 Corintios 1:21]
ni las cosas de Dios.
Todo el conocimiento del hombre natural,
del hombre cuya naturaleza permanece sin cambios (sea llamado pagano, judío o cristiano,
y su conocimiento sea llamado filosofía o divinidad),
no es más que la sabiduría ineficaz y conocimiento mental de este mundo;
no es la sabiduría de arriba por la que únicamente
es conocido y experimentado Dios y Sus cosas.
La sabiduría de Dios está fuera del alcance de las artes,
los idiomas y las ciencias del hombre,
y sólo se descubre por la manifestación del Espíritu de Cristo en el corazón--"`en
quien están escondidos todos los tesoros de la sabiduría y del conocimiento.`"^
footnote:[Colosenses 2:3]

Sin embargo,
aunque el mundo no conoce a Dios por medio de su admirada y celebrada sabiduría,
hay una sabiduría dada al hombre por la cual Él es conocido.
"`Porque Dios,`" dicen las sagradas Escrituras,
"`que mandó que de las tinieblas resplandeciese la luz,
es el que resplandeció en nuestros corazones,
para iluminación del conocimiento de la gloria de Dios en
la faz`"--o aparición interna--"`de Jesucristo.`"^
footnote:[2 Corintios 4:6]
El apóstol agrega, "`Pero tenemos este tesoro en vasos de barro,
para que la excelencia del poder sea de Dios, y no de nosotros.`"^
footnote:[2 Corintios 4:7]
Este poder excelente e iluminador opera en el que lo recibe con humildad y agradecimiento,
para abrir su entendimiento de lo que lee,
tanto en las Escrituras como en otros escritos provenientes de una experiencia viva,
a menudo concediéndole _sentir_ lo que está leyendo y cosechar sus provechosos efectos.
Pero el que rechaza los medios nunca puede obtener el fin.
Aquel que se rehúsa o huye de la luz de la vida cuando ella,
mediante sus reprensiones y convicciones,
se ofrece a sí misma a él (no creyendo que sea de Dios, ni recibiéndola como tal),
detiene su operación e impide que ella se le revele y se
extienda en él. El corazón incrédulo cierra su propio camino,
y por lo tanto permanece insensible al poder interno del Salvador.

¿Qué hombre en la tierra puede decir que no ha sentido estas convicciones?
¿Y quién puede tener un sentido de ellas y no distinguirlas
de los esfuerzos de su propia razón,
ni distinguir al Reprobador del reprobado?
Es imposible que haya convicciones que no se sientan.
¿Puede ser experimentada la obra de renovación sin ninguna percepción de su progreso?
¿Describió el apóstol Pablo, con tanta sensibilidad,
los estados dolorosos por los que había viajado y los poderes
opuestos que habían hecho guerra dentro de él,
sin nunca haberlos sentido?
¿Deben ser tratadas sus experiencias cristianas como el mero producto
de una apasionada o distorsionada fantasía? ¿Es posible que una
persona experimente el arrepentimiento para vida,
la remisión de pecados y los "`tiempos de refrigerio de la presencia del Señor,`"^
footnote:[Hechos 3:19]
sin sentirlos internamente?
Todos los clamores, los anhelos y la sed tras la presencia divina,
¿fueron expresados por los escritores sin un profundo sentido de su carencia?
Todas sus triunfantes alegrías en la consolación de Su presencia,
¿fueron expresadas bajo una total insensibilidad de ellas?
Los frutos del Espíritu y los consuelos del Espíritu Santo,
¿no fueron sentidos por quienes los disfrutaron?
¿Quién puede afirmar estas cosas tan absurdas?
¿Hasta dónde pueden llevar estos guías ciegos a sus ciegos seguidores?
Aquellos que le dan la espalda a la luz, caminan en tinieblas.
Es propiedad exclusiva del Espíritu de Cristo, la Luz de los hombres,
darle verdaderas revelaciones al alma,
tanto respecto a sí misma como de todo lo demás que le concierne.
Por lo tanto, Él es correctamente llamado el "`Sol de Justicia`"^
footnote:[Malaquías 2:14]--porque Él es para el alma del hombre,
exactamente lo mismo que el sol en el firmamento es para el cuerpo.
Uno es la luz externa, el otro es la luz interna.

Es el hombre incrédulo y no renovado,
ajeno a la operación efectiva de este Espíritu celestial,
el que inconscientemente lo rechaza y menosprecia,
y de este modo contribuye a mantenerse, tanto a sí mismo como a otros,
ciego con respecto al Espíritu y prejuiciado en Su contra.
"`El hombre natural,`" dice el apóstol,
"`no percibe las cosas que son del Espíritu de Dios, porque para él son locura,
y no las puede entender, porque se han de discernir espiritualmente.`"^
footnote:[1 Corintios 2:14]
'`¿Qué?`' dice el hombre poderoso en la razón, '`¿Debo quitarme los ojos para poder ver?
¿Debo dejar a un lado mi razón y renunciar a ella para obtener un mejor entendimiento?
¡Es imposible y absurdo!`' No,
la _correcta_ razón no es la que está siendo objetada ni desaconsejada,
porque la razón correcta es verdadera,
y siempre concuerda con los movimientos internos del Espíritu de la Verdad.
Sin embargo, evidentemente aparece (en los diversos prejuicios, presuposiciones,
debilidades y diferencias irreconciliables entre los hombres) que muchas
veces la razón _humana_ está lejos de estar de acuerdo con la razón _correcta_.
El peligro, por lo tanto, está en establecer la razón humana por encima del lugar
que le corresponde en la religión,
de hacerla líder en lugar de seguidora de la revelación,
de hacerla maestra en lugar de aprendiz,
y de estimarla con algún tipo de autosuficiencia e independencia
de la dirección y ayuda del Espíritu Santo de Dios.

Así como la luz del sol es dispensada perfectamente por la soberana sabiduría,
de tal manera que no ciega los ojos de los hombres,
sino más bien los ayuda a usarlos adecuadamente;
así mismo la iluminación e influencia divina es administrada por la misma sabiduría,
en tales grados, que no excluye la razón del hombre, ni la priva de su utilidad,
sino que la restaura a su uso apropiado en la religión
al disipar las neblinas del prejuicio y de la pasión,
dándole un claro sentido de su deber y suministrándole la capacidad de realizarlo.
Los hombres santos de Dios no fueron privados de sus entendimientos cuando
ellos hablaron y escribieron según fueron movidos por el Espíritu Santo.
Al contrario,
ellos sintieron su entendimiento iluminado y altamente mejorado por Él. Ellos no fueron
usados por el Espíritu, como si fuesen maquinas insensibles o vegetales irracionales,
inconscientes de la virtud que estaba surgiendo en ellos y que los estaba empoderando.
Sus facultades fueron iluminadas y elevadas a un nivel de
utilidad mucho más alto del que alguna vez pudieron experimentar
cuando no eran asistidos por el poder de la gracia divina.
Por lo tanto, con mucha razón,
uno de los escritores inspirados ha dado esta tan necesaria exhortación:
"`Fíate de Jehová de todo tu corazón, y no te apoyes en tu propio entendimiento.`"^
footnote:[Proverbios 3:5]
Y además dice, "`El que confía en su corazón es necio.`"^
footnote:[Proverbios 28:26]
