== Capítulo 7. La Ley del Espíritu de Vida en Cristo Jesús

A pesar de que a muchos se les enseña a suponer una
importancia y una eficacia en diversas ceremonias,
señales y sombras externas de la dispensación de la ley, no obstante,
es cierto que "`en Cristo Jesús ni la circuncisión vale algo, ni la incircuncisión,
sino la fe que obra por el amor.`"^
footnote:[Gálatas 5:6]
De hecho, ni la práctica,
ni la negación de las formas y de los rituales valen algo para con Dios--Aunque
lo primero pueda mantener infructuosamente ocupados a los que las practican,
y peligrosamente engañarlos a poner su confianza
en sus propias obras o en las de sus líderes.

La religión del verdadero cristiano consiste en sustancia, no en una forma externa.
No viene de la actividad de la razón, imaginación u opinión humana,
sino de la experiencia del amor divino en la Luz de la Vida que
se siente en lo profundo del corazón. Su fundamento es nada menos,
que la administración inmediata del Espíritu Santo de Dios al espíritu del hombre.
Este Espíritu le muestra al hombre los pensamientos de Dios acerca de él,
y revela quién y qué es el Señor, en la medida que le concierne al creyente.
Abre el entendimiento y dirige el deber del obediente;
porque "`el hombre no es señor de su camino,
ni del hombre que camina es el ordenar sus pasos.`"^
footnote:[Jeremías 10:23]
Es la luz del Cordero la que muestra el camino de salvación,
la única gran Luz designada para gobernar el día (o dispensación espiritual) del cristianismo,
en la cual deben caminar los que son salvos.

El hombre en su estado natural puede, al leer y estudiar,
acumular abundancia de nociones sobre el Ser Supremo;
pero tal como la luz manifiesta todas las cosas,
y aun así no puede ser conocida realmente sino por su propia aparición,
así Dios (quien en el sentido más perfecto,
es luz) sólo puede ser conocido por medio de Su propia manifestación inmediata.
Lo que los hombres normalmente llaman conocimiento de Dios
no es más que una serie de ideas acerca de Su esencia,
Sus atributos y Su providencia, pero nuestro Salvador llamó conocimiento de Dios,
a la experiencia real y consciente de Su vida.
"`Y esta es la vida eterna: que te conozcan a ti, el único Dios verdadero,
y a Jesucristo, a quien has enviado.`"^
footnote:[Juan 17:3]
Conocerlo verdaderamente es participar del sentido vivificador de Su vida,
a través de la influencia de Su Espíritu eterno que es comunicada.
En consecuencia, el verdadero conocimiento de Dios es la participación del nuevo pacto,
o de la verdadera dispensación del evangelio, porque es aquí que es declarado,
"`todos me conocerán, desde el más pequeño de ellos hasta el más grande.`"^
footnote:[Jeremías 31:34]

Por consiguiente,
el cristiano verdaderamente vivo tiene un sentido
certero de la vida divina en su propio pecho,
el cual le proporciona instrucción, fuerza y consuelo,
de tal manera que él lo espera con fidelidad,
y no está bajo la absoluta necesidad de apoyarse en las enseñanzas de otros hombres.
Sin embargo, cuando los maestros vienen en una medida de la misma vida,
él los siente y los acepta como instrumentos de Dios.
Esta vida de Dios en Cristo es el alma misma del cristianismo,
sin la cual las mejores formas y las más elevadas profesiones
son sólo miembros indeseables de un cuerpo muerto.

"`El que tiene al Hijo, tiene la vida;
el que no tiene al Hijo de Dios no tiene la vida.`"^
footnote:[1 Juan 5:12]
"`Porque yo vivo,`" Él dice,
"`vosotros también viviréis. En aquel día vosotros conoceréis que yo estoy en mi Padre,
y vosotros en mí, y yo en vosotros.`"^
footnote:[Juan 14:19-20]
Es porque Él vive y comunica Su vida a Sus seguidores espirituales,
que ellos también viven.
La verdadera iglesia (el cuerpo de Cristo que Él adopta
de entre todas las denominaciones) está compuesta de estos.
Sólo ellos son Su especial heredad y sacerdocio.

El cuerpo de Cristo es un cuerpo vivo, hecho así por el soplo de Su vida.
Él mismo es la vida en común de todos Sus miembros verdaderos,
y a través de Su influencia viva les comunica un sentido vivo de la verdad,
los inclina hacia Sí mismo y los inspira con el deseo y el poder de la obediencia.
Y a medida que estos avanzan en fidelidad,
Él los favorece con pruebas crecientes de gracia y amor divinos,
con el dulce sabor de la unción santa y con la virtud y
gloria de Su presencia celestial que mora en el interior.
Sólo hay "`un cuerpo, y un Espíritu.`"^
footnote:[Efesios 4:4]
Si no hubiera un único y mismo Espíritu en toda la iglesia,
no podría ser un único cuerpo, ni un cuerpo vivo.
"`El cuerpo de Cristo no puede vivir sino por el Espíritu de Cristo,`" dijo Agustino.
Él que no participa con la Cabeza del mismo Espíritu,
no es un miembro verdadero del cuerpo.
Su influencia espiritual es la sangre preciosa o manantial
de vida que hace que todos Sus miembros vivan.
Y Aquel que da vida, también da un sentido de esa vida,
la cual "`está escondida con Cristo en Dios.`"^
footnote:[Colosenses 3:3]--escondida del conocimiento
de aquellos que aún no han sido vivificados por ella;
y es de aquí que viene toda su oposición en contra de ella.

Todos nosotros somos por naturaleza extraños a esta vida divina,
y de ninguna manera podemos obtenerla por nosotros mismos.
No es por la consecución del hombre, sino por la comunicación de Dios; por lo tanto,
ella está tan lejos del alcance del más estudiado como del más inculto.
Está escondida de los sabios y prudentes a sus propios ojos,
y es revelada a los que son como niños para la sabiduría del mundo.
Dios no enseña al altivo ni aprendido, sino al pequeño y humilde,
y al manso lo guía por caminos de verdad y juicio.
Por lo tanto, los ojos de todos solo deben ser dirigidos humildemente hacia Dios,
y no ser puestos en los sabios, los escribas ni disputadores de este mundo;
porque Dios por medio de la poderosa simplicidad y pureza de Su dispensación del evangelio,
"`ha enloquecido la sabiduría del mundo.`"^
footnote:[1 Corintios 1:20]
Sin embargo, el mundo ama tanto su propia sabiduría,
que ha derribado la cruz de Cristo en gran medida,
junto con la verdadera religión espiritual,
y en su lugar ha erigido y respaldado al ídolo actual.
El mundo se ha arrodillado ante esta imagen, y de hecho, ha sido un medio para cegar,
atrapar y engañar a sus adoradores,
cuya fe está en la sabiduría del hombre y no en el poder de Dios.

A partir de la debida consideración del glorioso propósito de la creación del hombre,
así como también del estado degradado y corrupto de la humanidad desde la caída,
debe mostrarse evidente que la única cosa necesaria siempre ha sido la
regeneración verdadera--la obra esencial que todos tienen que experimentar.
Y así como el nacimiento del Espíritu no puede ser
producido por ninguna otra cosa que no sea el Espíritu,
así su crecimiento y realización deben ser preservados por este mismo Espíritu.
Por lo tanto, la permanencia o morada del Espíritu en el interior,
es de absoluta necesidad para el regenerado,
para que en la medida que sus almas son vivificadas en la vida divina por el Espíritu,
en esa misma medida continúen viviendo,
moviéndose y teniendo su ser como cristianos en Él,
y ser sostenidos en unión espiritual y comunión bendita con su Hacedor.

La esencia de la verdadera religión siempre ha sido la misma, consistiendo primeramente,
en la vida de Dios siendo resucitada en el corazón, y en el amor de Dios derramado allí,
operando internamente hasta lograr una verdadera renovación,
y para llevar a todo fruto virtuoso y benevolente.
Cualesquiera que sean las cosas externas o ceremonias que en ciertos
tiempos hayan sido añadidas por la dirección u ordenanza divina,
no fueron con la intención de alterar o desenfocar al hombre de
su debida y constante atención a la religión vital y espiritual.
Fue sólo cuando el hombre llegó a estar muy degenerado en cuanto a lo interno y lo espiritual,
y oscurecido al respecto,
que el misericordioso Creador se plació (por medios adecuados a su condición
alejada y carnal) apuntársela a través de señales y símbolos,
y por medio de estas cosas guiarlos hacia ella.
Por lo tanto,
la ley Mosaica no estaba destinada a ser toda la religión de los Israelitas,
o a reemplazar la religión interna de Abraham,
sino sólo a ser un "`ayo para llevarlos a Cristo`"^
footnote:[Gálatas 3:24]
en el Espíritu, en quien todo está incluido y cumplido,
y cuya presencia estaba en ese entonces con los fieles en Israel,
quienes tenían una comunión espiritual con Él. Porque de acuerdo a la Escritura,
"`todos comieron el mismo alimento espiritual,
y todos bebieron la misma bebida espiritual;
porque bebían de la roca espiritual que los seguía, y la roca era Cristo.`"^
footnote:[Corintios 10:3-4]

Suponer que la religión entera desde siempre haya consistido en modas o formas,
o que el Señor en algún momento haya prescindido de la substancia
interna por el bien de la sombra externa es vano.
No, Él es Dios y no cambia.
Su ley es Su propio Espíritu de eterna perfección. Las diferentes modificaciones
que Dios ha usado entre los hombres en puntos de religión han sido ocasionadas
por las diferentes alteraciones en las condiciones de la humanidad.
El Dios Omnisciente ha dirigido a algunos por un tiempo, misericordiosamente,
a sombras y ceremonias externas para el buen fin arriba mencionado;
y los hombres han inventado y añadido muchas más,
de acuerdo a sus propios malentendidos carnales de cosas espirituales,
o para hacer avanzar sus propios propósitos siniestros.
Pero las formas externas son sólo asuntos temporales;
no son la esencia del cristianismo verdadero.
El gran Autor del cristianismo describe esta esencia
como "`una fuente de agua que salta para vida eterna.`"^
footnote:[Juan 4:14]
Surge de un Espíritu viviente, permanente y creciente en el hombre,
el cual es de una naturaleza pura y celestial.
A medida que este es recibido con amor,
se expande en el alma y expulsa las obras y el poder de las tinieblas,
y produce Sus propios frutos genuinos de humildad, negación del yo, paciencia, justicia,
santidad, mansedumbre, gentileza, templanza, bondad, afecto fraternal, amor,
rendición a Dios y confianza en Él solamente.
Esta obra deriva su origen del cielo y conduce de regreso a él,
llevando al alma fuera de todas las formalidades y los falsos reposos,
hacia la Suprema bondad misma.
Destruye toda voluntad del yo y lleva a la perfecta rendición a la voluntad divina.
En esta humilde y contrita condición (y no en otra)
podemos sincera y verdaderamente decir:
"`¡Venga tu reino.
Hágase tu voluntad!`"
Porque mientras que nuestras voluntades están separadas de la voluntad de Dios,
no podemos dirigirnos en estos términos a Él con propiedad, o en Espíritu y verdad.

Ahora, el orgullo del hombre es naturalmente hostil a esta condición abatida y contrita.
No sabe cómo someterse para ser nada, o para considerarse a sí mismo nada,
aunque ciertamente, es peor que nada.
Con muchas ganas se establecería y exaltaría a sí mismo como poseedor de importancia,
estima y mérito propio, sin embargo, todas sus pretensiones son falsas y vanas.
En verdad, el hombre no es sino lo que Dios ha hecho de él,
y no posee nada sino lo que Dios le da.
Él es completamente de Dios y no de sí mismo,
y por tanto está obligado a caminar en obediencia a Él en cada momento de su vida,
la cual se le da con ese fin.
Y viendo que el hombre no cumplió con su deber,
y que ha pecado contra su Creador mediante la desobediencia, no está en su poder,
por mucho que pueda hacer, merecer el cielo o comprar remisión para sí mismo.
Él tampoco puede deshacer lo que ha hecho,
ni entregarle a su Creador un equivalente por las
transgresiones que ha cometido en Su contra.
Pero tal es la misericordiosa bondad y la gracia
gratuita de Dios hacia Sus indefensas criaturas,
que Él ofrece tanto el perdón como la felicidad bajo los términos más razonables.
Para los "`dispuestos y obedientes,`"^
footnote:[Isaías 1:19]
para el que sea "`fiel hasta la muerte,`"^
footnote:[Apocalipsis 2:10]
para el "`que venciere`"^
footnote:[Apocalipsis 2:7, 11, 17, 26; 3:5, 12, 21; 21:7]
(por medio del poder del Espíritu), para estos son las promesas de la vida eterna.
Sobre la base de estas ofertas gratuitas y voluntarias de la bondad divina,
y del cumplimiento de las condiciones por parte del hombre,
descansa su derecho de entrar.
"`Bienaventurados los que hacen sus mandamientos,
para que tengan derecho al árbol de la vida,
y que entren por las puertas en la ciudad.`"^
footnote:[Apocalipsis 22:14 RV1602P]

En la Escritura,
las leyes y los requisitos de Dios para el hombre a menudo son llamados pactos.
El hombre en pacto con Dios le debe su mismo ser y todo el bien que recibe,
tanto espiritual como temporal, a su Hacedor, con quien está en deuda por todo.
Por lo tanto, Dios tiene el derecho incuestionable de demandar todo el afecto,
la gratitud y la obediencia del hombre, y más especialmente,
cuando todos Sus tratos contribuyen a su bienestar eterno.
También hay un pacto interno y espiritual (una conexión o unión divina),
que el corazón del hombre llega a sentir a medida que crece en fidelidad a su Creador.
Este es el Espíritu de Vida en Cristo Jesús,
el cual libera el alma del cautiverio del pecado y de la muerte,
y la une a su Salvador en el poderoso pacto de amor divino.
Por este pacto, a través de la fe, el alma es injertada en Cristo,
y mediante la obediencia permanece en Él como una rama en la vid;
porque "`el que se une al Señor, un espíritu es.`"^
footnote:[1 Corintios 6:17]
Las almas regeneradas tienen una conciencia y entendimiento certeros de esta unión viva,
en proporción a su progreso.
"`En esto conocemos que permanecemos en él, y él en nosotros,
en que nos ha dado de su Espíritu.`"^
footnote:[1 Juan 4:13]--"`Y en esto sabemos que él permanece en nosotros,
por el Espíritu que nos ha dado.`"^
footnote:[1 Juan 3:24]
Por lo tanto es evidente,
que el don del Espíritu es el que comunica este entendimiento al alma.
