== Capítulo 8. La Religión Interna y Eterna

A lo largo de todo el Antiguo y Nuevo testamento,
aparecen señales evidentes de la religión interna y de la
manifestación inmediata del Espíritu para llevarlos a ella.^
footnote:[Nota del Editor:
Aunque los primeros cuáqueros creían que una medida del Espíritu
siempre ha estado obrando en los corazones que buscaban a Dios,
inclusive desde la caída de la humanidad, sin embargo,
creían que un dote mayor y más pleno del Espíritu
fue "`derramado sobre toda carne`" en el Nuevo Pacto.
William Penn explica que el Espíritu "`fue comunicando más
escasamente en las dispensaciones anteriores`" pero,
empezando en Pentecostés, "`la luz que resplandeció tenuemente antes,
empezó a resplandecer desde las tinieblas y el lucero de
la mañana comenzó a salir en los corazones de los creyentes,
para darles el conocimiento de Dios en el rostro, o aparición, de Su Hijo, Jesucristo.`"
(Una Breve Reseña del Surgimiento y Progreso del Pueblo llamado Cuáqueros, Capítulo 1)]
Antes del diluvio,
el mundo antiguo fue favorecido con la manifestación del Espíritu Santo,
como está implícito en Génesis 6:3,
"`No contenderá Mi Espíritu con el hombre para siempre,`"--o
más bien "`en el hombre,`" como debería traducirse el hebreo.
Y, de hecho,
¿en qué otro lugar se podría decir correctamente que el
Espíritu contiende con el hombre sino en el alma,
donde está la sede de la corrupción del hombre y
donde se aplican todas las sugerencias del mal?
¿Y con qué fin contiende el Espíritu con ellos,
sino para llevarlos al arrepentimiento y reforma,
y a la experiencia del Reino o poder reinante de Dios dentro ellos?

La renovación del corazón por el Espíritu Santo,
los genuinos frutos del arrepentimiento hacia Dios, la fe en Él y la obediencia a Él,
también eran parte principal y esencial de la religión, incluso entre los Israelitas.
En Deuteronomio 30:10, Moisés muestra las condiciones por las cuales,
si ellos las cumplen,
tendrían derecho a las promesas--"`cuando obedecieres a la voz de Jehová tu Dios,
para guardar sus mandamientos y sus estatutos escritos en este libro de la ley;
cuando te convirtieres a Jehová tu Dios con todo tu corazón y con toda tu alma.`"^
footnote:[Deuteronomio 30:10]
Estos eran los términos: Primero, que debían guardar la ley;
esta era la parte externa y legal de su deber,
que mayormente consistía en figuras y testimonios de la religión interna y espiritual.
Segundo, que debían convertirse con todo su corazón y con toda su alma a Dios;
esta era la parte interna y evangélica de su pacto.
Moisés no los dejó en un estado de incertidumbre,
sino que procedió a mostrarles a qué debía volverse su atención interna.
"`Porque,`" él dice,
"`este mandamiento que yo te ordeno hoy`"--o aquello a lo que te
ordeno que vuelvas tu corazón--"`no es demasiado difícil para ti,
ni está lejos.
No está en el cielo, para que digas: ¿Quién subirá por nosotros al cielo,
y nos lo traerá y nos lo hará oír para que lo cumplamos?
Ni está al otro lado del mar, para que digas: ¿Quién pasará por nosotros el mar,
para que nos lo traiga y nos lo haga oír, a fin de que lo cumplamos?
Porque muy cerca de ti está la palabra, en tu boca y en tu corazón,
para que la cumplas.`"^
footnote:[Deuteronomio 30:11-14]

El apóstol explica este pasaje en Romanos 10:6-8,
"`La justicia que es por la fe dice así: No digas en tu corazón: ¿Quién subirá al cielo?
(esto es, para traer abajo a Cristo); o, ¿quién descenderá al abismo?
(esto es, para hacer subir a Cristo de entre los muertos).
Mas ¿qué dice?
Cerca de ti está la palabra,
en tu boca y en tu corazón. Esta es la palabra de fe que predicamos.`"^
footnote:[Romanos 10:6-8]
Por esta explicación del apóstol se evidencia: Primero, que Moisés en aquel entonces,
además de la ley escrita,^
footnote:[Véase Deuteronomio 29:1 donde dice,
"`Estas son las palabras del pacto que Jehová mandó a Moisés
que celebrase con los hijos de Israel en la tierra de Moab,
además del pacto que concertó con ellos en Horeb.`"
(énfasis mío)]
le predicó a Israel la misma Palabra de fe que Pablo y sus hermanos evangélicos predicaron.
Segundo, que esta Palabra es Cristo Mismo en el Espíritu,
demandando atención y obediencia en el corazón (o conciencia) del hombre,
para efectuar su restauración y salvación. Y tercero,
que esto no se refiere a un lugar o tiempo,
sino que es una visitación interna del Salvador de la humanidad por Su Espíritu,
en el corazón.

La Palabra de Fe es la Palabra de la verdad,
la Palabra del evangelio eterno y no una composición de letras.
El término palabra, como muchos otros términos, se usa en varios sentidos, como:
un discurso o dicho, un reporte, un mandamiento, una exhortación, instrucción, etc.,
todos estos compuestos de palabras.
Y así como los hombres usan palabras para comunicar
su sentido o significado unos a otros,
de la misma manera Dios comunica Su entendimiento a los hombres por medio de Cristo,
quien es peculiar y enfáticamente llamado en la Escritura la Palabra de Dios.
Es más, al igual que las palabras se reciben al oírlas de la boca de otros, también,
la manera por la cual el alma recibe internamente del Espíritu Santo entendimiento,
reprensión, etc., es metafóricamente llamado oír, o "`el oír de la fe.`"^
footnote:[Gálatas 3:2,5]
Así, la fe, que es el don de Dios, se dice que viene "`por el oír, y el oír,
por la Palabra de Dios.`"^
footnote:[Romanos 10:17]
Es decir (según puedo comprender),
que el oído interno mismo es abierto en el alma por el Espíritu de Cristo,
y que la verdad es comunicada allí por el mismo Espíritu.

Por lo tanto, vemos que el mandamiento divino dado a los judíos,
no consistía solamente en la ley externa y escrita;
ni tampoco se les mantuvo en ignorancia de la religión interna y espiritual,
o de un futuro estado de recompensas y de castigos.
Porque si hubiera sido así,
¿con qué propósito Moisés les insistía con tanto fervor que consideraran su final?
"`¡Ojalá fueran sabios, que comprendieran esto, y que consideraran su día final!`"^
footnote:[Deuteronomio 32:29, Traducción literal del inglés]
O,
¿por qué él ordenaría que la atención de ellos estuviera
en la Palabra viva de fe (Cristo en el corazón),
así como también en el código escrito?
Él era un profeta eminentemente inspirado,
y sabía bien que la salvación sólo viene por Cristo,
y que esta ley interna y espiritual es preferible
a la exterior tanto como la sustancia es a la sombra.
La obediencia a la ley externa y temporal tenía promesas externas y temporales;
pero la obediencia a la ley interna y espiritual
tiene promesas de una naturaleza interna y eterna.
Por las obras de la primera ningún hombre se podía justificar;
pero por la operación de la última,
se obra la santificación y se experimenta la salvación. De hecho,
Moisés era un tipo de Cristo, y la ley temporal con sus recompensas temporales,
un tipo de la ley del Espíritu de vida en Cristo Jesús y de su recompensa eterna.

Pero, se podría preguntar: Si la ley espiritual siempre era proporcionada,
¿qué motivo había para añadir los estatutos temporales?
A lo que respondo, primero: Los israelitas,
al vivir bajo la servidumbre de un pueblo sumamente supersticioso e idólatra,
ellos mismos se habían vuelto propensos a la superstición y a la idolatría. "`Antes
se mezclaron con las naciones,`" dijo el Salmista "`Y aprendieron sus obras,
y sirvieron a sus ídolos, los cuales fueron causa de su ruina.`"^
footnote:[Salmos 106:35-36]
Ellos tenían que ser sacados de esta idolatría,
y por su obediencia al único Dios verdadero,
convertirse en un ejemplo para las naciones que los rodeaban,
para influir en el regreso de ellos también.

Aunque todos tenían la Palabra cerca en el corazón, sin embargo,
habiendo perdido el verdadero sentido de lo que era,
entonces la ley "`fue añadida a causa de su transgresión`"^
footnote:[Gálatas 3:19]
y corrupción, hasta la venida de Cristo en la carne.
La sabiduría divina,
al ver que su apego profundo y habitual a las formas y supersticiones
del paganismo no admitiría una redención plena e inmediata,
accedió a encontrarse con ellos en el estado en el que estaban,
y a proceder gradualmente con ellos,
permitiendo algunas formas y ceremonias que eran "`figuras de las cosas celestiales.`"^
footnote:[Hebreos 9:23]
Así,
Él hizo de la ley externa un instrumento temporal para llevarlos
gradualmente hacia esa religión perfecta que Él pretendía
(en su debido tiempo) introducir y establecer en su pureza,
para que todos los hombres entraran y caminaran en ella.

Mientras tanto,
a la Soberana Sabiduría le pareció bien hacer sonar una
alarma y levantar una bandera ante el resto de la humanidad,
a través de Su relación con los descendientes de Israel.
Él hizo maravillas para libertarlos y ayudarlos,
y además de los muchos y excelentes preceptos morales,
les dispensó "`la forma del conocimiento y de la verdad en la ley,`"^
footnote:[Romanos 2:20]
que simbólicamente indicaban la naturaleza y la forma de la redención
y de la salvación a través de Su Hijo mediante muchos tipos,
alegorías y similitudes significativas.
Estas representaciones externas fueron sabiamente
adaptadas a un pueblo entenebrecido y supersticioso,
y tenían la intención de servir como un ayo para llevarlos gradualmente a Cristo,
es decir, al conocimiento de Cristo,
tanto en Su aparición externa como un sacrificio
propiciatorio por los pecados de la humanidad,
como en Su aparición interna como la esperanza de gloria
y el verdadero santificador y Salvador de los hombres.
Porque,
a pesar de que "`todos en Moisés fueron bautizados en la nube,`" o sumergidos
en su dispensación exterior como estando debajo de un velo,
los espirituales entre ellos eran capaces de penetrar
a través del velo a la realidad interna,
y como antes se observó, "`todos comieron el mismo alimento espiritual,
y todos bebieron la misma bebida espiritual;
porque bebían de la roca espiritual que los seguía, y la roca era Cristo.`"^
footnote:[1 Corintios 10:1-4]

Para ayudarlos aún más,
la Bondad divina a veces inspiraba con el espíritu de profecía
a muchos de los más regenerados y devotos de ambos sexos,
y los llevaba a predicar la necesidad de la verdadera justicia y santidad.
Estos profetas con frecuencia dirigían a los hombres a mirar a través
de las figuras y las similitudes externas de la ley ceremonial,
a la verdad y sustancia que indicaban.
Estos claramente exhortaban y guiaban a sus oyentes a la religión interna y espiritual,
que de hecho era la intención principal de la Mosaica,
y de cualquier otra dispensación de Dios para la humanidad.
Porque los rituales de la ley no fueron instituidos para sustituir,
sino más bien para servir como un patrón^
footnote:[Éxodos 25:9, 40; 26:30; Números 8:4; Hechos 7:44; Hebreos 8:5]
de "`la ley del Espíritu de vida en Cristo Jesús.`"^
footnote:[Romanos 8:2]

No creo que alguna vez fuera la intención de la sabiduría divina,
esconder por completo de la humanidad "`el misterio de la piedad`"^
footnote:[1 Timoteo 3:16]
y su vida y virtud interna, sino más bien, siempre estaba a la disposición,
aunque a veces oscuramente debajo de tipos y sombras,
debido a las mentes degeneradas que estaban demasiado predispuestas y entenebrecidas
como para contemplar el esplendor del evangelio en su clara manifestación. Sin embargo,
el evangelio espiritual y poderoso de nuestro Señor,
fue finalmente manifestado pública y plenamente (aparte de las sombras ceremoniales),
en el amanecer de la dispensación cristiana en el día de Pentecostés,
cuando los discípulos, esperando juntos en obediencia al mandato de Cristo,
fueron bautizados con Su único, verdadero y permanente bautismo,
aquel del Espíritu Santo, el cual cumple y reemplaza todos los otros bautismos,
y continua para siempre como la ordenanza permanente de Dios para Su iglesia.
Fue entonces cuando por revelación, el misterio fue abierto visible y poderosamente;
"`misterio que`" dice el apóstol,
"`en otras generaciones no se dio a conocer a los hijos de los hombres,
como,`" o en el mismo grado que,
"`ahora es revelado a sus santos apóstoles y profetas por el Espíritu:
que los gentiles son coherederos y miembros del mismo cuerpo,
y copartícipes de la promesa en Cristo Jesús por medio del evangelio.`"^
footnote:[Efesios 3:5-6]
"`Pero ahora, aparte de la ley, se ha manifestado la justicia de Dios,
testificada por la ley y por los profetas.`"^
footnote:[Romanos 3:21]

La ley testificaba del evangelio, en primer lugar,
por medio de sus diversas ofrendas y sacrificios,
señalando y recordando que el Mesías había de venir en la carne con el
fin de "`quitar de en medio el pecado por el sacrificio de Sí mismo.`"^
footnote:[Hebreos 9:26]
Este era el verdadero propósito de las ofrendas por el pecado y la transgresión;
"`porque la sangre de los toros y de los machos cabríos no puede quitar los pecados.`"^
footnote:[Hebreos 10:4]
No, estos apuntaban hacia la sangre preciosa de Cristo,
tanto física como espiritualmente; quien,
"`con una sola ofrenda hizo perfectos para siempre a los santificados`"^
footnote:[Hebreos 10:14]--cumpliendo y poniendo fin a todos los sacrificios de la ley.
En segundo lugar, la ley testificaba del evangelio, mediante sus diversos rociamiento,
lavamientos y purificaciones,
que no tenían más eficacia para eliminar el pecado y la culpa,
que la sangre de los toros y de los machos cabríos. Estos fueron
designados para denotar la necesidad de santidad verdadera,
y para indicar la administración espiritual de Cristo,
"`quien se dio a Sí mismo por nosotros para redimirnos,`"
no sólo de la culpa y de la condenación,
sino también de toda la corrupción interna, y para "`purificar para sí un pueblo propio,
celoso de buenas obras.`"^
footnote:[Tito 2:14]
Esto lo hace "`por el lavamiento de la regeneración
y por la renovación en el Espíritu Santo.`"^
footnote:[Tito 3:5]

Los profetas testificaban del evangelio: En primer lugar,
mediante sus declaraciones proféticas concernientes a la venida,
sufrimientos y ministerio del Mesías; y, en segundo lugar,
al enseñarle al pueblo la necesidad de una religión interna,
sustancial y efectiva--prefiriéndola por encima de la ley escrita,
incluso durante el tiempo en el que la ley estaba vigente.
Samuel dijo, "`obedecer es mejor que los sacrificios`"^
footnote:[1 Samuel 15:22]
Oseas, "`Porque misericordia quiero, y no sacrificio,
y conocimiento de Dios más que holocaustos.`"^
footnote:[Oseas 6:6]
David admite ante el Señor, "`Porque no quieres sacrificio, que yo lo daría;
no quieres holocausto.
Los sacrificios de Dios son el espíritu quebrantado;
al corazón contrito y humillado no despreciarás tú, oh Dios.`"^
footnote:[Salmos 51:16-17]
En su discurso conmovedor le dice al Todopoderoso (versículo 6),
"`Tú amas la verdad en lo íntimo,`" y ora en el versículo 10, "`Crea en mí, oh Dios,
un corazón limpio,
y renueva un espíritu recto dentro de mí.`" Miqueas
pregunta "`¿Se agradará Jehová de millares de carneros,
o de diez mil arroyos de aceite?
¿Daré mi primogénito por mi rebelión, el fruto de mis entrañas por el pecado de mi alma?`"
Y luego responde; "`Oh hombre, él te ha declarado lo que es bueno,
y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia,
y humillarte ante tu Dios.`"^
footnote:[Miqueas 6:7-8]
Moisés exhorta a los hijos de Israel a "`Circuncidarse el prepucio de su corazón`"^
footnote:[Deuteronomio 10:16]
y les dijo, "`Y circuncidará Jehová tu Dios tu corazón, y el corazón de tu descendencia,
para que ames a Jehová tu Dios con todo tu corazón y con toda tu alma.`"^
footnote:[Deuteronomio 30:6]
Aquí Moisés les mostró que aunque ellos habían recibido la señal externa de la circuncisión,
sin embargo la realidad que Dios más requería, era la del corazón, en el Espíritu,
la cual es la obra interna de regeneración. Esta es la circuncisión cristiana
de la que habla el apóstol--"`No es judío el que lo es exteriormente,
ni es la circuncisión la que se hace exteriormente en la carne;
sino que es judío el que lo es en lo interior, y la circuncisión es la del corazón,
en espíritu, no en letra.`"^
footnote:[Romanos 2:28-29]
Él también le hace la observación a los Colosenses de que ellos
fueron circuncidados en Cristo "`con circuncisión no hecha a mano,
al echar de ellos el cuerpo pecaminoso carnal, en la circuncisión de Cristo.`"^
footnote:[Colosenses 2:11]
Por lo tanto es evidente que el verdadero conocimiento y amor de Dios,
y el cambio del pecado a la santidad por la circuncisión interna del Espíritu,
fueron enseñados e impuestos a los judíos como el objetivo verdadero,
sin el cual la observancia de la ley les hubiera sido de muy poco provecho.
De hecho, el profeta Isaías muestra claramente que esto último sin lo primero,
hizo que la práctica de la ley (aunque instituida divinamente) fuera abominable,
incluso para Aquel que la instituyó.^
footnote:[Véase Isaías 1:11-14; 66:3]
