== Capítulo 9. La Administración Pura del Espíritu Santo

Cuando llegó el tiempo en el que el Señor vio conveniente llamar
al mundo degenerado fuera de las corrupciones en las que se había sumergido,
levantó a los hijos de Israel como un ejemplo para el resto de la humanidad,
por medio de la manifestación pública de Su propio dominio justo.
Los sacó de su cautiverio egipcio con mano poderosa
y a través de muchos golpes admirables de Su poder.
Luego instituyó la ley Mosaica que,
siendo la introducción de una nueva forma de Teocracia desconocida para el mundo,
fue necesariamente acompañada por tales señales extraordinarias de autoridad Divina,
que pudieron autenticarla y establecerla suficientemente como proveniente del Creador.
Por lo tanto, en esa gran ocasión,
apareció a los israelitas de una manera correspondiente a Su Omnipotente Soberanía,
introduciendo Su pacto con las señales de espanto más temibles y asombrosas,
con estruendos y relámpagos, con oscuridad, tinieblas y tempestad;
la montaña ardía en fuego,
el sonido alarmante de la trompeta que iba aumentando en extremo,
y la voz que hablaba tan terriblemente, que no sólo el pueblo,
sino toda la montaña tembló extremadamente.
Esto fue un acto obvio y sumamente solemne del Supremo Legislador del universo,
y ninguna autoridad menor que la Suya podría abolirlo o alterarlo.

Por lo tanto,
cuando llegó el período en el que Él consideró apropiado dejar
a un lado y sustituir Su ley de ordenanzas externas y carnales,
al presentar a plena vista y como la única obligación
la sustancia que ella señalaba (es decir,
Su pacto espiritual y más excelente), fue necesario que se demostrara hecho,
por las claras manifestaciones de la misma autoridad soberana.

En consecuencia,
la dispensación de la misericordia del evangelio
fue introducida por evidencias de autoridad divina,
igualmente extraordinarias.
Además de las numerosas predicciones de los profetas acerca del Mesías,
el advenimiento del Bautista que preparó Su camino y la concepción
milagrosa de nuestro Salvador por la bendita virgen,
etc.,
hubo muchas obras maravillosas realizadas por Él y grandes
señales que acompañaron el amanecer del nuevo pacto.
El velo del templo se rasgó de arriba abajo cuando Él entregó el Espíritu,
indicando la separación, la conclusión y el final de todas las señales y ceremonias,
y la revelación de la sustancia en Espíritu y verdad.
Consideren también la oscuridad inexplicable al momento de Su muerte,
Su sorprendente resurrección,
los cuerpos de los santos enterrados que resucitaron y entraron a la ciudad,
Su visible ascensión acompañada por la ministración gloriosa de ángeles, etc.
Y después de todo esto,
en el tiempo de la fiesta judía de Pentecostés (celebrada anualmente
en conmemoración de la promulgación de la ley en el Monte Sinaí),
el Espíritu Santo fue derramado sobre los apóstoles y los discípulos,
hombres y mujeres reunidos de acuerdo al mandamiento del Señor,
como la demostración del inicio del pacto espiritual,
sin ninguna mezcla de figuras legales o sombrías. Esta demostración fue de dos maneras:
_Primero,_ por la aparición de las lenguas de fuego asentándose sobre cada uno de ellos;
y _segundo,_ llenando sus corazones del Espíritu Santo a tal grado,
que comenzaron a hablar en otras lenguas, o en otros lenguajes además de los suyos,
según el Espíritu les daba que hablasen.
Dotados con sabiduría y poder celestiales, y ardiendo en amor y fervor divinos,
ahora estaban cualificados para poner en práctica la comisión
dada antes (de manera verbal) por el gran Señor y Legislador.
De la misma forma,
a muchos de ellos se les añadieron los poderes milagrosos para sanar toda clase de enfermedades.
A los mudos hacían hablar, a los sordos oír, a los cojos andar, a los ciegos ver,
endemoniados eran desposeídos, y los muertos eran resucitados y restaurados a la vida.

Ahora bien, estos poderes extraordinarios no fueron concedidos a todos,
tampoco confinados solo a los apóstoles,
sino que una medida del mismo Espíritu fue comunicada a cada uno de ellos,
tanto a mujeres como a hombres (de acuerdo con la
aplicación que Pedro hizo de la profecía de Joel).
Todos fueron llenos del Espíritu Santo,
pero dotados y cualificados de formas diferentes por Él,
para servicios diferentes según la voluntad y sabiduría del gran Dispensador.
"`Porque a éste es dada por el Espíritu palabra de sabiduría; a otro,
palabra de ciencia según el mismo Espíritu; a otro, fe por el mismo Espíritu; y a otro,
dones de sanidades por el mismo Espíritu.
A otro, el hacer milagros; a otro, profecía; a otro, discernimiento de espíritus; a otro,
diversos géneros de lenguas; y a otro, interpretación de lenguas.
Pero todas estas cosas las hace uno y el mismo Espíritu,
repartiendo a cada uno en particular como él quiere.`"^
footnote:[1 Corintios 12:8-11]
Por lo tanto,
es evidente que no toda inspiración divina va acompañada
de lo que comúnmente se llaman milagros,
sino que estos son una de las diversas operaciones del Espíritu que a veces son añadidas.
Por lo tanto,
pueden cesar totalmente cuando las ocasiones por las que fueron agregadas hayan terminado,
o continuar siendo utilizados conforme le parezca necesario a la sabiduría Divina.

Por lo tanto,
cuando el evangelio estaba tan difundido y establecido
en los lugares que en ese entonces se pretendían,
de modo que el fin para el cual se concedieron esos poderes extraordinarios fue cumplido,
fueron retirados en gran medida de la iglesia, la cual quedó, en general,
sobre su fundamento apropiado y permanente--la inspiración inmediata del Espíritu Santo.
Por consiguiente,
no se puede abogar por la necesidad de la continuación constante de los poderes milagrosos,
o de tal espíritu de profecía que predice eventos futuros,
sino solo por aquellas influencias sobrenaturales
del Espíritu que son necesarias para iluminar,
vivificar, regenerar, santificar y producir los frutos del Espíritu en el hombre.
Estas cosas son necesarias indispensablemente en todas las eras,
siendo de carácter moral y directamente influyentes
en la trasformación y salvación de cada hombre.

Yo creo firmemente que, en ocasiones particulares,
bajo la administración del antiguo y nuevo pacto, como también antes de estos,
se han evidenciado algunas intervenciones divinas de naturaleza milagrosa,
bien sea para convencer a personas dudosas,
o para dar peso y autoridad adicionales al ministerio de algunos siervos ungidos de Dios,
o para alentarlos o confirmarlos en su servicio.
No tengo duda de que algunas veces este ha sido el caso desde el primer siglo,
y puede seguir siéndolo hasta el final de los tiempos;
porque ni el poder ni la bondad del Todopoderoso han cambiado.
Sin embargo,
también soy de la opinión de que las manifestaciones milagrosas han sido
menos públicas y más moderadas después del primer siglo que antes,
lo cual puede deberse en parte a la apostasía espiritual de las iglesias profesantes.
También creo, de acuerdo con las declaraciones proféticas de los apóstoles que,
durante el estado caído y oscuro tanto de los maestros como de los oyentes,
muchas señales extrañas y prodigios mentirosos han sido y todavía pueden
ser permitidos con personas crédulas y desobedientes por impostores,
para el apoyo y la difusión de sus intereses corruptos.

Viendo que nunca más habrá un cambio en las
dispensaciones ni se predicará ninguna otra doctrina,
sino la de nuestro Salvador y Sus apóstoles (la cual recibió en su comienzo
una confirmación milagrosa suficiente para su establecimiento duradero),
las personas ahora no deben esperar o pedir milagros
de quienes predican la doctrina cristiana.
En lugar de eso,
todos deben volverse a aquel Espíritu divino señalado por las Escrituras,
y esperar en Él, el cual se manifiesta en el pecho de cada individuo,
la ministración de Cristo en el Espíritu.
Este le dará al recipiente sincero y humilde,
una demostración más clara y particular de la que
podrían hacer todos los símbolos y señales externas;
porque los poderes de los que proceden los milagros externos pueden ser cuestionados,
pero la evidencia interna de la luz de Cristo, la vida de los hombres,
cuando se espera y se aferra correctamente a ella,
no deja duda en la mente acerca de su naturaleza y autoridad divinas.

Pero para regresar al ministerio del evangelio,
el apóstol muestra (2 Corintios 3) que supera con creces al de la ley,
y que su excelencia consiste en su espiritualidad.
Habiendo hablado de la ley en el versículo 7,
el añade "`¿Cómo no será más bien con gloria el ministerio del Espíritu?
Porque si el ministerio de condenación fue con gloria,
mucho más abundará en gloria el ministerio de justificación. Porque aun lo que fue glorioso,
no es glorioso en este respecto, en comparación con la gloria más eminente.
Porque si lo que perece tuvo gloria, mucho más glorioso será lo que permanece.`"
¿Por qué el evangelio es así de preeminente sobre la ley,
viendo que la ley fue una institución divina?
Principalmente, porque el evangelio no es un código externo como lo era la ley,
sino _la ley interna de vida,_ "`escrita no con tinta, sino con el Espíritu del Dios vivo;
no en tablas de piedra, sino en tablas de carne del corazón;`"^
footnote:[2 Corintios 3:3]
y porque hace "`ministros competentes de un nuevo pacto, no de la letra,
sino del espíritu; porque la letra mata, más el espíritu vivifica.`"^
footnote:[2 Corintios 3:6]

Ningún hombre puede ser un verdadero cristiano sin el Espíritu de Cristo; porque,
"`si alguno no tiene el Espíritu de Cristo, no es de él.`"^
footnote:[Romanos 8:9]
Todo cristiano debe experimentar la presencia del Espíritu en su interior.
"`¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros,
el cual tenéis de Dios, y que no sois vuestros?`"^
footnote:[1 Corintios 6:16]
Es un requisito que todo cristiano conozca al Espíritu como su guía y líder;
porque solo "`los que son guiados por el Espíritu de Dios, éstos son hijos de Dios.`"^
footnote:[Romanos 8:14]
Ningún hombre puede ser una oveja de Cristo sin un
sentido distintivo del Espíritu de Cristo.
"`Yo soy el buen pastor; y conozco mis ovejas,
y las mías me conocen... Mis ovejas oyen mi voz, y yo las conozco,
y me siguen... Las ovejas lo siguen, porque conocen su voz.
Mas al extraño no seguirán.`"^
footnote:[Juan 10:14, 27, 4-5]
La voz de Cristo es la manifestación de Su Espíritu al alma.

Ningún hombre puede entrar en el Reino de Dios sin nacer de nuevo del Espíritu.
Esto es tan necesario para nosotros ahora como una vez lo fue para los creyentes primitivos.
Ciertamente no tenemos más habilidad para regenerarnos y prepararnos para el reino que
la que ellos tenían. No hay facultades (naturales o adquiridas) en nuestro estado no
regenerado que sean suficientes para lograr un propósito tan grande,
tampoco podrían permitirnos decir verdaderamente (con el pueblo de Dios en tiempos antiguos),
"`Señor, tú nos darás paz; porque también obraste en nosotros todas nuestras obras.`"^
footnote:[Isaías 26:12 RV1602P]

Ningún hombre puede ser ministro del Espíritu sin el Espíritu.
La instrucción apostólica es que "`cada uno según el don que ha recibido,
minístrelo a los otros, como buenos administradores de la multiforme gracia de Dios.
Si alguno habla, hable conforme a las palabras de Dios; si alguno ministra,
ministre conforme al poder que Dios da,
para que en todo sea Dios glorificado por Jesucristo.`"^
footnote:[1 Pedro 4:10-11]
En la era apostólica,
todo creyente verdadero y seguidor fiel de Cristo recibió una medida
del mismo Espíritu Santo que los profetas y apóstoles recibieron,
aunque en menor grado;
"`Porque`" dice Pablo "`por un solo Espíritu fuimos todos bautizados en un cuerpo,
sean judíos o griegos, sean esclavos o libres;
y a todos se nos dio a beber de un mismo Espíritu.`"^
footnote:[1 Corintios 12:13]
Compartir este único Espíritu los hizo un solo cuerpo, y los unió a la única Cabeza viva.
Hay "`un cuerpo, y un Espíritu,
como fuisteis también llamados en una misma esperanza de vuestra vocación; un Señor,
una fe, un bautismo, un Dios y Padre de todos, el cual es sobre todos, y por todos,
y en todos.`"^
footnote:[Efesios 4:4-6]
Por lo tanto, según las diversas medidas que se les repartieron,
todos eran partícipes del mismo Espíritu Santo; y como era entonces, así es ahora,
y siempre deberá ser en la iglesia verdadera y espiritual de Jesucristo.

El sol del evangelio se levantó con gran esplendor, sin embargo,
a ninguno se le mostró todo su brillo de una sola vez.
La revelación de la verdad en las mentes de los cristianos
primitivos (tanto los apóstoles como lo demás) era gradual.
A medida que avanzaban en la nueva naturaleza, llegaban a ver más y más. Por un tiempo,
ellos ocasionalmente se circuncidaron, hicieron votos, se ungieron con aceite,
se bautizaron con el bautismo de Juan,
etc. todo lo cual era de una naturaleza externa y legal.
De hecho, al principio,
ni siquiera se habían dado cuenta de que el Espíritu Santo
iba a ser dado a los gentiles tanto como a los judíos,
a pesar de que Joel había profetizado claramente que sería derramado sobre toda carne.
Pero después, a medida que seguían a Cristo en la regeneración,
eran llevados más allá de la mezcla inicial de las cosas al principio.
Con el tiempo llegaron a ver claramente cómo el Espíritu
Santo cayó sobre los gentiles tanto como sobre los judíos,
y declararon que "`ni la circuncisión vale nada, ni la incircuncisión,
sino una nueva creación.`"^
footnote:[Gálatas 6:15]
Ellos encontraron que "`la unción del Santo`"^
footnote:[1 Juan 2:20]
es absolutamente suficiente para dar instrucción y juicio verdadero;
y entendieron que "`el bautismo que salva`" no es aquel que alcanza sólo la carne,
sino más bien aquel del Espíritu,
que bautiza el corazón y produce "`la respuesta de una buena conciencia hacia Dios,
por la resurrección de Jesucristo,`"^
footnote:[1 Pedro 3:21]
o por Su levantamiento espiritual en el alma.

Es común escuchar que la era apostólica es llamada la infancia del cristianismo;
y así como lo fue en cuanto al tiempo,
también lo fue con respecto a la continuación temporal
de unas pocas ceremonias y sombras exteriores.
Estos nuevos cristianos,
no podían ver a través del velo de las ceremonias y sombras exteriores, por lo tanto,
algunas sombras fueron mantenidas por un tiempo para no poner tropiezo
a otros que habían estado tan aferrados a las prácticas simbólicas
que no podían ser llevados rápidamente al punto de no usarlas.
Sin embargo, a medida que crecían en la gracia y en el conocimiento de Jesucristo,
el Espíritu estaba obrando en ellos para "`quitar lo primero, y establecer lo último,`"^
footnote:[Hebreos 10:9]
"`removiendo las cosas movibles, como cosas hechas,
para que quedaran las inconmovibles.`"^
footnote:[Hebreos 12:27]

En gran contraste con esto,
muchos de los líderes y gobernantes actuales de las
iglesias que profesan el nombre cristiano,
parecen pensar que,
aunque la asistencia del Espíritu Santo fue necesaria para la introducción
y soporte del cristianismo en los tiempos primitivos,
no hay necesidad de ella ahora.
Se cree que la iglesia ha madurado tanto por la sabiduría y aprendizaje del hombre (que
no tuvieron parte en su origen) que es absolutamente capaz de continuar sola.
De esta forma, la iglesia en gran medida se ha convertido en otra cosa,
y se encuentra sobre un fundamento distinto al antiguo.
Aunque todavía llama a Cristo su cabeza y se considera a sí misma Su cuerpo,
ella no recibe dirección inmediata de Él, ni siente la circulación de Su sangre,
que es la vida y la virtud de toda religión verdadera.
Por lo tanto,
la iglesia de hoy merece la reprensión del apóstol implícita en esta pregunta,
"`¿Tan necios sois?
¿Habiendo comenzado por el Espíritu, ahora os perfeccionáis por la carne?`"^
footnote:[Gálatas 3:3 RV2009]
En realidad, es demasiado evidente que las iglesias cristianas profesantes en general,
en lugar de haber avanzado a la madurez en el cristianismo,
están en un gran declive y apostasía de ese estado;
de lo contrario no podrían ser tan insensibles,
ni se atreverían a mostrarse tan opuestas a la vida de la religión
como para rechazar o menospreciar la parte más vital de la misma,
tratándola como extinguida, innecesaria o, al menos, imperceptible.
Seguramente una iglesia en esta condición merece bien la descripción del Espíritu,
dada a la iglesia degenerada de Sardis; "`Yo conozco tus obras,
que tienes nombre de que vives, y estás muerto.`"^
footnote:[Apocalipsis 3:1]
Sin embargo, aunque este parezca ser el caso en general, tengo la esperanza,
y verdaderamente creo,
que hay muchos miembros vivos y sensibles del cuerpo de Cristo dentro de esas iglesias.

La vitalidad y la gloria del cristianismo
radica en la administración pura del Espíritu Santo,
sin ningún velo de sombras legales o rituales.
El aprendizaje escolar es sólo un logro humano, y aunque es muy útil como siervo,
realmente no es parte del cristianismo.
Ni los conocimientos de la universidad, ni las formalidades de la autoridad humana,
pueden producir esa humildad que prepara el corazón para las enseñanzas de Dios.
Los débiles humanos, cuando poseen artes y lenguajes,
se hinchan con una presunción de superioridad,
la cual los aleja de la negación de sí mismos y de la cruz diaria,
hacia el orgullo y la autosuficiencia.

Estos, en lugar de esperar y depender de la sabiduría y del poder de Dios,
llegan a confiar en la sabiduría de este mundo y a sentirse satisfechos
con la repetición de las formas y ordenanzas externas.
Por otro lado, aquellos que "`adoran a Dios en Espíritu,
gloriándose en Cristo Jesús,`" no ponen su "`confianza en la carne.`"^
footnote:[Filipenses 3:3]
Y ¿Por qué? Porque "`el Espíritu es el que da vida; la carne para nada aprovecha.`"^
footnote:[Juan 6:63]
Por lo tanto,
cualquiera que niegue la necesidad de experimentar sensiblemente
al Espíritu Santo y sus operaciones internas,
sólo demuestra su propia falta de experiencia de ello.
El pueblo verdadero de Dios en todas las edades ha declarado su propio
sentido indudable de la iluminación y el empoderamiento divino;
y los apóstoles testificaron unánimemente que ellos tenían un sentido
claro y distintivo del Espíritu Santo en Sus diversas operaciones.
Como fue entonces, así es ahora,
y deberá continuar mientras los hombres estén sobre la tierra.

La misma obra interna de Dios es absolutamente necesaria en cada hombre,
y un sentido o conciencia correspondiente a ella (en medida) es claro y certero
para todos los que experimentan la regeneración. Porque tal como el hombre no
puede obtener verdadera felicidad fuera del reino de Dios,
ni entrar en él sin haber nacido del Espíritu,
así tampoco la obra del nuevo nacimiento es hecha imperceptiblemente en ningún alma.
No importa cuál sea el medio secreto o desconocido
que los hombres puedan imaginar o alegar,
una operación del Espíritu Santo que no se sienta no es regeneración,
sino un mero engaño. El Espíritu de Dios,
ya sea que opere a través de palabras e instrumentos o sin ellos, siempre viene en poder,
un poder que da un sentido innegable,
que es perfectamente distinto y superior a todos los demás poderes,
y que manifiesta un resplandor que, en momentos,
excede por mucho todas las luces naturales,
así como cuando el sol radiante excede el brillo tenue de una luciérnaga.
Este Espíritu Santo de luz y poder de vida es el gran y
fundamental principio de los reprochados Cuáqueros,
y el único y verdadero principio salvador, para toda la humanidad.
Es Cristo en el Espíritu la "`luz de los Gentiles,
y la salvación de Dios hasta lo postrero de la tierra,`"^
footnote:[Isaías 49:6]
quien siempre ha sido,
y siempre está listo para convertirse en el "`autor
de eterna salvación para todos los que le obedecen.`"^
footnote:[Hebreos 5:9]
