== Capítulo 10. La Operación de la Gracia Divina

Habiendo tratado de mostrar claramente algo de la caída del hombre,
y de la necesidad y los medios de su restauración a Dios,
ahora procederé a observar particularmente algunos
de los errores y malentendidos más comunes,
empezando por las doctrinas concernientes a la predestinación
individual y a la operación de la gracia divina.

Aunque el hombre no puede dar ni un paso hacia su salvación sin la ayuda de la gracia
de Dios como la primera y continua causa habilitadora (tanto del querer como del hacer),
esto no necesariamente significa (como algunos reformadores han insistido) que Dios es,
por lo tanto, el autor de la salvación de unos, y el autor de la destrucción de otros.
La verdad de este asunto, como está establecida claramente en las Escrituras,
es como sigue: 1. Que el hombre no tiene la capacidad de salvarse a sí mismo,
ni en su condición natural se encuentra en el estado en el que
tiene la misma libertad para hacer el bien o el mal según su antojo,
tampoco tiene posesión de aquella fe que es necesaria para su salvación. 2. Que
el Redentor proporciona una manifestación de Su Espíritu al alma de cada hombre,
mediante la cual, en ciertos tiempos,
Él reprueba las inclinaciones corruptas de los hombres,
los detiene en seco y pone en su poder la capacidad
de reflexionar sobre su condición presente,
y de entregarse a la operación de este Espíritu interno.
Si no se resiste, sino al contrario permanece en sumisión,
el Espíritu se apodera de él aún más, dándole la capacidad de creer,
de unirse y de permanecer en la operación del Espíritu que está sobre él. En esta situación,
siente fuerza y consuelo brotando de la Semilla (o medida
de gracia) que incrementan su fe y confianza en ella,
y gradualmente lo habilitan y lo llevan a volverse activo, es decir,
a unirse de corazón en consentimiento con sus operaciones, y a avanzar de fe a fe,
y de un grado de gracia a otro.
Esto continúa hasta que el alma llega a sentir y a experimentar
el verdadero nuevo nacimiento del Espíritu,
participando (en medida) de la luz, vida y naturaleza gloriosas del reino celestial.

Dios ha hecho al hombre una criatura racional,
y por lo tanto requiere su obediencia voluntaria: "`Si queréis y obedecéis,
comeréis el bien de la tierra.`"^
footnote:[Isaías 1:19 RV1977]
¿Es posible creer que Él pone el bien y el mal,
la vida y la muerte delante de los hombres (como testifican los registros sagrados),
y que una y otra vez los llama a escoger la vida y el bien,
y sin embargo no les permite hacerlo?
De hecho, cada precepto divino, cada exhortación, cada mandamiento, cada advertencia,
implica una libertad concedida para aceptar o rechazar; para obedecer o desobedecer.
Sin embargo, si Dios repetidamente visita a todos con los alcances de Su gracia,
y continúa una y otra vez tratando de convencerlos,
persuadirlos y atraerlos (como declaran las Escrituras) para que
Él pueda prevalecer en ellos y llevarlos al arrepentimiento,
¿no va lo más lejos posible sin violar la libertad racional que proporciona?
Dejen que el hombre rinda obediencia a Sus convicciones,
y entonces vean si puede acusar a su Creador de parcialidad o de duro trato.
Es el siervo inútil y perezoso que hace tales acusaciones en contra de su Maestro.

Sin duda, la educación y la tradición predisponen a las personas,
y crean un prejuicio en la mente contra toda doctrina
diferente de la que se les ha enseñado.
Sin embargo, la luz divina, a veces, repentinamente se lanza como dardo sobre el alma,
tan rápido como un relámpago,
y penetra a través de toda oscuridad y de cada falsa apariencia,
perturbando al alma en sus descansos impuros y en sus gratificaciones carnales,
mostrándole su esclavitud bajo todo eso,
e inspirando en ella el deseo y suspiro secreto por ser redimida.
Esto, al ser la revelación de la luz divina en la mente,
es llamado __el día de la visitación de Dios,__^
footnote:[Lucas 19:44; 1 Pedro 2:12]
el tiempo de gracia para el hombre,
donde la vida y la muerte se distinguen en él. En este tiempo,
al hombre no sólo se le da la libertad para elegir la vida (lo que antes no podía hacer),
sino también se le da una medida correspondiente de capacidad
para poder amar y adherirse a la gracia que lo visita,
y de ese modo llegar al arrepentimiento y a la salvación.
Porque esta gracia es el Espíritu del Salvador,
y por lo tanto trae consigo el poder de salvación, como dice el apóstol,
"`Porque la gracia de Dios se ha manifestado para salvación a todos los hombres,
enseñándonos que, renunciando a la impiedad y a los deseos mundanos,
vivamos en este siglo sobria, justa y piadosamente,
aguardando la esperanza bienaventurada y la manifestación
gloriosa de nuestro gran Dios y Salvador Jesucristo.`"^
footnote:[Tito 2:11-13]

Estas visitaciones misericordiosas de la gracia divina a menudo se repiten,
tanto de noche como de día. "`Dios,`" dice el inspirado Eliú,
"`en una o en dos maneras habla; pero el hombre no entiende.
Por sueño, en visión nocturna, cuando el sueño cae sobre los hombres,
cuando se adormecen sobre el lecho, entonces revela al oído de los hombres,
y les señala su consejo, para quitar al hombre de su obra,
y apartar del varón la soberbia.`"^
footnote:[Job 33:14-17]
Luego procede a mostrar cómo el Señor opera sobre el alma
sumisa en la obra de arrepentimiento y mortificación,
y cuál será el resultado.
Entonces, resume con estas palabras, "`Él mira sobre los hombres; y al que dijere: Pequé,
y pervertí lo recto, y no me ha aprovechado,
Dios redimirá su alma para que no pase al sepulcro, y su vida se verá en luz.
He aquí, todas estas cosas hace Dios dos y tres veces con el hombre,
para apartar su alma del sepulcro, y para iluminarlo con la luz de los vivientes.`"^
footnote:[Job 33:27-30]

De hecho,
el gran Padre de las misericordias se complace en continuar sus
visitaciones de gracia desde lo alto a los hombres rebeldes,
hasta que se hayan vuelto tan determinados en su iniquidad,
y tan habitualmente unidos a su servidumbre,
que al igual que los siervos en Éxodo 21:5-6, no quieren ser liberados de ella.
Entonces la noche viene sobre ellos, y el día de su visitación pasa;
porque Dios no contenderá para siempre con aquellos que
por mucho tiempo y con frecuencia han sido reprobados,
y sin embargo siguen endureciendo su cerviz. No, después de una larga paciencia,
Él retira el alcance de Su bondad misericordiosa y los deja caer bajo esa terrible sentencia,
"`El que es injusto, sea injusto todavía; y el que es inmundo, sea inmundo todavía.`"^
footnote:[Apocalipsis 22:11]

Cuando las personas están justamente endurecidas,
y entregadas a las concupiscencias de su propio corazón y a sus amados engaños,
y son dejadas en un estado de insensibilidad al Espíritu divino,
pueden confundir ciegamente su condición con una de paz y de seguridad.
Para estos, la conciencia se oscurece, como un libro cerrado que no pueden leer.
Pero en el día de la justa retribución del gran Juez de los vivos y de los muertos,
este volumen oculto será otra vez abierto por Aquél que abre y ninguno puede cerrar,
y se hará la justa retribución a todos de acuerdo a lo que está escrito allí.
Esto demostrará ser para cada hombre un libro de vida o un libro de muerte,
"`vida eterna a los que, perseverando en bien hacer,
buscan gloria y honra e inmortalidad,
pero ira y enojo a los que son contenciosos y no obedecen a la verdad,
sino que obedecen a la injusticia.`"^
footnote:[Romanos 2:7-8]

Por lo tanto,
concluimos razonablemente que Dios no sólo pone delante del hombre
el bien y el mal (en sus distinciones correctas) sino que,
al mismo tiempo, le da la capacidad de escoger qué quiere seguir.
Además de esto, Dios despierta y ayuda al hombre a desear la felicidad verdadera,
y mientras el corazón permanece en este deseo, Él le da poder al hombre para batallar,
esforzarse y luchar eficazmente por su liberación y preservación.

Las motivaciones más íntimas de la voluntad humana son imposibles
de discernir sin la luz del Espíritu de Dios,
y por falta de discernimiento,
algunos se han atrevido a acusar a Dios como el responsable de las distintas
respuestas de la humanidad a la visitación de la gracia divina,
haciéndolo a Él el autor principal de la maldad, rebelión y condenación del hombre.
Pero, ¿no es absurdo suponer que Dios produciría voluntariamente
lo que es contrario a Su naturaleza?
¿No es todo pecado una transgresión a la voluntad
de Dios y todo vicio contrario a Su naturaleza?
Entonces, ¿cómo podrían estas cosas ser producidas por un acto de Su voluntad,
o ser el fruto genuino de Su poder, ya sea directa o indirectamente?
¿Puede el entendimiento correcto llevar a un hombre a pensar que la voluntad de Dios,
en algún momento, sea contraria a Su naturaleza?
De la pureza, la bondad y la virtud, ninguna impureza, vicio ni maldad,
pueden surgir naturalmente.

Pero algunas Escrituras han sido objetadas, tales como,
"`Imposible es que no vengan tropiezos.`"
Cierto; pero ¿de dónde vienen?
No de Dios, sino de esa raíz de corrupción que entró y se esparció en el mundo.
Mientras esta raíz corrupta permanezca, los tropiezos surgirán naturalmente de ella;
y el mismo texto pronuncia, "`¡ay de aquel por quien vienen!`"^
footnote:[Lucas 17:1]
Pero el Señor dice que Él "`creó el mal,`"^
footnote:[Isaías 45:7 RV1602P]
y el profeta dice: "`¿Habrá algún mal en la ciudad, el cual Jehová no haya hecho?`"^
footnote:[Amos 3:6]
Esto no se refiere al mal moral,
sino más bien al mal y a la calamidad natural de dolor y de angustia,
que vienen en la forma de la hostilidad, de la enfermedad, de la hambruna, etc.,
que son los juicios de Dios sobre el hombre por desobediencia
y por cometer maldades de tipo moral.

Por lo tanto, de acuerdo a mi entendimiento,
el pecado consiste en que la criatura prefiere la indulgencia de su naturaleza
depravada por encima de la obediencia a la gracia divina;
tal indulgencia conduce al abuso de esa gracia, y por tanto a pensar,
hablar y actuar en contra de la voluntad manifiesta de su Creador.
Ahora,
es cierto que algunos obedecen y que otros rehúsan
obedecer la manifestación de la gracia divina;
pero creemos que Dios no es la causa de esta diferencia,
sino que se debe enteramente al individuo.
De hecho,
no es difícil creer que la misma naturaleza tenga efectos
diferentes en sujetos que están en condiciones diferentes.
Porque ante los ojos de todo hombre es evidente que los
rayos del sol ablandarán el alquitrán y endurecerán el barro.
Estos efectos contrarios no vienen de una diferencia entre los rayos solares,
sino de una diferencia entre la disposición del alquitrán y del barro para recibirlos.
De la misma manera,
el Espíritu Santo opera de formas diferentes en personas diferentes debido
a sus estados y disposiciones diferentes para recibir Sus influencias.
Dejen que aquel que duda de esto inquiera en su propia conciencia,
y allí el Testigo fiel (por medio de Sus condenaciones por
el mal) le mostrará claramente que la falta es suya.
¿Qué hombre hay en la tierra que no haya sido golpeado por la culpa y el remordimiento?
o ¿que no haya sentido en algunos momentos que se encienden dentro de
él inclinaciones y disposiciones hacia la virtud y hacia la vida piadosa?
Y habiendo seguido esta Guía, ¿no ha encontrado paz en su obediencia?
Pero habiéndose vuelto de ella para perseguir algo de la naturaleza contraria,
¿no ha sufrido angustia y condenación? ¿Necesitará una criatura razonable
más pruebas de que estas reprensiones y consuelos convencedores son los
juicios internos e inmediatos de un Espíritu justo,
bueno, poderoso, omnipresente y omnisciente?
¿Y con qué fin Dios trata al alma de cada hombre de esta manera,
sino para que todos puedan llegar al arrepentimiento y a experimentar la salvación?

Entonces, la primera causa iniciadora,
verdadera y legítima de la salvación del hombre es
la bondad y el amor de Dios para con él,
y la operación de Su propio Espíritu Santo en el alma del
hombre es el medio esencial por el cual Él obra la salvación,
a veces directamente y otras veces haciendo uso de medios secundarios,
como la predicación, leer las Escrituras y otros libros buenos, conversaciones piadosas,
adoración, misericordias, angustias, etc.
Pero es Dios a través de Su propio Espíritu Santo, quien hace todo lo bueno en el hombre,
tanto el querer como el hacer.
Es por gracia que somos salvos, por medio de la fe, o en el camino de la fe.
Esta fe obra por el amor de Dios^
footnote:[Gálatas 5:6]
para purificar el corazón,^
footnote:[Hechos 15:9]
y producir buenas obras.^
footnote:[Santiago 2:14-26]
Estas obras son los frutos genuinos de la verdadera fe, y son inseparables de ella:
por lo tanto, sin obras no podemos ser salvos.^
footnote:[Santiago 2:24]
Sin embargo, no es _por_ las obras que somos salvos,
como la causa de la salvación para nosotros, sino por gracia (que es su raíz),
y por la fe, por la cual creemos en Dios, nos abrimos a Él y lo recibimos,
nos unimos a Él, confiamos en Él, y por consiguiente echamos mano de la vida eterna.

Esta fe no es facultad nuestra, sino más bien el don de Dios para nosotros.^
footnote:[Hebreos 12:2, 2 Pedro 1:1, Filipenses 1:29]
Viene por gracia, la gracia gratuita de Dios, quien no quiere "`que ninguno perezca,
sino que todos procedan al arrepentimiento.`"^
footnote:[2 Pedro 3:9]
Aquél cuyas obras son malas no tiene esta fe salvadora,
sin importar cuales doctrinas o nociones crea.
Porque donde está la fe verdadera, necesariamente produce buenas obras.
De hecho, esta raíz nunca está sin sus frutos.
El apóstol Santiago dice "`Muéstrame tu fe sin tus obras,
y yo te mostraré mi fe por mis obras.`"^
footnote:[Santiago 2:18]
Sin embargo, estas obras no _merecen_ la salvación,
porque no deben ser atribuidas a nosotros, sino totalmente a Él que,
a través de su gracia,
nos ha llevado al bendito estado de fe viva en el que ellas se producen.
"`Porque por gracia sois salvos por medio de la fe; y esto no de vosotros,
pues es don de Dios; no por obras, para que nadie se gloríe. Porque somos hechura suya,
creados en Cristo Jesús para buenas obras,
las cuales Dios preparó de antemano para que anduviésemos en ellas.`"^
footnote:[Efesios 2:8-10]

Todas las almas que Dios ha hecho son igualmente Suyas,
y Aquél cuyas "`misericordias están sobre todas Sus obras,`"^
footnote:[Salmo 145:9]
no se olvida de ninguna de sus criaturas en la distribución de las mismas.
Él a ninguno le niega Sus talentos,
sino que los dispensa en porciones diferentes a personas diferentes.
A uno le da cinco talentos, y a otro dos, y a otro uno;
pero a cada uno se le da la manifestación divina suficiente para obrar su salvación,
si es creída y obedecida.
El Creador, justamente,
requiere un incremento correspondiente a la medida que proporciona;
y como Él sabe perfectamente hasta qué grado de progreso cada uno podría llegar,
al final juzgará a todos de acuerdo a su incremento,
su negligencia o su rechazo total del talento recibido.

En el tiempo de Ezequiel, el pueblo de Israel,
por una interpretación errónea del segundo mandamiento,
habían adoptado la noción de que los niños eran castigados por los pecados de sus padres,
por lo que se convirtió en un refrán entre ellos, "`Los padres comieron las uvas agrias,
y los dientes de los hijos tienen la dentera.`"
Por lo tanto,
el profeta fue comisionado particularmente para declarar
la voluntad inmutable de Dios en oposición a esto:
"`Vivo yo, dice Jehová el Señor,
que nunca más tendréis por qué usar este refrán en Israel.
He aquí que todas las almas son mías; como el alma del padre,
así el alma del hijo es mía; el alma que pecare, esa morirá.`"^
footnote:[Ezequiel 18:3-4]
"`El hijo no llevará el pecado del padre, ni el padre llevará el pecado del hijo;
la justicia del justo será sobre él, y la impiedad del impío será sobre él.`"^
footnote:[Ezequiel 18:20]
"`Y si dijereis: No es recto el camino del Señor; oíd ahora, casa de Israel:
¿No es recto mi camino?
¿no son vuestros caminos torcidos?
Apartándose el justo de su justicia, y haciendo iniquidad, él morirá por ello;
por la iniquidad que hizo, morirá. Y apartándose el impío de su impiedad que hizo,
y haciendo según el derecho y la justicia, hará vivir su alma.
Porque miró y se apartó de todas sus transgresiones que había cometido, de cierto vivirá;
no morirá.`"^
footnote:[Ezequiel 18:25-28]
"`Por tanto, yo os juzgaré a cada uno según sus caminos, oh casa de Israel,
dice Jehová el Señor. Convertíos, y apartaos de todas vuestras transgresiones,
y no os será la iniquidad causa de ruina.`"^
footnote:[Ezequiel 18:30]
El profeta repite aún más con el mismo propósito en este capítulo y en el 33. "`Vivo yo,
dice Jehová el Señor, que no quiero la muerte del impío,
sino que se vuelva el impío de su camino, y que viva.
Volveos, volveos de vuestros malos caminos; ¿por qué moriréis, oh casa de Israel?`"^
footnote:[Ezequiel 33:11]
"`Luego dirán los hijos de tu pueblo: No es recto el camino del Señor;
el camino de ellos es el que no es recto.
Cuando el justo se apartare de su justicia, e hiciere iniquidad, morirá por ello.
Y cuando el impío se apartare de su impiedad, e hiciere según el derecho y la justicia,
vivirá por ello.`"^
footnote:[Ezequiel 33:17-19]
Ahora,
es evidente que la muerte de la que se habla en estas
Escrituras no es la muerte común del cuerpo;
porque en cuanto a eso,
el mismo evento sucede a los justos y a los impíos. Sin duda alguna,
la muerte que se menciona aquí se refiere al estado perpetuo e infeliz de las almas
que salen del tiempo a la eternidad sin arrepentimiento y regeneración.

Es evidente, de todas estas expresas declaraciones, que el Todopoderoso,
"`no aflige ni entristece voluntariamente a los hijos de los hombres;`"^
footnote:[Lamentaciones 3:33]
y que "`no quiere que ninguno perezca, sino que todos procedan al arrepentimiento,`"^
footnote:[2 Pedro 3:9]
deseando "`que todos los hombres sean salvos y vengan al conocimiento de la verdad.`"^
footnote:[1 Timoteo 2:4]
Todas estas escrituras son manifestaciones claras
de la mente de Dios con respecto a este punto,
y deberían ser decisivas.
Los pecados de los hombres son el producto de su propia voluntad,
y no la voluntad de Dios.
"`¿Por qué moriréis, casa de Israel?`"^
footnote:[Ezequiel 18:31, 33:11]
Y, en verdad, está claro que hace todo lo posible por medios justos para impedirlo.
Por esa apremiante repetición, "`Volveos,
volveos de vuestros malos caminos,`" es manifiesto como Él pone
en poder de los hombres la capacidad de volverse de ellos.
Entonces ¿quién puede justificar su perversidad, o de algún modo cargar su pecado,
ya sea directa o indirectamente a Su cuenta?
Los hombres no son destruidos por alguna malevolencia en su Creador;
más bien son salvos por Su gracia,
la cual Él dispensa a todos desde Su incomparable
benevolencia que surge puramente de Su bondad infinita.
El hombre pecador no tiene nada que ofrecer.
Por lo tanto, Dios tendrá misericordia porque tendrá misericordia.
Sí, porque está lleno de misericordia,
la dispensará a sus desamparadas e indignas criaturas.
"`Yo,`" dice el Señor al pecador arrepentido,
"`yo soy el que borro tus rebeliones por amor de mí mismo,
y no me acordaré de tus pecados.`"^
footnote:[Isaías 43:25]

Varios textos y porciones de la Escritura han sido argumentados y utilizados
para atribuir una cruel parcialidad a nuestro Creador y Benefactor.
Se nos ha dicho que Él ordenó la obstinación de Faraón,
el pecado y locura de Sehón y de los reyes de Canaán,
la rebelión desleal de Sedequías en contra del rey de Babilonia,
los estragos de Nabucodonosor, etc.
Pero esto, debidamente considerado,
se ve que fue el ordenamiento de castigo por causa del pecado,
y no el ordenamiento del pecado para el castigo.
El Señor no endurece a ninguno hasta que se haya endurecido
a sí mismo más allá de toda posibilidad de arrepentimiento,
y entonces lo entrega al desorden de sus propias concupiscencias y vicios amados.
Y lo que se considera como injustas devastaciones (aunque
realmente lo son en cuanto a los que las comenten),
con respecto al Todopoderoso,
son la ejecución justa de Su justicia en contra de
aquellos que han llenado su medida de iniquidad,
y han abusado Su gracia bondadosa y larga paciencia hacia ellos,
hasta que Él decide no extendérselas más. Por lo tanto,
castiga la iniquidad arraigada de algunos por medio de la iniquidad de sus enemigos,
la cual Él permite que se vuelva contra ellos.
Pero después procede de la misma manera con aquellos
que fueron Sus instrumentos de castigo,
cuando también han llenado su medida.

El Ser divino es una sola esencia, perfectamente pura y simple.
Él es un solo poder eterno e inmutable, que crea y sustenta a todos los demás seres,
y que opera de diversas maneras según el estado de cada persona,
pero nunca contrariamente hacia los que están en la misma condición.
Puesto que todas las almas son igualmente Su creación inmediata,
no hay ninguna razón justa que pueda ser alegada para explicar por qué Él,
que es justo en todos Sus caminos, santo y misericordioso en todas Sus obras,
trataría con tanta desigualdad como para predestinar a algunas
a la felicidad eterna y a otras a la inevitable miseria.
¡Oh, Sus misericordias están sobre todo y para todos,
con una intención justa y llena de gracia hacia todos!
El bondadoso Redentor compró dones de gracia tanto para aquellos que son rebeldes,
como para los demás,
y todos son visitados con la manifestación de Su Espíritu
para que puedan obtener provecho a través de ella.
Y aunque los hombres se vuelven del poder que los visita,
y muchas veces se apartan de la ayuda que les es brindada, Él todavía los sigue,
una y otra vez, con mucha paciencia, y con frecuencia los vuelve a visitar,
debido a Su gracia y misericordia abundantes,
con el fin de convencerlos de que se arrepientan y sean salvos.
La condenación de los hombres, según nuestro Salvador,
no es el fruto de ningún decreto hecho de antemano, porque "`esta es la condenación:
que la luz vino al mundo, y los hombres amaron más las tinieblas que la luz,
porque sus obras eran malas.`"^
footnote:[Juan 3:19]
