== Capítulo 11. Las Escrituras y el Espíritu

Con respecto a las Escrituras,
estamos tan lejos de quitarles importancia o de oponernos al sentido verdadero de ellas,
que creemos firmemente y afirmamos sinceramente,
que el Espíritu Santo (en cualquier grado de iluminación
en que aparezca) nunca puede contradecirlas.
Son las interpretaciones privadas o particulares del hombre, sin iluminación divina,
a las que nos oponemos,
ya que son insuficientes para dar el verdadero significado de las Escrituras en disputa.
Además de la inhabilidad natural del hombre, sus diversos prejuicios,
sus pasiones predominantes, sus diferentes intereses y sus distintos líderes,
todos contribuyen a dar interpretaciones diferentes, y a veces opuestas,
del texto sagrado.
Muchos tienen las palabras del Espíritu en las Escrituras,
quienes no tienen la mente del Espíritu en sus corazones.

Sin iluminación divina,
el hombre no tiene capacidad suficiente para determinar
el sentido correcto de los textos dudosos y discutidos,
que son muchos.
De hecho,
la gran diferencia en las interpretaciones hechas
por personas aparentemente igual de sinceras,
y de las mejores habilidades naturales y aprendidas, de las mismas,
como también de diferentes denominaciones,
indica claramente cuán indispensable es la ayuda del Mismo
Autor Divino para el entendimiento correcto de ellos.
Anteriormente mostré que la razón del hombre está demasiado
nublada e influenciada por sus pasiones y prejuicios,
como para que sea justamente llamada la razón _correcta_,
porque a menudo manifiesta una gran diversidad en cuanto a asuntos espirituales,
e incluso una inestabilidad en la misma persona.
La razón correcta es la verdad, inmutablemente la misma e incapaz de errar,
y por lo tanto existe sólo en la naturaleza divina, de la cual el hombre debe, en medida,
hacerse partícipe, para rectificar su razón caída y falible.

Ni la naturaleza, ni la educación pueden darle al hombre el sentido del Espíritu Santo,
ni interpretar las expresiones del Espíritu con certeza.
Por lo tanto, se afirma verdaderamente, no sólo por los Cuáqueros,
sino también por muchos escritores distinguidos de diversas profesiones,
antiguos y modernos,
que la iluminación interna del Espíritu Santo es absolutamente necesaria para cada hombre,
a fin de entender correctamente las Escrituras.

Ahora, muchos imponen su propia opinión particular sobre algunas partes de la Escritura,
como la intención verdadera del Espíritu Santo,
aunque niegan la experiencia de la iluminación del Espíritu Santo en sus corazones.
Pero, ¿por qué debería dárseles algún crédito a tales afirmaciones,
viendo que existe tanta diversidad de opiniones?
Ellos alegan, '`¡La Escritura es infalible!`' Estoy de acuerdo;
pero ¿cómo se transmite infaliblemente su verdadero significado a cada lector?
¿A través del estudio e instrucción humanas?
¡Eso ha llevado a todas las diferencias y desacuerdos con respecto a ellas!
La simple verdad del asunto es que nada más que el Espíritu de la Sabiduría divina,
de donde provinieron las Escrituras, puede dar el sentido genuino de ellas.
Porque, "`nadie conoce las cosas de Dios, sino el Espíritu de Dios.`"^
footnote:[1 Corintios 2:11]
¿Qué importa la infalibilidad de la Escritura para
alguien que no conoce al Maestro infalible de ella?
Si todos los que han tenido las Escrituras conocieran a este Maestro,
ninguno podría malentender, o diferir entre sí acerca de ellas.
Sin embargo, es demasiado evidente, por las diferencias entre los cristianos,
que ellos sí las malentienden.
Tal confusión no debe ser atribuida a ningún defecto en los escritos sagrados,
sino a la incapacidad común en el entendimiento de los hombres,
para descubrir el sentido correcto de las palabras de Dios.
¿Qué, pues,
es capaz de abrir las Escrituras al entendimiento
de los hombres aparte del Espíritu Santo?
La pregunta no es si las Escrituras, tal como están escritas por la inspiración divina,
son infaliblemente correctas.
Sin duda lo son.
La pregunta es, si todos los que las leen, son infaliblemente capaces de entenderlas.
Algunos dicen que, si las Escrituras no pueden entenderse sin el Espíritu,
son dadas en vano.
Pero esto es contradecir las Escrituras mismas,
que declaran claramente que "`a cada uno le es dada
la manifestación del Espíritu para provecho.`"^
footnote:[1 Corintios 12:7]
Las palabras del apóstol son claras en este asunto:
"`Nosotros no hemos recibido el espíritu del mundo,
sino el Espíritu que proviene de Dios, para que sepamos lo que Dios nos ha concedido,
lo cual también hablamos, no con palabras enseñadas por sabiduría humana,
sino con las que enseña el Espíritu, acomodando lo espiritual a lo espiritual.
Pero el hombre natural no percibe las cosas que son del Espíritu de Dios,
porque para él son locura, y no las puede entender,
porque se han de discernir espiritualmente.`"^
footnote:[1 Corintios 2:12-14]

Las doctrinas de las Escrituras son de varios tipos.
Ellas exhiben las morales justas y la conducta benevolente de forma superior
a los mejores escritores éticos de todas las edades y naciones.
Estas son aceptadas general y apropiadamente como de obligación natural,
universal e inalterable,
y son suficientemente sencillas y claras para el entendimiento común de cada hombre.
Pero los asuntos relacionados a la fe y a la adoración,
habiendo pasado por muchas adiciones y alteraciones circunstanciales,
de acuerdo a las diferentes dispensaciones de la Sabiduría divina,
no han sido tan claros para el entendimiento de los hombres,
ni los hombres han estado tan unidos en su opinión
acerca de ellos como en el caso de los deberes morales.
Desde la publicación del Nuevo Testamento,
han existido y abundado las opiniones diferentes acerca del significado verdadero,
especialmente en asuntos de la fe.
¿Y cómo se pueden resolver estas diferencias?
El sabio erudito A. dice que un texto particular significa esto y lo otro.
El sabio erudito B. insiste en que se debe entender en un sentido diferente,
tal vez contrario.
Apelan al contexto y sin embargo siguen igualmente con opiniones diferentes,
y seguros de estar en lo correcto.
Pasan de un texto a otro, y de críticos a comentaristas,
hasta agotar a todos los que puedan encontrar o forzar para su propósito,
pero continúan en la misma, o tal vez más discordia que al principio.
¿Qué les queda para determinar el asunto?
¿Podrán hacerlo las iglesias o concilios?
Ellos debaten de año en año, o de siglo en siglo,
y dejan las diferencias tan amplias como las encontraron.
El sentido verdadero sigue estando solamente con el Autor divino de los textos en disputa,
y sólo Él puede comunicarlo.
¡Ay!, este ha sido el caso por muchos siglos,
y continuará siempre mientras que los hombres prefieran sus propios prejuicios,
imaginaciones y razonamientos,
antes que las directrices internas del Espíritu de la Verdad.

Creemos que las Escrituras son la regla de gobierno y guía de todos los que las tienen,
en la medida que tengan un entendimiento correcto de ellas.
No obstante, por las siguientes razones, no podemos afirmar que son el director único,
principal, y universal para la humanidad en cuestiones de deberes religiosos:
1+++.+++ No son el _único_ director porque el Espíritu de
Dios en el corazón y conciencia del hombre,
innegablemente,
dirige también. 2. No son el director _principal_ porque
la iluminación del Espíritu Santo que las produjo,
es necesaria para abrir el sentido verdadero de muchas de sus partes,
sobre las cuales difieren muchísimo las interpretaciones de los hombres.
El Espíritu, de donde provienen las Escrituras, siendo su origen,
es por lo tanto superior a ellas;
y dado que sólo el Espíritu puede revelar el significado de Sus palabras,
las palabras son secundarias al Espíritu, como un instrumento en Sus manos.
3+++.+++ No son el director _universal_ porque no es probable que uno de diez,
incluso uno de cada veinte de la humanidad,
alguna vez haya tenido la oportunidad de poseerlas.
Por lo tanto, viendo que este es el caso,
no pueden ser debidamente declaradas como la regla
perfecta adecuada y universal de la humanidad.

Por consiguiente,
estimamos las Escrituras como la regla o guía secundaria de los cristianos,
las cuales han sido divinamente comunicadas para
el uso de todos a quienes les puedan llegar.
Y puesto que son intrínsecamente superiores en excelencia a todos los demás escritos,
las preferimos por encima de todos ellos,
y las utilizamos con la misma gratitud y consolación que cualquier cristiano en la tierra,
creyendo verdaderamente que "`se escribieron para nuestra enseñanza,
a fin de que por la paciencia y la consolación de las Escrituras, tengamos esperanza.`"^
footnote:[Romanos 15:4]
No despreciamos las Escrituras, de hecho las mantenemos en su lugar apropiado,
como superiores a todas las obras de los hombres,
pero subordinadas a su Comunicador Supremo y único Explicador seguro.
Porque el Espíritu Santo es necesario para el uso correcto de ellas,
como un agente con un instrumento;
y ¿qué es un instrumento sin una mano para guiarlo y darle fuerza?
Y ¿cuál es superior, el agente o el instrumento?
El Espíritu Santo es la sabiduría original de la cual provienen las Escrituras,
y el único poder que puede abrirlas y hacer su efecto correcto.
El Espíritu de la Verdad es dado para guiar a toda verdad, y es Él,
el único que puede hacerlo,
siendo por lo tanto la Guía Suprema proporcionada a la humanidad.

Es insostenible e irracional afirmar que algo podría
actuar como el director único y principal,
cuando el Espíritu de Dios se ha comunicado con ese propósito.
Los mismos pasajes de la Escritura se muestran tan diferentes para cada persona,
como difieren sus entendimientos el uno del otro.
Por lo tanto, el entendimiento humano debe ser rectificado,
para que sean capaces de ver esas verdades en la misma luz.
El Espíritu de la Verdad es el Rectificador,
Él único que puede unir a los hombres en el sentido verdadero.
No dudamos llamar a las Escrituras colectivamente una regla divina;
pero nos oponemos a llamarlas _la_ regla de la fe y la práctica,
no sea que esto implique que no buscamos nada más para que sea nuestra guía o líder.

Las mismas Escrituras testifican abundantemente que hay algo superior a ellas,
que todos deben buscar y atender.
Ese algo es el Espíritu Santo del Legislador Supremo de los hombres,
el Espíritu del Autor de los escritos sagrados.
Y es en y por Su luz y poder,
que las Escrituras se vuelven un instrumento útil y adecuado
para los propósitos que se pretenden con ellas.
Como un buen reloj de sol, son verdaderas y perfectas según su propósito y género,
esto es, como escritos.
Sin embargo,
ellas apropiadamente pueden tener el mismo lema que
el reloj de sol--_Non sine lunine_ (Es decir,
'`Nada sin luz`'). Porque como un reloj de sol sin
los rayos solares no tiene ningún uso verdadero,
tampoco un pasaje ambiguo de la Escritura comunica infaliblemente
la mente del Espíritu Santo a diferentes entendimientos,
a menos que los rayos luminosos del Sol de Justicia lo revelen a la mente atenta.

Nuestros oponentes llaman a las Escrituras la regla principal.
Confesamos que es la regla _escrita_ principal,
y en todas las disputas entre ellos y nosotros, respetamos sus decretos,
según nuestro entendimiento del significado de ellas,
lo cual ellos también dicen hacer según el suyo.
Por lo tanto,
en todas las diferencias públicas recurrimos intencionalmente a la misma regla con ellos.
Pero nosotros también tenemos tanta Escritura clara como experiencia para
respaldar nuestra creencia (con respecto al deber de cada individuo en
particular) de que todos tienen en su propio pecho una regla o guía de
la consciencia más cercana y certera que las Escrituras,
a saber--"`la manifestación del Espíritu para provecho.`"^
footnote:[1 Corintios 12:7]
Y cuando esta guía se observa debidamente,
da la interpretación correcta de la Escritura (hasta donde sea necesario),
como también el sentido del deber de cada persona en particular.
De hecho, cuando alguien siente al testigo fiel de Dios en su conciencia,
condenándolo por lo que está mal y aprobándolo por lo que está bien,
¿no encuentra que este testigo le habla más claro,
particular y convincentemente a su caso y estado
que lo que puede leer en las palabras de la Escritura?
¿Y concluirá entonces que este testigo que verdaderamente
discierne es menos que aquel Espíritu de la Verdad,
o Consolador, que "`convence al mundo de pecado, de justicia y de juicio?`"^
footnote:[Juan 16:8]
Pero ¡ay! he observado en los que no obedecen a este testigo celestial,
que la opinión de cada hombre sobre la Escritura _es_ su Escritura,
y cuando le propone a su oponente que todo sea determinado por la Escritura,
quiere decir de acuerdo con su propia compresión de su significado.

Cuando Cristo, después de Su resurrección, "`abrió el entendimiento de sus discípulos,
para que entendiesen las Escrituras,`"^
footnote:[Lucas 24:45]
¿no fue la iluminación divina en sus entendimientos una evidencia mucho más clara,
certera y superior de su significado,
de lo que toda su lectura y estudio podrían haberles proporcionado sin
tal iluminación? ¿Se ha vuelto la humanidad mucho más sabia y astuta,
que ya no tiene necesidad de Su ayuda para abrirle su entendimiento?
¿El aprendizaje de sus escuelas y universidades es tan perfecto como para
hacer que la iluminación de Dios sea completamente innecesaria?
Los innumerables enfrentamientos y debates de los sacerdotes y maestros intelectuales
con respecto al significado de la Escritura ¿son una prueba de la unidad en sus sentimientos?
¡Oh, consideren! ¿Cómo pueden afirmar que la Escritura es el criterio final y certero,
cuando es precisamente el significado de la Escritura
lo que da lugar a toda la incertidumbre y diferencia?
Por lo tanto, es seguro que, sin la iluminación divina,
cada lector de los textos sagrados acepta cualquier
significado que sus suposiciones le fabriquen,
lo cual es la causa de las innumerables diferencias entre los cristianos profesantes.
